import { NextRequest,NextResponse } from "next/server";
import { requireAdminApi,logAdminActivity } from "@/lib/admin-auth";
import { connectToDatabase } from "@/lib/db";
import { calculateInvoice,nextInvoiceNumber } from "@/lib/invoice-utils";
import { Invoice } from "@/models/Invoice";

const clean=(v:unknown,max=1000)=>String(v??"").trim().slice(0,max);
export async function GET(request:NextRequest){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});await connectToDatabase();const url=new URL(request.url);const q=clean(url.searchParams.get("q"),100);const status=clean(url.searchParams.get("status"),30);const payment=clean(url.searchParams.get("payment"),30);const filter:Record<string,unknown>={};if(q)filter.$or=[{invoiceNumber:{$regex:q,$options:"i"}},{"customer.name":{$regex:q,$options:"i"}},{"customer.phone":{$regex:q,$options:"i"}},{"trip.destination":{$regex:q,$options:"i"}}];if(["draft","issued","cancelled"].includes(status))filter.status=status;if(["unpaid","partial","paid"].includes(payment))filter.paymentStatus=payment;const items=await Invoice.find(filter).sort({issueDate:-1,createdAt:-1}).limit(250).lean();return NextResponse.json({items});}
export async function POST(request:NextRequest){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"Invalid request."},{status:400});const customer=(body.customer??{}) as Record<string,unknown>;const name=clean(customer.name,120);if(name.length<2)return NextResponse.json({error:"Customer name is required."},{status:400});const calc=calculateInvoice(body);if(!calc.lineItems.length)return NextResponse.json({error:"Add at least one invoice item."},{status:400});await connectToDatabase();const invoiceNumber=await nextInvoiceNumber();const trip=(body.trip??{}) as Record<string,unknown>;const issueDate=body.issueDate?new Date(String(body.issueDate)):new Date();const dueDate=body.dueDate?new Date(String(body.dueDate)):null;const travelDate=trip.travelDate?new Date(String(trip.travelDate)):null;const item=await Invoice.create({invoiceNumber,issueDate:Number.isNaN(issueDate.getTime())?new Date():issueDate,dueDate:dueDate&& !Number.isNaN(dueDate.getTime())?dueDate:null,customer:{name,phone:clean(customer.phone,30),email:clean(customer.email,160),address:clean(customer.address,500),gstin:clean(customer.gstin,30)},trip:{serviceType:clean(trip.serviceType,160),pickup:clean(trip.pickup,200),destination:clean(trip.destination,200),travelDate:travelDate&& !Number.isNaN(travelDate.getTime())?travelDate:null,vehicle:clean(trip.vehicle,160),vehicleNumber:clean(trip.vehicleNumber,80),driverName:clean(trip.driverName,120)},...calc,paymentMethod:["cash","upi","bank_transfer","card","other"].includes(clean(body.paymentMethod,30))?clean(body.paymentMethod,30):"",status:["draft","issued"].includes(clean(body.status,30))?clean(body.status,30):"issued",notes:clean(body.notes,2000),terms:clean(body.terms,2000),createdBy:admin.id,updatedBy:admin.id});await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Created invoice",entity:"Invoice",entityId:item._id.toString(),metadata:{invoiceNumber,total:item.total}});return NextResponse.json({item},{status:201});}
