import { NextRequest,NextResponse } from "next/server";
import { requireAdminApi,logAdminActivity } from "@/lib/admin-auth";
import { connectToDatabase } from "@/lib/db";
import { calculateInvoice,nextInvoiceNumber } from "@/lib/invoice-utils";
import { Invoice } from "@/models/Invoice";

const clean=(v:unknown,max=1000)=>String(v??"").trim().slice(0,max);
const media=(v:unknown)=>{const m=(v??{}) as Record<string,unknown>;return{url:clean(m.url,1000),publicId:clean(m.publicId,500)}};
export async function GET(request:NextRequest){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});await connectToDatabase();const url=new URL(request.url);const q=clean(url.searchParams.get("q"),100);const payment=clean(url.searchParams.get("payment"),30);const filter:Record<string,unknown>={};if(q)filter.$or=[{invoiceNumber:{$regex:q,$options:"i"}},{customerName:{$regex:q,$options:"i"}},{customerPhone:{$regex:q,$options:"i"}},{vehicleNumber:{$regex:q,$options:"i"}},{itinerary:{$regex:q,$options:"i"}}];if(["unpaid","partial","paid"].includes(payment))filter.paymentStatus=payment;const items=await Invoice.find(filter).sort({billDate:-1,createdAt:-1}).limit(250).lean();return NextResponse.json({items});}
export async function POST(request:NextRequest){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"Invalid request."},{status:400});const customerName=clean(body.customerName,120);const vehicleName=clean(body.vehicleName,120);const vehicleNumber=clean(body.vehicleNumber,40);if(customerName.length<2)return NextResponse.json({error:"Customer name is required."},{status:400});if(!vehicleName)return NextResponse.json({error:"Vehicle name is required."},{status:400});if(!vehicleNumber)return NextResponse.json({error:"Vehicle number is required."},{status:400});let calc;try{calc=calculateInvoice(body)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Invalid invoice values."},{status:400})}if(calc.totalKm<=0||calc.pricePerKm<=0)return NextResponse.json({error:"Total KM and price per KM must be greater than 0."},{status:400});await connectToDatabase();const invoiceNumber=await nextInvoiceNumber();const billDate=body.billDate?new Date(String(body.billDate)):new Date();const travelDate=body.travelDate?new Date(String(body.travelDate)):null;const item=await Invoice.create({invoiceNumber,billDate:Number.isNaN(billDate.getTime())?new Date():billDate,customerName,customerPhone:clean(body.customerPhone,30),travelDate:travelDate&&!Number.isNaN(travelDate.getTime())?travelDate:null,travelType:body.travelType==="itinerary"?"itinerary":"distance",itinerary:clean(body.itinerary,1000),vehicleName,vehicleNumber,...calc,otherChargesLabel:clean(body.otherChargesLabel,120)||"Other Charges",paymentMethod:["cash","upi","bank_transfer","card","other"].includes(clean(body.paymentMethod,30))?clean(body.paymentMethod,30):"",status:["draft","issued"].includes(clean(body.status,30))?clean(body.status,30):"issued",notes:clean(body.notes,2000),signatoryName:clean(body.signatoryName,120)||"Authorized Signatory",signatureImage:media(body.signatureImage),stampImage:media(body.stampImage),createdBy:admin.id,updatedBy:admin.id});await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Created invoice",entity:"Invoice",entityId:item._id.toString(),metadata:{invoiceNumber,total:item.total}});return NextResponse.json({item},{status:201});}
