import { NextRequest,NextResponse } from "next/server";
import { Types } from "mongoose";
import { requireAdminApi,logAdminActivity } from "@/lib/admin-auth";
import { connectToDatabase } from "@/lib/db";
import { calculateInvoice } from "@/lib/invoice-utils";
import { Invoice } from "@/models/Invoice";

type Context={params:Promise<{id:string}>};const clean=(v:unknown,max=1000)=>String(v??"").trim().slice(0,max);const media=(v:unknown)=>{const m=(v??{}) as Record<string,unknown>;return{url:clean(m.url,1000),publicId:clean(m.publicId,500)}};
export async function GET(_:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid invoice id."},{status:400});await connectToDatabase();const item=await Invoice.findById(id).lean();if(!item)return NextResponse.json({error:"Invoice not found."},{status:404});return NextResponse.json({item});}
export async function PATCH(request:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid invoice id."},{status:400});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"Invalid request."},{status:400});await connectToDatabase();const item=await Invoice.findById(id);if(!item)return NextResponse.json({error:"Invoice not found."},{status:404});const merged={totalKm:body.totalKm??item.totalKm,pricePerKm:body.pricePerKm??item.pricePerKm,tollIncluded:body.tollIncluded??item.tollIncluded,tollAmount:body.tollAmount??item.tollAmount,parkingIncluded:body.parkingIncluded??item.parkingIncluded,parkingAmount:body.parkingAmount??item.parkingAmount,otherCharges:body.otherCharges??item.otherCharges,taxRate:body.taxRate??item.taxRate,amountPaid:body.amountPaid??item.amountPaid};let calc;try{calc=calculateInvoice(merged)}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"Invalid invoice values."},{status:400})}if(calc.totalKm<=0||calc.pricePerKm<=0)return NextResponse.json({error:"Total KM and price per KM must be greater than 0."},{status:400});item.customerName=clean(body.customerName??item.customerName,120);item.customerPhone=clean(body.customerPhone??item.customerPhone,30);item.vehicleName=clean(body.vehicleName??item.vehicleName,120);item.vehicleNumber=clean(body.vehicleNumber??item.vehicleNumber,40);item.travelType=body.travelType==="itinerary"?"itinerary":"distance";item.itinerary=clean(body.itinerary??item.itinerary,1000);if(body.billDate)item.billDate=new Date(String(body.billDate));if(body.travelDate)item.travelDate=new Date(String(body.travelDate));Object.assign(item,calc);item.otherChargesLabel=clean(body.otherChargesLabel??item.otherChargesLabel,120)||"Other Charges";if(typeof body.status==="string"&&["draft","issued","cancelled"].includes(body.status))item.status=body.status;if(typeof body.paymentMethod==="string"&&["cash","upi","bank_transfer","card","other",""].includes(body.paymentMethod))item.paymentMethod=body.paymentMethod;item.notes=clean(body.notes??item.notes,2000);item.signatoryName=clean(body.signatoryName??item.signatoryName,120)||"Authorized Signatory";if(body.signatureImage!==undefined)item.signatureImage=media(body.signatureImage);if(body.stampImage!==undefined)item.stampImage=media(body.stampImage);item.updatedBy=admin.id;await item.save();await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Updated invoice",entity:"Invoice",entityId:id,metadata:{invoiceNumber:item.invoiceNumber,total:item.total,paymentStatus:item.paymentStatus}});return NextResponse.json({item});}
export async function DELETE(_:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid invoice id."},{status:400});await connectToDatabase();const item=await Invoice.findByIdAndDelete(id);if(!item)return NextResponse.json({error:"Invoice not found."},{status:404});await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Deleted invoice",entity:"Invoice",entityId:id,metadata:{invoiceNumber:item.invoiceNumber}});return NextResponse.json({success:true});}
