import { NextRequest,NextResponse } from "next/server";
import { Types } from "mongoose";
import { requireAdminApi,logAdminActivity } from "@/lib/admin-auth";
import { connectToDatabase } from "@/lib/db";
import { calculateInvoice } from "@/lib/invoice-utils";
import { Invoice } from "@/models/Invoice";

type Context={params:Promise<{id:string}>};const clean=(v:unknown,max=1000)=>String(v??"").trim().slice(0,max);
export async function GET(_:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid invoice id."},{status:400});await connectToDatabase();const item=await Invoice.findById(id).lean();if(!item)return NextResponse.json({error:"Invoice not found."},{status:404});return NextResponse.json({item});}
export async function PATCH(request:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid invoice id."},{status:400});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"Invalid request."},{status:400});await connectToDatabase();const item=await Invoice.findById(id);if(!item)return NextResponse.json({error:"Invoice not found."},{status:404});const customer=(body.customer??item.customer) as Record<string,unknown>;const trip=(body.trip??item.trip) as Record<string,unknown>;const calc=calculateInvoice(body.lineItems?body:{...body,lineItems:item.lineItems,discountType:body.discountType??item.discountType,discountValue:body.discountValue??item.discountValue,taxRate:body.taxRate??item.taxRate,amountPaid:body.amountPaid??item.amountPaid});if(!calc.lineItems.length)return NextResponse.json({error:"Add at least one invoice item."},{status:400});item.customer={name:clean(customer.name,120),phone:clean(customer.phone,30),email:clean(customer.email,160),address:clean(customer.address,500),gstin:clean(customer.gstin,30)};item.trip={serviceType:clean(trip.serviceType,160),pickup:clean(trip.pickup,200),destination:clean(trip.destination,200),travelDate:trip.travelDate?new Date(String(trip.travelDate)):null,vehicle:clean(trip.vehicle,160),vehicleNumber:clean(trip.vehicleNumber,80),driverName:clean(trip.driverName,120)};Object.assign(item,calc);if(body.issueDate)item.issueDate=new Date(String(body.issueDate));item.dueDate=body.dueDate?new Date(String(body.dueDate)):null;if(typeof body.status==="string"&&["draft","issued","cancelled"].includes(body.status))item.status=body.status;if(typeof body.paymentMethod==="string"&&["cash","upi","bank_transfer","card","other",""].includes(body.paymentMethod))item.paymentMethod=body.paymentMethod;item.notes=clean(body.notes??item.notes,2000);item.terms=clean(body.terms??item.terms,2000);item.updatedBy=admin.id;await item.save();await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Updated invoice",entity:"Invoice",entityId:id,metadata:{invoiceNumber:item.invoiceNumber,total:item.total,paymentStatus:item.paymentStatus}});return NextResponse.json({item});}
export async function DELETE(_:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid invoice id."},{status:400});await connectToDatabase();const item=await Invoice.findByIdAndDelete(id);if(!item)return NextResponse.json({error:"Invoice not found."},{status:404});await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Deleted invoice",entity:"Invoice",entityId:id,metadata:{invoiceNumber:item.invoiceNumber}});return NextResponse.json({success:true});}
