import Image from "next/image";
import Link from "next/link";
import { BadgeIndianRupee, Clock3, FileText, Headphones, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { SiteCta } from "@/components/layout/site-cta";
import { FaqInteractive } from "@/components/faq/faq-interactive";

const highlights=[[Headphones,"Quick Answers","Get instant answers to common questions"],[ShieldCheck,"Trusted & Reliable","Transparent information you can trust"],[FileText,"Clear & Simple","Easy to understand information"],[Clock3,"24/7 Assistance","Our team is always here to help you"]] as const;
const trustItems=[[BadgeIndianRupee,"Best Price Guarantee","Competitive pricing with no hidden surprises"],[ShieldCheck,"Safe & Comfortable","Well-maintained vehicles and experienced drivers"],[Clock3,"On-Time Service","Punctual pickups and dependable travel"],[UsersRound,"Customer Satisfaction","Trusted by travelers across Rajasthan and India"],[Sparkles,"Easy Booking","Simple booking through call, WhatsApp, or enquiry"]] as const;

export function FaqPageContent(){return <>
<section className="relative overflow-hidden bg-[#f8f7f2]"><div className="absolute inset-0"><Image src="https://images.pexels.com/photos/797824/pexels-photo-797824.jpeg?auto=compress&cs=tinysrgb&w=1000" alt="Mehrangarh Fort and the Blue City of Jodhpur, Rajasthan" fill priority fetchPriority="high" quality={60} className="object-cover object-center" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-white/95 via-white/72 via-52% to-white/5"/></div><div className="relative mx-auto min-h-[430px] max-w-[1180px] px-4 py-12 sm:py-16"><div className="flex items-center gap-2 text-xs text-[#4f5b50]"><Link href="/" className="hover:text-[#0b6531]">Home</Link><span>›</span><span>FAQ</span></div><div className="mt-8 max-w-[620px]"><h1 className="font-serif text-5xl font-bold leading-[.98] text-[#17341f] sm:text-6xl">Frequently Asked <span className="block text-[#ca7c1c]">Questions</span></h1><div className="mt-5 flex items-center gap-3 text-[#d29a2c]"><span className="h-px w-10 bg-current"/><span>✤</span><span className="h-px w-10 bg-current"/></div><p className="mt-6 max-w-[520px] text-sm leading-7 text-[#435045]">Find answers to common questions about our services, bookings, vehicles, payments, and travel solutions.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:max-w-[820px] lg:grid-cols-4">{highlights.map(([Icon,title,text])=><div key={title} className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#edf5e8] text-[#0b6531]"><Icon className="h-5 w-5"/></div><div><p className="text-sm font-bold text-[#1d3422]">{title}</p><p className="mt-1 text-[11px] leading-5 text-[#667067]">{text}</p></div></div>)}</div></div></section>
<FaqInteractive/>
<section className="defer-render bg-[#fff8ed] py-12"><div className="mx-auto max-w-[1180px] px-4"><h2 className="text-center font-serif text-3xl font-bold text-[#17341f]">Why Travelers Choose Rani Tour&apos;s</h2><div className="mx-auto mt-3 h-px w-16 bg-[#d29a2c]"/><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-5">{trustItems.map(([Icon,title,text])=><div key={title} className="text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-[#c7d6c2] bg-white text-[#0b6531]"><Icon className="h-5 w-5"/></div><h3 className="mt-4 text-sm font-bold text-[#203524]">{title}</h3><p className="mx-auto mt-2 max-w-[190px] text-[11px] leading-5 text-[#667067]">{text}</p></div>)}</div></div></section>
<SiteCta/>
</>}
