import Image from "next/image";
import Link from "next/link";
import { CarFront, CheckCircle2, Clock3, Headphones, Luggage, MapPin, Route as RouteIcon, ShieldCheck, UsersRound } from "lucide-react";
import { TripSearch } from "@/components/home/trip-search";
import { SiteCta } from "@/components/layout/site-cta";

type Img={url:string;alt?:string};type Feature={title:string;description?:string};type Card={title:string;description?:string;image?:Img|null};type Route={title:string;from?:string;to?:string;durationLabel?:string;image?:Img|null};type Service={title:string;slug:string;serviceType:string;pageTemplate?:string;tagline?:string;shortDescription:string;overview?:string;heroImage:Img;bookingForm?:{title?:string;showReturnDate?:boolean;showTime?:boolean;showTransferType?:boolean;showFlightNumber?:boolean;showVehicleType?:boolean;showPassengers?:boolean};heroFeatures?:Feature[];whyChooseFeatures?:Feature[];serviceCards?:Card[];popularRoutes?:Route[];useCases?:Card[]};type Fleet={_id:string;name:string;modelLabel?:string;image?:Img;seatCount?:number;seatingLabel?:string;luggageCount?:number;luggageLabel?:string;category?:string;ac?:boolean};
const sectionCopy:Record<string,{whyEyebrow:string;whyTitle:string;contentEyebrow:string;contentTitle:string;useEyebrow:string;useTitle:string}>={
"jodhpur-local-taxi":{whyEyebrow:"Why Choose Rani Tours Local Taxi?",whyTitle:"Best Local Taxi Service in Jodhpur",contentEyebrow:"Popular Local Places in Jodhpur",contentTitle:"Explore Jodhpur With Us",useEyebrow:"Perfect for Local Travel",useTitle:"Comfortable Rides for Every Need"},
"outstation-taxi":{whyEyebrow:"Why Choose Outstation Taxi With Rani Tours?",whyTitle:"Your Journey, Our Responsibility",contentEyebrow:"Top Outstation Routes",contentTitle:"Travel from Jodhpur to Popular Destinations",useEyebrow:"Choose Your Journey",useTitle:"One Way, Round Trip or Multi-City"},
"one-way-taxi":{whyEyebrow:"Why Choose Our One Way Taxi?",whyTitle:"Simple, Comfortable One Way Travel",contentEyebrow:"Popular One Way Routes",contentTitle:"Travel Directly to Your Destination",useEyebrow:"Perfect for One Way Travel",useTitle:"Travel Smart Without a Return Plan"},
"round-trip-taxi":{whyEyebrow:"Why Choose Rani Tours for Round Trips?",whyTitle:"Travel Out and Return With Ease",contentEyebrow:"Popular Round Trip Routes",contentTitle:"Plan a Comfortable Return Journey",useEyebrow:"Perfect for Every Round Trip",useTitle:"Travel for Any Occasion"},
"multi-city-taxi":{whyEyebrow:"Why Choose Rani Tours for Multi City Travel?",whyTitle:"Comfort, Convenience & Complete Flexibility",contentEyebrow:"Popular Multi City Routes",contentTitle:"Explore Popular Multi City Routes",useEyebrow:"Perfect for Every Journey",useTitle:"Ideal for Every Type of Traveller"},
"airport-transfers":{whyEyebrow:"Why Choose Rani Tours for Airport Transfers?",whyTitle:"Smooth Airport Pickup & Drop",contentEyebrow:"Airport Transfer Services",contentTitle:"Reliable Transfers for Every Flight",useEyebrow:"Perfect for Every Occasion",useTitle:"Ideal for All Your Airport Transfer Needs"},
"railway-station-transfers":{whyEyebrow:"Why Choose Rani Tours for Railway Transfers?",whyTitle:"Safe, Reliable & Comfortable",contentEyebrow:"Our Railway Transfer Services",contentTitle:"Popular Pickup & Drop Services",useEyebrow:"Travel With Ease",useTitle:"Station Transfers for Every Traveller"},
"hotel-transfers":{whyEyebrow:"Why Choose Rani Tours for Hotel Transfers?",whyTitle:"Your Comfort, Our Priority",contentEyebrow:"Popular Hotels in Jodhpur",contentTitle:"Pickup & Drop to Major Hotels",useEyebrow:"Hotel Travel Made Easy",useTitle:"Door-to-Door Transfers for Every Stay"},
"corporate-travel":{whyEyebrow:"Why Choose Rani Tours for Corporate Travel?",whyTitle:"Your Business, Our Responsibility",contentEyebrow:"Corporate Travel Services",contentTitle:"Professional Transport for Every Business Need",useEyebrow:"Built for Business",useTitle:"Reliable Corporate Mobility"},
"wedding-transportation":{whyEyebrow:"Why Choose Rani Tours for Weddings?",whyTitle:"Elegant Travel for Your Special Day",contentEyebrow:"Wedding Transport Services",contentTitle:"Complete Transportation for Your Celebration",useEyebrow:"Perfect for Every Wedding Event",useTitle:"From Family Travel to Guest Movement"},
"tempo-traveller-rental":{whyEyebrow:"Why Choose a Tempo Traveller?",whyTitle:"Comfortable Group Travel Made Easy",contentEyebrow:"Tempo Traveller Options",contentTitle:"Choose the Right Space for Your Group",useEyebrow:"Popular Uses",useTitle:"Best for Every Occasion"},
"luxury-car-rental":{whyEyebrow:"Why Choose Rani Tours for Luxury Rides?",whyTitle:"Luxury Beyond Your Expectations",contentEyebrow:"Premium Travel Services",contentTitle:"Arrive in Comfort and Style",useEyebrow:"Perfect for Every Special Occasion",useTitle:"Make Every Journey Extraordinary"},
"bus-rental":{whyEyebrow:"Why Choose Rani Tours Bus Rental?",whyTitle:"Reliable Travel for Large Groups",contentEyebrow:"Bus Rental Options",contentTitle:"Group Transport for Every Requirement",useEyebrow:"Popular Uses",useTitle:"Travel Together for Every Occasion"}};
const defaultCopy={whyEyebrow:"Why Choose Rani Tours?",whyTitle:"Comfortable, Reliable Travel",contentEyebrow:"Travel Options",contentTitle:"Built Around Your Journey",useEyebrow:"Perfect for Every Journey",useTitle:"Travel for Every Occasion"};
export function TaxiServiceDetail({service,fleet}:{service:Service;fleet:Fleet[]}){const copy=sectionCopy[service.slug]||defaultCopy;const hasRoutes=Boolean(service.popularRoutes?.length);return <div className="bg-white text-[#17341f]"><Hero service={service}/><section className="bg-[#f6f8f1] py-14"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow={copy.whyEyebrow} title={copy.whyTitle}/><div className="mt-9 grid gap-3 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-6">{(service.whyChooseFeatures||[]).slice(0,6).map((feature,index)=><FeatureCard key={`${feature.title}-${index}`} feature={feature} index={index}/>)}</div></div></section><section className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow={copy.contentEyebrow} title={copy.contentTitle}/>{hasRoutes?<RouteGrid routes={service.popularRoutes||[]}/>:<ImageCardGrid cards={service.serviceCards||[]}/>}</section>{hasRoutes&&service.serviceCards?.length?<section className="bg-[#f6f8f1] py-14"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow="Our Service Options" title="Choose the Journey That Fits Your Plan"/><ImageCardGrid cards={service.serviceCards}/></div></section>:null}{fleet.length?<FleetStrip fleet={fleet}/>:null}{service.useCases?.length?<section className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow={copy.useEyebrow} title={copy.useTitle}/><ImageCardGrid cards={service.useCases}/></section>:null}<SiteCta/></div>}
function Hero({service}:{service:Service}){return <section className="relative isolate min-h-[500px] overflow-hidden bg-[#073d25] text-white"><Image src={service.heroImage.url} alt={service.heroImage.alt||service.title} fill priority sizes="100vw" className="object-cover object-center opacity-50"/><div className="absolute inset-0 bg-gradient-to-r from-[#042b1a]/96 via-[#063c25]/80 to-[#073d25]/50"/><div className="relative mx-auto grid max-w-[1180px] gap-9 px-4 py-11 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold text-white/72"><Link href="/">Home</Link><span>›</span><Link href="/taxi-services">Taxi Services</Link><span>›</span><span>{service.title}</span></div><p className="mt-7 text-[11px] font-black uppercase tracking-[.2em] text-[#e1bd58]">{service.serviceType}</p><h1 className="mt-2 max-w-2xl font-serif text-4xl font-black leading-[1.02] sm:text-5xl lg:text-[58px]">{service.title}</h1>{service.tagline?<p className="mt-3 font-serif text-xl font-bold text-[#e1bd58]">{service.tagline}</p>:null}<p className="mt-4 max-w-[650px] text-sm leading-7 text-white/83">{service.shortDescription}</p><div className="mt-8 grid max-w-3xl grid-cols-2 gap-x-4 gap-y-4 sm:grid-cols-4">{(service.heroFeatures||[]).slice(0,4).map((feature,index)=><div key={`${feature.title}-${index}`} className="flex items-center gap-2 border-r border-white/15 last:border-r-0"><HeroIcon index={index}/><p className="text-[11px] font-bold leading-4">{feature.title}</p></div>)}</div></div><TripSearch/></div></section>}
function FeatureCard({feature,index}:{feature:Feature;index:number}){const icons=[MapPin,ShieldCheck,CarFront,Clock3,Headphones,CheckCircle2];const Icon=icons[index%icons.length];return <article className="rounded-2xl border border-[#143124]/8 bg-white p-4 text-center shadow-sm"><span className="mx-auto grid size-11 place-items-center rounded-full bg-[#edf5e8] text-[#08723c]"><Icon className="size-5"/></span><h3 className="mt-3 text-sm font-black leading-5">{feature.title}</h3>{feature.description?<p className="mt-2 text-[11px] leading-5 text-[#6c786f]">{feature.description}</p>:null}</article>}
function RouteGrid({routes}:{routes:Route[]}){return <div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{routes.slice(0,5).map((route,index)=><article key={`${route.title}-${index}`} className="group overflow-hidden rounded-[18px] border border-[#143124]/10 bg-white shadow-sm"><div className="relative h-36 overflow-hidden">{route.image?.url?<Image src={route.image.url} alt={route.image.alt||route.title} fill sizes="(min-width: 1280px) 20vw, (min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition duration-500 group-hover:scale-105"/>:null}<div className="absolute inset-0 bg-gradient-to-t from-black/55 to-transparent"/></div><div className="p-4"><h3 className="font-serif text-base font-black">{route.title}</h3>{route.durationLabel?<p className="mt-1 text-[11px] text-[#718074]">{route.durationLabel}</p>:null}</div></article>)}</div>}
function ImageCardGrid({cards}:{cards:Card[]}){return <div className="mt-9 grid gap-4 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-5">{cards.slice(0,6).map((card,index)=><article key={`${card.title}-${index}`} className="group overflow-hidden rounded-[18px] border border-[#143124]/10 bg-white shadow-sm">{card.image?.url?<div className="relative h-36 overflow-hidden"><Image src={card.image.url} alt={card.image.alt||card.title} fill sizes="(min-width: 1280px) 20vw, (min-width: 768px) 33vw, (min-width: 640px) 50vw, 100vw" className="object-cover transition duration-500 group-hover:scale-105"/></div>:<div className="grid h-28 place-items-center bg-[#edf5e8] text-[#08723c]"><RouteIcon className="size-8"/></div>}<div className="p-4"><h3 className="font-serif text-base font-black">{card.title}</h3>{card.description?<p className="mt-1.5 text-[11px] leading-5 text-[#6d796f]">{card.description}</p>:null}</div></article>)}</div>}
function FleetStrip({fleet}:{fleet:Fleet[]}){return <section className="bg-[#f6f8f1] py-14"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow="Choose the Right Vehicle for Your Journey" title="Comfortable Vehicles for Every Group Size"/><div className="mt-9 grid gap-4 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-6">{fleet.slice(0,6).map(vehicle=><article key={vehicle._id} className="overflow-hidden rounded-2xl border border-[#143124]/10 bg-white shadow-sm"><div className="relative h-32 bg-white">{vehicle.image?.url?<Image src={vehicle.image.url} alt={vehicle.image.alt||vehicle.name} fill sizes="(min-width: 1280px) 17vw, (min-width: 768px) 33vw, (min-width: 640px) 50vw, 100vw" className="object-contain p-3"/>:<div className="grid h-full place-items-center"><CarFront className="size-10 text-[#0b6b3a]"/></div>}</div><div className="border-t border-[#143124]/8 p-3"><h3 className="text-xs font-black">{vehicle.name}</h3>{vehicle.modelLabel?<p className="mt-0.5 text-[10px] text-[#7a877c]">{vehicle.modelLabel}</p>:null}<div className="mt-2 flex flex-wrap gap-2 text-[9px] font-bold text-[#647167]">{vehicle.seatCount?<span className="inline-flex items-center gap-1"><UsersRound className="size-3"/>{vehicle.seatingLabel||`${vehicle.seatCount} Seats`}</span>:null}{vehicle.luggageCount?<span className="inline-flex items-center gap-1"><Luggage className="size-3"/>{vehicle.luggageLabel||`${vehicle.luggageCount} Bags`}</span>:null}{vehicle.ac?<span>AC</span>:null}</div></div></article>)}</div></div></section>}
function Heading({eyebrow,title}:{eyebrow:string;title:string}){return <div className="text-center"><p className="text-[11px] font-black uppercase tracking-[.17em] text-[#08723c]">{eyebrow}</p><h2 className="mx-auto mt-2 max-w-3xl font-serif text-3xl font-black sm:text-[34px]">{title}</h2><div className="mx-auto mt-3 h-px w-16 bg-[#d6a63a]"/></div>}
function HeroIcon({index}:{index:number}){const icons=[RouteIcon,ShieldCheck,CarFront,Headphones];const Icon=icons[index%icons.length];return <Icon className="size-6 shrink-0 text-[#e1bd58]"/>}
