import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CheckCircle2, HelpCircle, Phone, ShieldCheck, UsersRound } from "lucide-react";
import { siteContact } from "@/lib/site-data";

type Img={url:string;alt?:string};type Feature={title:string;description?:string};type Card={title:string;description?:string;image?:Img|null};type Route={title:string;durationLabel?:string;startingPrice?:number;priceUnit?:string;image?:Img|null};type FAQ={question:string;answer:string};
type Service={title:string;serviceType:string;tagline?:string;shortDescription:string;overview?:string;heroImage:Img;origin?:string;destination?:string;distanceKm?:number;estimatedDuration?:string;startingPrice?:number;priceUnit?:string;priceNote?:string;bookingForm?:{title?:string};heroFeatures?:Feature[];whyChooseFeatures?:Feature[];serviceCards?:Card[];popularRoutes?:Route[];useCases?:Card[];faq?:FAQ[]};
type Fleet={_id:string;name:string;image?:Img;seatCount?:number;outstationRatePerKm?:number;startingPrice?:number;priceUnit?:string};
const money=(n:number)=>`₹${n.toLocaleString("en-IN")}`;
export function TaxiServiceDetail({service,fleet}:{service:Service;fleet:Fleet[]}){return <div className="bg-[#fffdf7] text-[#17341f]">
<section className="relative isolate overflow-hidden bg-[#073d25] text-white"><Image src={service.heroImage.url} alt={service.heroImage.alt||service.title} fill priority className="object-cover opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-[#032819]/95 via-[#064326]/84 to-[#064326]/45"/><div className="relative mx-auto grid max-w-[1180px] gap-10 px-4 py-14 lg:grid-cols-[1.18fr_.82fr] lg:items-center lg:py-20"><div><div className="flex flex-wrap gap-2 text-[11px] font-bold text-white/70"><Link href="/">Home</Link><span>/</span><Link href="/taxi-services">Taxi Services</Link><span>/</span><span>{service.title}</span></div><p className="mt-7 text-xs font-black uppercase tracking-[.22em] text-[#d8b752]">{service.serviceType}</p><h1 className="mt-3 font-serif text-4xl font-black leading-tight sm:text-5xl lg:text-6xl">{service.title}</h1>{service.tagline&&<p className="mt-3 text-xl font-bold text-[#d8b752]">{service.tagline}</p>}<p className="mt-5 max-w-2xl text-base leading-7 text-white/82">{service.shortDescription}</p><div className="mt-7 grid max-w-3xl grid-cols-2 gap-3 sm:grid-cols-4">{service.heroFeatures?.slice(0,4).map((f,i)=><div key={`${f.title}-${i}`} className="rounded-2xl border border-white/12 bg-white/8 p-3 backdrop-blur"><CheckCircle2 className="size-5 text-[#b3df24]"/><p className="mt-2 text-xs font-black">{f.title}</p></div>)}</div></div><aside className="rounded-[28px] bg-white p-6 text-[#17341f] shadow-2xl"><p className="text-xs font-black uppercase tracking-[.16em] text-[#9b7a24]">Quick Enquiry</p><h2 className="mt-2 text-2xl font-black">{service.bookingForm?.title||"Plan Your Ride"}</h2><p className="mt-3 text-sm leading-6 text-[#667369]">Share pickup, destination, travel date, passengers and vehicle preference. Our team will confirm availability and price.</p>{service.startingPrice? <div className="mt-5 rounded-2xl bg-[#f1f5e8] p-4"><p className="text-[10px] font-black uppercase tracking-[.15em] text-[#71806f]">Starting From</p><p className="mt-1 text-2xl font-black text-[#0b6b3a]">{money(service.startingPrice)} <span className="text-sm">{service.priceUnit}</span></p><p className="mt-1 text-[11px] text-[#768178]">{service.priceNote}</p></div>:null}<Link href="/get-quote" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#076b39] px-5 py-3.5 text-sm font-black text-white">Get Quote / Enquiry <ArrowRight className="size-4"/></Link><div className="mt-3 grid grid-cols-2 gap-2"><a href={siteContact.whatsapp} className="rounded-xl bg-[#eef5df] p-3 text-center text-xs font-black text-[#0b6b3a]">WhatsApp Us</a><a href={siteContact.phones[0].href} className="flex items-center justify-center gap-2 rounded-xl border p-3 text-xs font-black"><Phone className="size-4"/>Call</a></div></aside></div></section>
<section className="mx-auto max-w-[1180px] px-4 py-14"><div className="grid gap-8 lg:grid-cols-[.78fr_1.22fr]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#0b6b3a]">About This Service</p><h2 className="mt-2 font-serif text-3xl font-black">Comfort, reliability and flexibility</h2></div><div><p className="text-[15px] leading-8 text-[#5f6c62]">{service.overview||service.shortDescription}</p><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold">{service.origin&&<span className="rounded-full bg-[#eef5df] px-3 py-2">From: {service.origin}</span>}{service.destination&&<span className="rounded-full bg-[#eef5df] px-3 py-2">To: {service.destination}</span>}{service.distanceKm? <span className="rounded-full bg-[#eef5df] px-3 py-2">{service.distanceKm} km</span>:null}{service.estimatedDuration&&<span className="rounded-full bg-[#eef5df] px-3 py-2">{service.estimatedDuration}</span>}</div></div></div></section>
{service.whyChooseFeatures?.length?<section className="bg-[#f1f5e8]"><div className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow="Why Choose Rani Tours?" title="Your Journey, Our Responsibility"/><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{service.whyChooseFeatures.map((f,i)=><div key={`${f.title}-${i}`} className="rounded-2xl border border-[#143124]/8 bg-white p-5"><span className="grid size-11 place-items-center rounded-xl bg-[#eef5df] text-[#0b6b3a]"><ShieldCheck className="size-5"/></span><h3 className="mt-4 font-black">{f.title}</h3><p className="mt-2 text-sm leading-6 text-[#69756c]">{f.description}</p></div>)}</div></div></section>:null}
{service.popularRoutes?.length?<section className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow="Popular Routes" title="Popular journeys travellers choose"/><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{service.popularRoutes.map((r,i)=><div key={`${r.title}-${i}`} className="overflow-hidden rounded-2xl border border-[#143124]/10 bg-white">{r.image?.url?<div className="relative h-44"><Image src={r.image.url} alt={r.image.alt||r.title} fill className="object-cover"/></div>:null}<div className="p-5"><h3 className="font-serif text-xl font-black">{r.title}</h3><div className="mt-3 flex justify-between gap-2 text-xs text-[#6f7b72]"><span>{r.durationLabel}</span>{r.startingPrice?<b className="text-[#0b6b3a]">From {money(r.startingPrice)} {r.priceUnit}</b>:null}</div></div></div>)}</div></section>:null}
{service.serviceCards?.length?<CardSection eyebrow="Service Options" title="Built Around Your Travel Needs" cards={service.serviceCards}/>:null}
{fleet.length?<section className="bg-white"><div className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow="Choose Your Vehicle" title="The Right Vehicle for Your Journey"/><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{fleet.map(v=><div key={v._id} className="overflow-hidden rounded-2xl border border-[#143124]/10 bg-[#fbfcfa]">{v.image?.url?<div className="relative h-40 bg-white"><Image src={v.image.url} alt={v.image.alt||v.name} fill className="object-contain p-3"/></div>:null}<div className="p-4"><h3 className="font-black">{v.name}</h3><div className="mt-2 flex items-center justify-between text-xs text-[#6f7a71]"><span className="inline-flex items-center gap-1"><UsersRound className="size-3"/>{v.seatCount||"—"} seats</span><span>{v.outstationRatePerKm?`From ₹${v.outstationRatePerKm}/km`:v.startingPrice?`From ₹${v.startingPrice}${v.priceUnit||""}`:"On request"}</span></div></div></div>)}</div></div></section>:null}
{service.useCases?.length?<CardSection eyebrow="Perfect for Every Journey" title="Travel for Every Occasion" cards={service.useCases}/>:null}
{service.faq?.length?<section className="mx-auto max-w-[900px] px-4 py-14"><Heading eyebrow="Frequently Asked Questions" title="Good to Know"/><div className="mt-8 space-y-3">{service.faq.map((f,i)=><details key={`${f.question}-${i}`} className="rounded-2xl border border-[#143124]/10 bg-white p-5"><summary className="flex cursor-pointer list-none items-center gap-3 font-black"><HelpCircle className="size-5 shrink-0 text-[#0b6b3a]"/><span>{f.question}</span></summary><p className="mt-3 pl-8 text-sm leading-6 text-[#68746b]">{f.answer}</p></details>)}</div></section>:null}
<section className="mx-auto max-w-[1180px] px-4 pb-14"><div className="rounded-[28px] bg-[#073d25] px-6 py-8 text-white md:flex md:items-center md:justify-between md:px-10"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#d8b752]">Ready to Travel?</p><h2 className="mt-2 font-serif text-2xl font-black sm:text-3xl">Plan your {service.title.toLowerCase()} today.</h2></div><div className="mt-5 flex gap-3 md:mt-0"><a href={siteContact.phones[0].href} className="inline-flex items-center gap-2 rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-sm font-black"><Phone className="size-4"/>Call</a><Link href="/get-quote" className="rounded-xl bg-[#b3df24] px-5 py-3 text-sm font-black text-[#073b25]">Get Quote</Link></div></div></section></div>}
function Heading({eyebrow,title}:{eyebrow:string;title:string}){return <div className="text-center"><p className="text-xs font-black uppercase tracking-[.18em] text-[#0b6b3a]">{eyebrow}</p><h2 className="mt-2 font-serif text-3xl font-black">{title}</h2></div>}
function CardSection({eyebrow,title,cards}:{eyebrow:string;title:string;cards:Card[]}){return <section className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow={eyebrow} title={title}/><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map((c,i)=><div key={`${c.title}-${i}`} className="overflow-hidden rounded-2xl border border-[#143124]/10 bg-white">{c.image?.url?<div className="relative h-44"><Image src={c.image.url} alt={c.image.alt||c.title} fill className="object-cover"/></div>:null}<div className="p-5"><h3 className="font-black">{c.title}</h3><p className="mt-2 text-sm leading-6 text-[#68746b]">{c.description}</p></div></div>)}</div></section>}
