import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = { title: "Terms & Conditions | Rani Tour's", description: "Terms and conditions governing enquiries, quotations and travel services provided by Rani Tour's." };

const sections = [
  { title: "Acceptance of Terms", paragraphs: ["By using this website, requesting a quotation or confirming a service with Rani Tour's, you agree to these Terms & Conditions together with any trip-specific terms communicated in your final quotation or booking confirmation."] },
  { title: "Enquiries and Quotations", paragraphs: ["Website enquiries and quote requests are requests for information only and do not create a confirmed booking. Prices and vehicle availability are subject to verification by our team before confirmation."] },
  { title: "Booking Confirmation", items: ["A booking is confirmed only after Rani Tour's explicitly confirms the requested service and any required advance payment or agreed booking condition has been completed.", "Customers should verify passenger details, pickup location, dates, times, itinerary and contact information provided for the booking.", "Changes requested after confirmation remain subject to availability and may affect the final price."] },
  { title: "Pricing and Payments", paragraphs: ["The applicable fare, inclusions, exclusions, taxes, tolls, parking, driver allowances or other trip charges will be based on the quotation or confirmation shared for the specific journey. Any additional service requested during the trip may be charged separately where applicable."] },
  { title: "Vehicle and Seating", paragraphs: ["Vehicle models shown on the website represent the types of vehicles generally offered. A specific model, colour or registration is not guaranteed unless expressly confirmed. An equivalent or suitable vehicle may be arranged depending on availability, group size and operational requirements."] },
  { title: "Pickup, Delays and Itinerary", paragraphs: ["Customers should be available at the agreed pickup point and time. Travel duration can be affected by traffic, weather, road closures, local restrictions, breakdowns, public events and other circumstances beyond reasonable control. Reasonable operational adjustments may therefore be required."] },
  { title: "Passenger Responsibilities", items: ["Passengers must comply with applicable laws and reasonable safety instructions from the driver or service team.", "Customers are responsible for their personal belongings and for providing accurate passenger and journey information.", "Illegal, dangerous, abusive or damaging conduct may result in refusal or discontinuation of service where reasonably necessary for safety or legal compliance."] },
  { title: "Cancellations and Refunds", paragraphs: ["Cancellation charges, refund eligibility and related timelines are governed by the Cancellation Policy and any specific conditions communicated for your booking. Certain third-party or special arrangements may have separate non-refundable charges."] },
  { title: "Third-Party Services", paragraphs: ["Where a journey includes hotels, attractions, guides, partner vehicles or other independently provided services, those services may also be subject to the provider's own terms, availability and policies."] },
  { title: "Liability", paragraphs: ["Rani Tour's will use reasonable care in arranging travel services. To the extent permitted by applicable law, we are not responsible for losses arising solely from circumstances outside our reasonable control, including severe weather, road closures, government action or delays caused by third parties. Nothing in these terms excludes rights or liabilities that cannot legally be excluded."] },
  { title: "Governing Law and Contact", paragraphs: ["These terms are intended to operate under applicable laws in India. Questions or concerns about a booking should first be raised with Rani Tour's through the contact details published on this website so that our team can assist promptly."] },
];

export default function TermsPage() { return <LegalPage eyebrow="Travel With Clarity" title="Terms & Conditions" intro="These terms set out the general conditions for using the Rani Tour's website, requesting quotations and arranging taxi, tour and related travel services with us." updated="26 August 2026" sections={sections} />; }
