import { NextRequest,NextResponse } from "next/server";
import { Types } from "mongoose";
import { connectToDatabase } from "@/lib/db";
import { logAdminActivity,requireAdminApi } from "@/lib/admin-auth";
import { collectAreaPublicIds,destroyCloudinaryImage } from "@/lib/cloudinary";
import { normalizeDestinationInput,validateDestination } from "@/lib/destinations";
import { Destination } from "@/models/Destination";

type Context={params:Promise<{id:string}>};
export async function GET(_:NextRequest,context:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await context.params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid destination id."},{status:400});await connectToDatabase();const item=await Destination.findById(id).lean();if(!item)return NextResponse.json({error:"Destination not found."},{status:404});return NextResponse.json({item})}
export async function PUT(request:NextRequest,context:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await context.params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid destination id."},{status:400});const input=normalizeDestinationInput(await request.json());const errors=validateDestination(input);if(errors.length)return NextResponse.json({error:errors[0],errors},{status:400});await connectToDatabase();const existing=await Destination.findById(id);if(!existing)return NextResponse.json({error:"Destination not found."},{status:404});if(await Destination.exists({slug:input.slug,_id:{$ne:id}}))return NextResponse.json({error:"A destination with this slug already exists."},{status:409});const oldIds=collectAreaPublicIds(existing.toObject(),"destinations");const item=await Destination.findByIdAndUpdate(id,{...input,publishedAt:input.status==="published"?(existing.publishedAt||new Date()):null,updatedBy:admin.id},{new:true,runValidators:true});const newIds=collectAreaPublicIds(item?.toObject(),"destinations");await Promise.all([...oldIds].filter(x=>!newIds.has(x)).map(destroyCloudinaryImage));await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Updated destination",entity:"Destination",entityId:id,metadata:{title:input.title,entityType:input.entityType,status:input.status}});return NextResponse.json({item})}
export async function DELETE(_:NextRequest,context:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await context.params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid destination id."},{status:400});await connectToDatabase();const item=await Destination.findByIdAndDelete(id);if(!item)return NextResponse.json({error:"Destination not found."},{status:404});const ids=collectAreaPublicIds(item.toObject(),"destinations");await Promise.all([...ids].map(destroyCloudinaryImage));await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Deleted destination",entity:"Destination",entityId:id,metadata:{title:item.title}});return NextResponse.json({success:true})}
