"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "motion/react";
import { AirVent, BadgeIndianRupee, BriefcaseBusiness, Car, Clock3, Headphones, MapPinned, ShieldCheck, Sparkles, UsersRound } from "lucide-react";

const heroImage = "https://images.pexels.com/photos/29566908/pexels-photo-29566908.jpeg?auto=compress&cs=tinysrgb&w=2200";
const fleet = [
{badge:"1 - 4 Seater",name:"Toyota Etios",model:"Toyota Etios / Similar",seats:"4 Seats",bags:"3 Bags",description:"Comfortable sedan for local sightseeing, airport transfers and outstation travel.",bestFor:"Best for Couples & Small Families",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota%20Etios%201.5%20XLS%20Sedan%202019.jpg"},
{badge:"1 - 4 Seater",name:"Swift Dzire",model:"Maruti Suzuki Dzire / Similar",seats:"4 Seats",bags:"3 Bags",description:"Efficient and comfortable sedan suited for city travel and long-distance taxi journeys.",bestFor:"Best for Everyday Travel",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2026%20Suzuki%20Dzire%20GL%20in%20Arctic%20White%20Pearl%2002.jpg"},
{badge:"1 - 7 Seater",name:"Innova Crysta",model:"Toyota Innova Crysta / Similar",seats:"7 Seats",bags:"5 Bags",description:"Premium family MPV with spacious seating and excellent comfort for Rajasthan and all-India journeys.",bestFor:"Best for Families",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2024%20Toyota%20Innova%202.8%20V%20in%20White%20Pearl%20Crystal%20Shine%2C%20front%20left.jpg"},
{badge:"1 - 7 Seater",name:"Toyota Fortuner",model:"Toyota Fortuner / Similar",seats:"7 Seats",bags:"5 Bags",description:"Premium SUV for travellers who prefer extra road presence, comfort and space on long journeys.",bestFor:"Best for Premium Family Travel",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2025%20Toyota%20Fortuner%202.8%20Q%204x2%20in%20Platinum%20White%20Pearl%20Mica%2C%20front%20right.jpg"},
{badge:"1 - 4 Seater",name:"Toyota Corolla",model:"Toyota Corolla / Similar",seats:"4 Seats",bags:"3 Bags",description:"Comfort-oriented executive sedan for business travel, airport transfers and premium outstation rides.",bestFor:"Best for Executive Travel",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Toyota%20Corolla%20Altis%20ZRE212%20FL%201.8%20E%20Super%20White%20II.jpg"},
...([12,14,17,21].map(n=>({badge:`${n} Seater`,name:`Force Tempo Traveller ${n}`,model:"Force Traveller / Similar",seats:`${n} Seats`,bags:`${Math.max(6,Math.round(n/2))}+ Bags`,description:"Spacious Force Traveller configuration for comfortable group tours, family functions and longer journeys.",bestFor:n<17?"Best for Medium Groups":"Best for Large Groups",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/ForceTravellerside.JPG"}))),
{badge:"24 Seater",name:"Tourist Bus 24",model:"Premium Tourist Bus / Similar",seats:"24 Seats",bags:"15+ Bags",description:"Comfortable tourist bus for corporate travel, weddings and organised tours.",bestFor:"Best for Tour Groups",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Moscow%20-%202025%20-%20White%20tour%20bus.jpg"},
{badge:"32 Seater",name:"Tourist Bus 32",model:"Premium Tourist Coach / Similar",seats:"32 Seats",bags:"20+ Bags",description:"Full-size tourist coach for large groups and long-distance group travel.",bestFor:"Best for Large Tour Groups",image:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Moscow%20-%202025%20-%20White%20tour%20bus.jpg"},
];
const highlights=[[ShieldCheck,"Well Maintained","Regularly serviced vehicles for a smooth journey"],[UsersRound,"Experienced Drivers","Polite, professional and well-trained chauffeurs"],[ShieldCheck,"Safe & Secure","Your safety is our top priority always"],[Headphones,"24/7 Assistance","We are always here to assist you on your trip"]] as const;
const reasons=[[Sparkles,"Clean & Hygienic Vehicles"],[Clock3,"On-time Pick & Drop"],[BadgeIndianRupee,"Transparent Quotations"],[BriefcaseBusiness,"No Hidden Charges"],[Car,"Customizable Solutions"],[MapPinned,"PAN India Service"]] as const;
export function FleetPageContent(){return <>
<section className="relative overflow-hidden bg-[#f7f7f4]"><Image src={heroImage} alt="White vehicle fleet ready for travel" fill priority unoptimized sizes="100vw" className="object-cover object-center opacity-70"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(255,255,255,.96)_0%,rgba(255,255,255,.74)_42%,rgba(255,255,255,.08)_100%)]"/><div className="relative mx-auto min-h-[390px] max-w-[1180px] px-4 py-10 sm:py-12"><div className="max-w-[590px]"><div className="flex items-center gap-2 text-xs text-[#4e5b4f]"><Link href="/">Home</Link><span>›</span><span>Fleet</span></div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="mt-6 font-serif text-5xl font-bold text-[#17341f] sm:text-6xl">Our Fleet</motion.h1><h2 className="mt-2 font-serif text-3xl font-bold text-[#d98200]">Comfort. Safety. Reliability.</h2><div className="mt-4 flex items-center gap-3 text-[#d69a28]"><span className="h-px w-8 bg-current"/><span>✤</span><span className="h-px w-8 bg-current"/></div><p className="mt-5 max-w-[520px] text-sm leading-7 text-[#313b31]">From sedans and premium SUVs to multiple Force Traveller configurations and tourist buses, choose the right vehicle for your group size and journey.</p></div></div></section>
<section className="bg-white py-4"><div className="mx-auto grid max-w-[1180px] gap-4 rounded-2xl bg-[#fff8ee] px-5 py-5 sm:grid-cols-2 lg:grid-cols-4">{highlights.map(([Icon,title,text])=><div key={title} className="flex gap-3 lg:border-r lg:border-[#e8ddcf] lg:pr-4 lg:last:border-r-0"><Icon className="h-9 w-9 shrink-0 text-[#0a6330]"/><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-[10px] text-[#626962]">{text}</p></div></div>)}</div></section>
<section className="bg-white py-12"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading title="Our Vehicle Options"/><p className="mx-auto mt-3 max-w-2xl text-center text-xs text-[#687068]">Vehicle model and exact seating configuration may vary by availability. Tell us your route and group size and we&apos;ll recommend the right option.</p><div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{fleet.map((v,i)=><motion.article key={v.name} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.035}} whileHover={{y:-4}} className="overflow-hidden rounded-2xl border border-[#e5e0d8] bg-white shadow-sm"><div className="relative h-52 bg-[#f5f5f3] p-3"><span className="absolute left-3 top-3 z-10 rounded-full bg-[#0c592d] px-3 py-1 text-[10px] font-bold text-white">{v.badge}</span><Image src={v.image} alt={v.model} fill unoptimized sizes="390px" className={v.name === "Innova Crysta" ? "object-contain p-2 brightness-[1.12] contrast-[0.94]" : "object-contain p-2"}/></div><div className="p-5"><h3 className="font-serif text-xl font-bold text-[#1d3021]">{v.name}</h3><p className="mt-1 text-xs text-[#687068]">{v.model}</p><div className="mt-4 flex gap-4 text-[10px]"><span className="flex gap-1"><UsersRound className="h-4 w-4 text-[#087239]"/>{v.seats}</span><span className="flex gap-1"><BriefcaseBusiness className="h-4 w-4 text-[#087239]"/>{v.bags}</span><span className="flex gap-1"><AirVent className="h-4 w-4 text-[#087239]"/>AC</span></div><p className="mt-5 min-h-[54px] text-[11px] leading-[18px] text-[#5f675f]">{v.description}</p><div className="mt-4 rounded-lg border border-[#7a9a7f] px-3 py-2 text-center text-[11px] font-bold text-[#174a29]">{v.bestFor}</div></div></motion.article>)}<article className="flex min-h-[410px] flex-col items-center justify-center rounded-2xl border border-dashed border-[#83a486] bg-[#f5f9f2] p-8 text-center"><Car className="h-10 w-10 text-[#0a6330]"/><h3 className="mt-5 font-serif text-2xl font-bold">Other Vehicles on Demand</h3><p className="mt-3 text-xs leading-6">Need another premium car, coach or specific configuration? We can arrange it subject to availability.</p></article></div></div></section>
<section className="bg-[#fff8ee] py-7"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading title="Why Travel with Rani Tours?"/><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{reasons.map(([Icon,label])=><div key={label} className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full border bg-white text-[#0b6331]"><Icon className="h-5 w-5"/></div><span className="text-[11px] font-semibold">{label}</span></div>)}</div></div></section>
</>}
function SectionHeading({title}:{title:string}){return <div className="text-center"><h2 className="font-serif text-3xl font-bold text-[#17341f]">{title}</h2><div className="mx-auto mt-3 h-px w-16 bg-[#d69a28]"/></div>}
