"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { motion } from "motion/react";
import { AirVent, BriefcaseBusiness, Car, Clock3, Headphones, MapPinned, ShieldCheck, Sparkles, UsersRound } from "lucide-react";

type Vehicle={_id:string;name:string;slug:string;modelLabel:string;category:string;seatingLabel:string;seatCount:number;luggageLabel?:string;luggageCount?:number;ac?:boolean;description:string;bestFor?:string;badge?:string;image:{url:string;alt?:string};features?:string[];suitableFor?:string[]};

const heroImage="https://images.pexels.com/photos/29566908/pexels-photo-29566908.jpeg?auto=compress&cs=tinysrgb&w=2200";
const highlights=[[ShieldCheck,"Well Maintained","Regularly serviced vehicles for a smooth journey"],[UsersRound,"Experienced Drivers","Polite, professional and well-trained chauffeurs"],[ShieldCheck,"Safe & Secure","Your safety is our top priority always"],[Headphones,"24/7 Assistance","We are always here to assist you on your trip"]] as const;
const reasons=[[Sparkles,"Clean & Hygienic Vehicles"],[Clock3,"On-time Pick & Drop"],[ShieldCheck,"Safe & Reliable Travel"],[Headphones,"24/7 Assistance"],[Car,"Flexible Vehicle Options"],[MapPinned,"Rajasthan & All India Travel"]] as const;

export function FleetPageContent({vehicles}:{vehicles:Vehicle[]}){return <>
<section className="relative isolate overflow-hidden bg-[#f7f7f4]"><Image src={heroImage} alt="Rani Tours vehicle fleet" fill priority sizes="100vw" className="object-cover object-center opacity-75"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(255,255,255,.98)_0%,rgba(255,255,255,.88)_42%,rgba(255,255,255,.12)_100%)]"/><div className="relative mx-auto flex min-h-[430px] max-w-[1180px] items-center px-4 py-12"><div className="max-w-[590px]"><div className="flex items-center gap-2 text-xs text-[#4e5b4f]"><Link href="/">Home</Link><span>›</span><span>Fleet</span></div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="mt-7 font-serif text-5xl font-black text-[#17341f] sm:text-6xl">Our Fleet</motion.h1><h2 className="mt-2 font-serif text-3xl font-bold text-[#c9881d]">Comfort. Safety. Reliability.</h2><div className="mt-4 flex items-center gap-3 text-[#d69a28]"><span className="h-px w-8 bg-current"/><span>✤</span><span className="h-px w-8 bg-current"/></div><p className="mt-5 max-w-[520px] text-sm leading-7 text-[#313b31]">A well-maintained fleet of vehicles to make your journey safe, comfortable and memorable. Choose the right vehicle for your group size and travel needs.</p></div></div></section>

<section className="bg-white py-5"><div className="mx-auto grid max-w-[1180px] gap-4 rounded-2xl bg-[#fff8ee] px-5 py-5 sm:grid-cols-2 lg:grid-cols-4">{highlights.map(([Icon,title,text])=><div key={title} className="flex gap-3 lg:border-r lg:border-[#e8ddcf] lg:pr-4 lg:last:border-r-0"><Icon className="h-9 w-9 shrink-0 text-[#0a6330]"/><div><h3 className="text-sm font-bold">{title}</h3><p className="mt-1 text-[10px] leading-4 text-[#626962]">{text}</p></div></div>)}</div></section>

<section className="bg-white py-14"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading eyebrow="Our Fleet" title="Our Vehicle Options"/><p className="mx-auto mt-3 max-w-2xl text-center text-xs leading-5 text-[#687068]">From comfortable sedans and family MPVs to Force Tempo Travellers and Tata tourist buses, choose the right vehicle for your journey. Other vehicle types can also be arranged on demand.</p>{vehicles.length?<div className="mt-9 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{vehicles.map((v,i)=><motion.article id={v.slug} key={v._id||v.slug} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:Math.min(i*.035,.2)}} whileHover={{y:-4}} className="overflow-hidden rounded-2xl border border-[#e5e0d8] bg-white shadow-sm"><div className="relative h-48 overflow-hidden bg-[#f5f5f3]"><span className="absolute left-3 top-3 z-10 rounded-full bg-[#0c592d] px-3 py-1 text-[10px] font-bold text-white">{v.badge||v.seatingLabel}</span><VehiclePhoto vehicle={v}/></div><div className="p-5"><h3 className="font-serif text-xl font-bold text-[#1d3021]">{v.name}</h3><p className="mt-1 text-xs text-[#687068]">{v.modelLabel}</p><div className="mt-4 flex flex-wrap gap-4 text-[10px]"><span className="flex items-center gap-1"><UsersRound className="h-4 w-4 text-[#087239]"/>{v.slug==="on-demand-vehicle"?"As required":`${v.seatCount} Seats`}</span><span className="flex items-center gap-1"><BriefcaseBusiness className="h-4 w-4 text-[#087239]"/>{v.luggageLabel||`${v.luggageCount||0} Bags`}</span>{v.ac?<span className="flex items-center gap-1"><AirVent className="h-4 w-4 text-[#087239]"/>AC</span>:null}</div><p className="mt-5 min-h-[72px] text-[11px] leading-[18px] text-[#5f675f]">{v.description}</p>{v.bestFor?<div className="mt-4 rounded-lg border border-[#7a9a7f] px-3 py-2 text-center text-[11px] font-bold text-[#174a29]">{v.bestFor}</div>:null}</div></motion.article>)}</div>:<div className="mt-9 rounded-2xl border border-dashed border-[#7e9b82] bg-[#f7faf5] p-10 text-center"><Car className="mx-auto size-9 text-[#0a6330]"/><h3 className="mt-4 font-serif text-xl font-bold">Vehicle options are being updated</h3><p className="mt-2 text-xs text-[#687068]">Contact our team and we&apos;ll recommend a suitable vehicle for your journey.</p></div>}</div></section>

<section className="bg-[#fff8ee] py-12"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading eyebrow="Travel With Confidence" title="Why Travel with Rani Tour's?"/><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{reasons.map(([Icon,label])=><div key={label} className="text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-[#dce6da] bg-white text-[#0b6331]"><Icon className="h-5 w-5"/></div><span className="mt-3 block text-[11px] font-semibold leading-4">{label}</span></div>)}</div></div></section>

<section className="bg-[#073d25] py-8 text-white"><div className="mx-auto flex max-w-[1180px] flex-col gap-5 px-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#dcbf62]">Need the right vehicle?</p><h2 className="mt-2 font-serif text-2xl font-black">Tell us your group size and travel plan.</h2><p className="mt-2 text-xs text-white/70">Our team will recommend a comfortable vehicle for your route.</p></div><Link href="/get-quote" className="inline-flex w-fit items-center justify-center rounded-xl bg-[#b3df24] px-6 py-3 text-xs font-black text-[#073b25]">Get a Quote</Link></div></section>
</>}

function VehiclePhoto({vehicle}:{vehicle:Vehicle}){const[fallback,setFallback]=useState(false);const src=fallback?"/images/fleet/vehicle-fallback.svg":vehicle.image.url;return <Image src={src} alt={vehicle.image.alt||vehicle.modelLabel||vehicle.name} fill sizes="(max-width:768px) 100vw, (max-width:1280px) 50vw, 25vw" className="object-contain p-2" onError={()=>setFallback(true)}/>}
function SectionHeading({eyebrow,title}:{eyebrow:string;title:string}){return <div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#08713b]">{eyebrow}</p><h2 className="mt-2 font-serif text-3xl font-black text-[#17341f] sm:text-4xl">{title}</h2><div className="mx-auto mt-3 h-px w-16 bg-[#d69a28]"/></div>}
