export type CmsImage={url:string;publicId?:string;alt?:string};
export function slugifyDestination(v:string){return v.toLowerCase().trim().replace(/['’]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120)}
const text=(v:unknown,max=5000)=>typeof v==="string"?v.trim().slice(0,max):"";
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const bool=(v:unknown,f=false)=>typeof v==="boolean"?v:f;
const image=(v:unknown):CmsImage|null=>{if(!v||typeof v!=="object")return null;const r=v as Record<string,unknown>;const url=text(r.url,1500);if(!/^https?:\/\//i.test(url))return null;return{url,publicId:text(r.publicId,500),alt:text(r.alt,250)}};
const list=(v:unknown,max=80)=>Array.isArray(v)?v.map(x=>text(x,500)).filter(Boolean).slice(0,max):[];
const ids=(v:unknown,max=40)=>Array.isArray(v)?v.map(x=>text(x,50)).filter(x=>/^[a-f\d]{24}$/i.test(x)).slice(0,max):[];
const cards=(v:unknown)=>Array.isArray(v)?v.slice(0,40).map(x=>{const r=x&&typeof x==="object"?x as Record<string,unknown>:{};return{title:text(r.title,180),description:text(r.description,2000),image:image(r.image),meta:text(r.meta,180)}}).filter(x=>x.title):[];
const faqs=(v:unknown)=>Array.isArray(v)?v.slice(0,30).map(x=>{const r=x&&typeof x==="object"?x as Record<string,unknown>:{};return{question:text(r.question,300),answer:text(r.answer,3000)}}).filter(x=>x.question&&x.answer):[];
export function normalizeDestinationInput(raw:unknown){const i=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};const title=text(i.title,180);const seo=i.seo&&typeof i.seo==="object"?i.seo as Record<string,unknown>:{};return{
 title,slug:slugifyDestination(text(i.slug,180)||title),entityType:i.entityType==="category"?"category" as const:"destination" as const,categoryType:i.categoryType==="region"?"region" as const:i.categoryType==="theme"?"theme" as const:"city" as const,parentCategoryIds:ids(i.parentCategoryIds),tagline:text(i.tagline,300),shortDescription:text(i.shortDescription,700),overview:text(i.overview,8000),heroImage:image(i.heroImage),gallery:Array.isArray(i.gallery)?i.gallery.map(image).filter((x):x is CmsImage=>Boolean(x)).slice(0,30):[],country:text(i.country,100)||"India",state:text(i.state,120),region:text(i.region,120),bestTimeToVisit:text(i.bestTimeToVisit,180),idealDuration:text(i.idealDuration,120),knownFor:list(i.knownFor,40),latitude:num(i.latitude),longitude:num(i.longitude),attractions:cards(i.attractions),experiences:cards(i.experiences),travelTips:list(i.travelTips,60),featuredDestinationIds:ids(i.featuredDestinationIds),nearbyDestinationIds:ids(i.nearbyDestinationIds),relatedPackageIds:ids(i.relatedPackageIds),relatedTaxiServiceIds:ids(i.relatedTaxiServiceIds),ctaTitle:text(i.ctaTitle,180)||"Plan Your Trip",ctaDescription:text(i.ctaDescription,700),faq:faqs(i.faq),featured:bool(i.featured),status:i.status==="published"?"published" as const:"draft" as const,sortOrder:Math.round(Number(i.sortOrder)||0),seo:{metaTitle:text(seo.metaTitle,180),metaDescription:text(seo.metaDescription,320),keywords:list(seo.keywords,40),canonicalUrl:text(seo.canonicalUrl,1000),ogImage:image(seo.ogImage)}}}
export function validateDestination(i:ReturnType<typeof normalizeDestinationInput>){const e:string[]=[];if(i.title.length<2)e.push("Title is required.");if(!i.slug)e.push("A valid slug is required.");if(i.shortDescription.length<20)e.push("Short description must contain at least 20 characters.");if(!i.heroImage)e.push("Hero image is required.");return e}
