export type CmsImage={url:string;publicId?:string;alt?:string};
const text=(v:unknown,max=5000)=>typeof v==="string"?v.trim().slice(0,max):"";
const num=(v:unknown,f=0)=>{const n=Number(v);return Number.isFinite(n)?n:f};
const bool=(v:unknown,f=false)=>typeof v==="boolean"?v:f;
const list=(v:unknown,max=80)=>Array.isArray(v)?v.map(x=>text(x,300)).filter(Boolean).slice(0,max):[];
const image=(v:unknown):CmsImage|null=>{if(!v||typeof v!=="object")return null;const r=v as Record<string,unknown>;const url=text(r.url,1500);if(!/^https?:\/\//i.test(url))return null;return{url,publicId:text(r.publicId,500),alt:text(r.alt,250)}};
export const slugifyFleet=(v:string)=>v.toLowerCase().trim().replace(/['’]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);
export function normalizeFleetInput(raw:unknown){const i=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};const title=text(i.name,180);const seo=i.seo&&typeof i.seo==="object"?i.seo as Record<string,unknown>:{};const categories=new Set(["sedan","suv","mpv","tempo_traveller","bus","luxury","other"]);const category=categories.has(String(i.category))?String(i.category):"sedan";return{name:title,slug:slugifyFleet(text(i.slug,180)||title),modelLabel:text(i.modelLabel,180),category,seatingLabel:text(i.seatingLabel,100),seatCount:Math.max(1,Math.round(num(i.seatCount,1))),luggageLabel:text(i.luggageLabel,100),luggageCount:Math.max(0,Math.round(num(i.luggageCount,0))),ac:bool(i.ac,true),description:text(i.description,2500),bestFor:text(i.bestFor,250),badge:text(i.badge,100),image:image(i.image),gallery:Array.isArray(i.gallery)?i.gallery.map(image).filter((x):x is CmsImage=>Boolean(x)).slice(0,20):[],startingPrice:Math.max(0,num(i.startingPrice,0)),priceUnit:text(i.priceUnit,80),localRatePerKm:Math.max(0,num(i.localRatePerKm,0)),outstationRatePerKm:Math.max(0,num(i.outstationRatePerKm,0)),minimumKmPerDay:Math.max(0,num(i.minimumKmPerDay,0)),driverAllowancePerDay:Math.max(0,num(i.driverAllowancePerDay,0)),tollParkingIncluded:bool(i.tollParkingIncluded),features:list(i.features,50),suitableFor:list(i.suitableFor,50),featured:bool(i.featured),status:i.status==="published"?"published" as const:"draft" as const,sortOrder:Math.round(num(i.sortOrder,0)),seo:{metaTitle:text(seo.metaTitle,180),metaDescription:text(seo.metaDescription,320),keywords:list(seo.keywords,40),canonicalUrl:text(seo.canonicalUrl,1000),ogImage:image(seo.ogImage)}}}
export function validateFleetInput(i:ReturnType<typeof normalizeFleetInput>){const e:string[]=[];if(i.name.length<2)e.push("Vehicle name is required.");if(!i.slug)e.push("A valid slug is required.");if(!i.modelLabel)e.push("Model label is required.");if(!i.seatingLabel)e.push("Seating label is required.");if(i.description.length<15)e.push("Description must contain at least 15 characters.");if(!i.image)e.push("Vehicle image is required.");return e}
