import { Sequence } from "@/models/Sequence";

export type InvoiceInput={lineItems?:Array<{description?:unknown;quantity?:unknown;rate?:unknown}>;discountType?:unknown;discountValue?:unknown;taxRate?:unknown;amountPaid?:unknown};
const money=(value:unknown)=>Math.max(0,Math.round((Number(value)||0)*100)/100);
export function calculateInvoice(input:InvoiceInput){
  const lineItems=(Array.isArray(input.lineItems)?input.lineItems:[]).map(item=>{const quantity=Math.max(0,Number(item.quantity)||0);const rate=money(item.rate);return{description:String(item.description??"").trim().slice(0,300),quantity,rate,amount:money(quantity*rate)}}).filter(item=>item.description&&item.quantity>0);
  const subtotal=money(lineItems.reduce((sum,item)=>sum+item.amount,0));const discountType=["fixed","percent"].includes(String(input.discountType))?String(input.discountType):"none";const discountValue=money(input.discountValue);const discountAmount=discountType==="fixed"?Math.min(subtotal,discountValue):discountType==="percent"?money(subtotal*Math.min(discountValue,100)/100):0;const taxable=Math.max(0,subtotal-discountAmount);const taxRate=Math.min(100,money(input.taxRate));const taxAmount=money(taxable*taxRate/100);const total=money(taxable+taxAmount);const amountPaid=Math.min(total,money(input.amountPaid));const balanceDue=money(total-amountPaid);const paymentStatus=balanceDue<=0?"paid":amountPaid>0?"partial":"unpaid";return{lineItems,subtotal,discountType,discountValue,discountAmount,taxRate,taxAmount,total,amountPaid,balanceDue,paymentStatus};
}
export async function nextInvoiceNumber(){const year=new Date().getFullYear();const key=`invoice-${year}`;const seq=await Sequence.findOneAndUpdate({key},{$inc:{value:1}},{new:true,upsert:true,setDefaultsOnInsert:true});return `RT-${year}-${String(seq.value).padStart(4,"0")}`;}
