"use client";

import { useEffect } from "react";
import { usePathname } from "next/navigation";

function labelControl(form:HTMLFormElement,labelStart:string){const labels=[...form.querySelectorAll("label")];return labels.find(label=>label.textContent?.trim().startsWith(labelStart));}
function inputValue(form:HTMLFormElement,placeholder:string){return (form.querySelector(`[placeholder="${CSS.escape(placeholder)}"]`) as HTMLInputElement|HTMLTextAreaElement|null)?.value?.trim()||"";}
function fieldText(form:HTMLFormElement,labelStart:string){const label=labelControl(form,labelStart);if(!label)return "";const input=label.querySelector("input,textarea") as HTMLInputElement|HTMLTextAreaElement|null;if(input)return input.value.trim();const button=label.querySelector("button");return button?.textContent?.replace(/\s+/g," ").trim()||"";}
function travellerCount(form:HTMLFormElement){const label=labelControl(form,"Travellers");if(!label)return 1;const text=label.textContent||"";const match=text.match(/\b(\d{1,3})\b/);return match?Number(match[1]):1;}
function getDate(form:HTMLFormElement){const label=labelControl(form,"Travel Date");if(!label)return "";const button=label.querySelector("button");const text=button?.textContent?.replace(/\s+/g," ").trim()||"";if(!text||/select travel date/i.test(text))return "";const parsed=new Date(text);if(Number.isNaN(parsed.getTime()))return "";const y=parsed.getFullYear(),m=String(parsed.getMonth()+1).padStart(2,"0"),d=String(parsed.getDate()).padStart(2,"0");return `${y}-${m}-${d}`;}
function showContactMessage(form:HTMLFormElement,message:string,ok:boolean){form.querySelector("[data-enquiry-feedback]")?.remove();const el=document.createElement("div");el.dataset.enquiryFeedback="true";el.className=`sm:col-span-2 rounded-xl border px-4 py-3 text-sm ${ok?"border-[#9fc099] bg-[#f1f8ee] text-[#0b6531]":"border-red-200 bg-red-50 text-red-700"}`;el.textContent=message;form.prepend(el);}

export function PublicEnquiryBridge(){const pathname=usePathname();useEffect(()=>{if(pathname!=="/get-quote"&&pathname!=="/contact")return;const handler=async(event:SubmitEvent)=>{const form=event.target as HTMLFormElement;if(!(form instanceof HTMLFormElement))return;if(pathname==="/get-quote"&&form.dataset.enquirySynced==="1"){delete form.dataset.enquirySynced;return;}event.preventDefault();event.stopImmediatePropagation();try{let payload:Record<string,unknown>;if(pathname==="/contact"){const fd=new FormData(form);payload={source:"contact",name:String(fd.get("name")||""),phone:String(fd.get("phone")||"").replace(/\D/g,""),email:String(fd.get("email")||""),subject:String(fd.get("subject")||""),message:String(fd.get("message")||"")};}else{const consent=form.querySelector('[role="checkbox"]')?.getAttribute("aria-checked")==="true";payload={source:"get_quote",name:inputValue(form,"Enter your full name"),phone:inputValue(form,"10-digit mobile number").replace(/\D/g,""),email:inputValue(form,"Enter your email"),journeyType:fieldText(form,"Journey Type"),pickup:inputValue(form,"Enter pickup location"),destination:inputValue(form,"Enter destination"),travelDate:getDate(form),travellers:travellerCount(form),duration:inputValue(form,"e.g. 3 Days"),vehicle:fieldText(form,"Preferred Vehicle"),message:inputValue(form,"Tell us about stops, luggage, hotel pickup, special requirements, itinerary preferences, or anything else..."),consent};if(!consent){form.requestSubmit();return;}}
 const response=await fetch("/api/enquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to submit your enquiry right now.");if(pathname==="/get-quote"){form.dataset.enquirySynced="1";form.requestSubmit();}else{form.reset();showContactMessage(form,"Thank you. Your message has been received and our team will contact you shortly.",true);}}
 catch(error){const message=error instanceof Error?error.message:"Unable to submit your enquiry right now.";if(pathname==="/contact")showContactMessage(form,message,false);else alert(message);}};document.addEventListener("submit",handler,true);return()=>document.removeEventListener("submit",handler,true);},[pathname]);return null;}
