"use client";

import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import { CalendarDays, Camera, Car, Grid3X3, Headphones, IndianRupee, Mountain, ShieldCheck, UsersRound } from "lucide-react";
import { SiteCta } from "@/components/layout/site-cta";

type Category="All Photos"|"Destinations"|"Vehicles"|"Happy Travelers"|"Travel Moments"|"Events";
export type PublicGalleryItem={id:string;title:string;src:string;alt:string;category:Exclude<Category,"All Photos">;caption:string;location:string;featured:boolean};

const categories:{label:Category;icon:typeof Grid3X3}[]=[{label:"All Photos",icon:Grid3X3},{label:"Destinations",icon:Mountain},{label:"Vehicles",icon:Car},{label:"Happy Travelers",icon:UsersRound},{label:"Travel Moments",icon:Camera},{label:"Events",icon:CalendarDays}];
const fallbackHero="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=88&w=2200";
const trustItems=[[ShieldCheck,"Trusted & Reliable","Thousands of happy customers trust us for their journeys."],[IndianRupee,"Transparent Quotations","Clear quotations with no hidden surprises."],[Car,"Comfort & Safety","Well-maintained vehicles for a safe journey."],[Headphones,"24/7 Travel Support","Our team is always here to assist you anytime."]] as const;

export function GalleryPageContent({items}:{items:PublicGalleryItem[]}){
  const[activeCategory,setActiveCategory]=useState<Category>("All Photos");
  const filteredItems=useMemo(()=>activeCategory==="All Photos"?items:items.filter(item=>item.category===activeCategory),[activeCategory,items]);
  const heroItem=items.find(item=>item.featured&&item.category==="Destinations")||items.find(item=>item.category==="Destinations")||items[0];
  const heroImage=heroItem?.src||fallbackHero;
  const heroAlt=heroItem?.alt||"Scenic travel destination in India";

  return <>
<section className="relative overflow-hidden bg-[#f6f5f0]"><Image src={heroImage} alt={heroAlt} fill priority unoptimized={heroImage.includes("wikimedia.org")||heroImage.includes("upload.wikimedia.org")} sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(255,255,255,.98)_0%,rgba(255,255,255,.9)_34%,rgba(255,255,255,.28)_68%,rgba(255,255,255,.08)_100%)]"/><div className="relative mx-auto flex min-h-[370px] max-w-[1180px] items-center px-4 py-12"><div className="max-w-[570px]"><div className="flex items-center gap-2 text-xs text-[#536054]"><Link href="/" className="transition hover:text-[#0b6531]">Home</Link><span>›</span><span>Gallery</span></div><h1 className="hero-reveal mt-6 font-serif text-5xl font-bold text-[#17341f] sm:text-6xl">Our Gallery</h1><h2 className="hero-reveal mt-2 font-serif text-3xl font-bold text-[#c67b22] [animation-delay:80ms]">Moments. Places. Memories.</h2><div className="mt-4 flex items-center gap-3 text-[#d6a63a]"><span className="h-px w-8 bg-current"/><span>✤</span><span className="h-px w-8 bg-current"/></div><p className="mt-5 max-w-[500px] text-sm leading-7 text-[#313b31]">A glimpse of beautiful destinations, our vehicle fleet and memorable road journeys with Rani Tour&apos;s across Rajasthan and India.</p></div></div></section>
<section className="border-y border-[#eee7dc] bg-[#fff8ed] py-4"><div className="mx-auto flex max-w-[1180px] gap-3 overflow-x-auto px-4 pb-1 sm:justify-center">{categories.map(({label,icon:Icon})=>{const active=activeCategory===label;const count=label==="All Photos"?items.length:items.filter(item=>item.category===label).length;return <button key={label} type="button" onClick={()=>setActiveCategory(label)} className={`flex shrink-0 items-center gap-2 rounded-full border px-5 py-2.5 text-xs font-semibold transition ${active?"border-[#0b6531] bg-[#0b6531] text-white shadow-sm":"border-[#ddd7cd] bg-white text-[#26352a] hover:border-[#7da082] hover:text-[#0b6531]"}`} aria-pressed={active}><Icon className="h-4 w-4"/>{label}<span className={`rounded-full px-1.5 py-0.5 text-[9px] ${active?"bg-white/15":"bg-[#edf5e8] text-[#0b6531]"}`}>{count}</span></button>})}</div></section>
<section className="defer-render bg-white py-8 sm:py-10"><div className="mx-auto max-w-[1180px] px-4">{filteredItems.length?<div key={activeCategory} className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">{filteredItems.map((item,index)=><figure key={item.id} className={`gallery-reveal group relative overflow-hidden rounded-2xl bg-[#f4f3ef] ${index%5===0?"sm:row-span-2 sm:min-h-[430px]":"min-h-[210px]"}`} style={{animationDelay:`${Math.min(index*20,120)}ms`}}><Image src={item.src} alt={item.alt} fill unoptimized={item.src.includes("wikimedia.org")||item.src.includes("upload.wikimedia.org")} sizes="(max-width:640px) 100vw,(max-width:1024px) 50vw,25vw" className="object-cover transition duration-500 group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/5 to-transparent opacity-60 transition group-hover:opacity-80"/><figcaption className="absolute inset-x-0 bottom-0 p-4 text-white"><span className="inline-flex rounded-full bg-white/15 px-2.5 py-1 text-[9px] font-bold uppercase tracking-[.12em] backdrop-blur">{item.category}</span><h3 className="mt-2 font-serif text-lg font-bold leading-tight">{item.title}</h3>{item.location?<p className="mt-1 text-[10px] text-white/80">{item.location}</p>:null}{item.caption?<p className="mt-2 line-clamp-2 text-[10px] leading-4 text-white/75 opacity-0 transition group-hover:opacity-100">{item.caption}</p>:null}</figcaption></figure>)}</div>:<div className="rounded-2xl border border-dashed border-[#a8b9a5] bg-[#f7faf5] px-6 py-16 text-center"><Camera className="mx-auto h-9 w-9 text-[#0b6531]"/><h2 className="mt-4 font-serif text-2xl font-bold text-[#17341f]">Gallery is being updated</h2><p className="mt-2 text-sm text-[#687068]">Published photos from the Gallery CMS will appear here.</p></div>}</div></section>
<section className="defer-render bg-white pb-10 pt-3"><div className="mx-auto max-w-[1180px] px-4"><div className="text-center"><p className="text-[11px] font-bold uppercase tracking-[.18em] text-[#315d3b]">Why Travel with Rani Tour&apos;s?</p><div className="mx-auto mt-3 flex items-center justify-center gap-3 text-[#d6a63a]"><span className="h-px w-9 bg-current"/><span>✤</span><span className="h-px w-9 bg-current"/></div></div><div className="mt-7 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{trustItems.map(([Icon,title,text],index)=><div key={title} className={`flex gap-4 ${index<trustItems.length-1?"lg:border-r lg:border-[#e6e0d7] lg:pr-5":""}`}><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full border border-[#97ae9b] text-[#0b6531]"><Icon className="h-5 w-5"/></div><div><h3 className="text-sm font-bold text-[#1d3021]">{title}</h3><p className="mt-1 text-[11px] leading-5 text-[#687068]">{text}</p></div></div>)}</div></div></section><SiteCta/></>}
