"use client";

import { FormEvent, useMemo, useState } from "react";
import { CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, MapPin, Minus, Plus, Send, UsersRound, X } from "lucide-react";

const journeyOptions=["Local / Sightseeing","One Way","Round Trip","Multi-City","Airport / Railway Transfer","Corporate Travel","Tour Package","Wedding / Event","Other"];
const vehicleOptions=["Let Rani Tour's recommend","Toyota Etios / Sedan","Maruti Suzuki Dzire","Honda Amaze","Toyota Corolla","Innova Crysta","Toyota Fortuner","Force Traveller - 12 Seater","Force Traveller - 14 Seater","Force Traveller - 17 Seater","Force Traveller - 21 Seater","Tourist Bus - 24 Seater","Tourist Bus - 32 Seater","Other / On Demand"];
const fieldClass="rani-control mt-2 h-12 px-4 text-sm placeholder:text-[#949b94]";
type FormState={name:string;phone:string;email:string;journeyType:string;pickup:string;destination:string;date:string;travellers:number;duration:string;vehicle:string;message:string;consent:boolean};
const initialForm:FormState={name:"",phone:"",email:"",journeyType:"",pickup:"",destination:"",date:"",travellers:1,duration:"",vehicle:"Let Rani Tour's recommend",message:"",consent:false};
const pad=(v:number)=>String(v).padStart(2,"0");
const formatDate=(y:number,m:number,d:number)=>`${y}-${pad(m+1)}-${pad(d)}`;
function displayDate(value:string){if(!value)return"Select travel date";const[y,m,d]=value.split("-").map(Number);return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(y,m-1,d));}

export function GetQuoteForm(){
 const[submitted,setSubmitted]=useState(false);const[sending,setSending]=useState(false);const[serverError,setServerError]=useState("");const[form,setForm]=useState<FormState>(initialForm);const[errors,setErrors]=useState<Record<string,string>>({});const[openControl,setOpenControl]=useState<"journey"|"vehicle"|"date"|null>(null);const today=useMemo(()=>new Date(),[]);const[calendarMonth,setCalendarMonth]=useState(()=>new Date(today.getFullYear(),today.getMonth(),1));
 const setValue=<K extends keyof FormState>(key:K,value:FormState[K])=>{setForm(c=>({...c,[key]:value}));setErrors(c=>{const n={...c};delete n[key];return n});setServerError("")};
 const validate=()=>{const n:Record<string,string>={};if(form.name.trim().length<2)n.name="Please enter your full name.";if(!/^[6-9]\d{9}$/.test(form.phone))n.phone="Enter a valid 10-digit Indian mobile number.";if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))n.email="Enter a valid email address.";if(!form.journeyType)n.journeyType="Please choose a journey type.";if(form.pickup.trim().length<2)n.pickup="Please enter the pickup location.";if(form.destination.trim().length<2)n.destination="Please enter the destination.";if(!form.date)n.date="Please choose a travel date.";if(!form.consent)n.consent="Please allow us to contact you about this request.";setErrors(n);return Object.keys(n).length===0};
 async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!validate()||sending)return;setSending(true);setServerError("");try{const response=await fetch("/api/enquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:"get_quote",name:form.name,phone:form.phone,email:form.email,journeyType:form.journeyType,pickup:form.pickup,destination:form.destination,travelDate:form.date,travellers:form.travellers,duration:form.duration,vehicle:form.vehicle,message:form.message})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Unable to submit your quote request.");setSubmitted(true);setOpenControl(null)}catch(error){setServerError(error instanceof Error?error.message:"Unable to submit your quote request. Please try again.")}finally{setSending(false)}}
 if(submitted)return <div className="mt-9 rounded-2xl border border-[#9fc099] bg-[#f1f8ee] p-7 text-center"><CheckCircle2 className="mx-auto h-11 w-11 text-[#0b6531]"/><h3 className="mt-4 font-serif text-2xl font-bold text-[#17341f]">Quote Request Sent</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#5c685f]">Thank you. Your enquiry has been received and our team will contact you using the details you provided.</p><button type="button" onClick={()=>{setSubmitted(false);setForm(initialForm);setErrors({});setServerError("")}} className="mt-5 rounded-xl border border-[#0b6531] px-5 py-2.5 text-xs font-bold text-[#0b6531] transition hover:bg-[#0b6531] hover:text-white">Submit Another Request</button></div>;
 return <form onSubmit={handleSubmit} noValidate className="mt-8 grid gap-5">
 <div className="grid gap-5 sm:grid-cols-2"><Field label="Full Name *" error={errors.name}><input value={form.name} onChange={e=>setValue("name",e.target.value)} placeholder="Enter your full name" className={fieldClass}/></Field><Field label="Mobile Number *" error={errors.phone}><input value={form.phone} onChange={e=>setValue("phone",e.target.value.replace(/\D/g,"").slice(0,10))} inputMode="numeric" placeholder="10-digit mobile number" className={fieldClass}/></Field></div>
 <div className="grid gap-5 sm:grid-cols-2"><Field label="Email Address" error={errors.email}><input value={form.email} onChange={e=>setValue("email",e.target.value)} inputMode="email" placeholder="Enter your email" className={fieldClass}/></Field><Field label="Journey Type *" error={errors.journeyType}><CustomSelect value={form.journeyType} placeholder="Select journey type" options={journeyOptions} open={openControl==="journey"} onToggle={()=>setOpenControl(openControl==="journey"?null:"journey")} onSelect={v=>{setValue("journeyType",v);setOpenControl(null)}}/></Field></div>
 <div className="grid gap-5 sm:grid-cols-2"><Field label="Pickup Location *" error={errors.pickup}><span className="relative block"><MapPin className="pointer-events-none absolute left-4 top-[26px] h-4 w-4 text-[#718074]"/><input value={form.pickup} onChange={e=>setValue("pickup",e.target.value)} placeholder="Enter pickup location" className={`${fieldClass} pl-11`}/></span></Field><Field label="Destination *" error={errors.destination}><span className="relative block"><MapPin className="pointer-events-none absolute left-4 top-[26px] h-4 w-4 text-[#718074]"/><input value={form.destination} onChange={e=>setValue("destination",e.target.value)} placeholder="Enter destination" className={`${fieldClass} pl-11`}/></span></Field></div>
 <div className="grid gap-5 sm:grid-cols-3"><Field label="Travel Date *" error={errors.date}><CustomDatePicker value={form.date} open={openControl==="date"} month={calendarMonth} today={today} onToggle={()=>setOpenControl(openControl==="date"?null:"date")} onMonthChange={setCalendarMonth} onSelect={v=>{setValue("date",v);setOpenControl(null)}}/></Field><Field label="Travellers *"><TravellerStepper value={form.travellers} onChange={v=>setValue("travellers",v)}/></Field><Field label="Trip Duration"><input value={form.duration} onChange={e=>setValue("duration",e.target.value)} placeholder="e.g. 3 Days" className={fieldClass}/></Field></div>
 <Field label="Preferred Vehicle"><CustomSelect value={form.vehicle} placeholder="Let Rani Tour's recommend" options={vehicleOptions} open={openControl==="vehicle"} onToggle={()=>setOpenControl(openControl==="vehicle"?null:"vehicle")} onSelect={v=>{setValue("vehicle",v);setOpenControl(null)}}/></Field>
 <Field label="Additional Requirements"><textarea value={form.message} onChange={e=>setValue("message",e.target.value)} rows={5} placeholder="Stops, luggage, hotel pickup, itinerary preferences or anything else..." className="rani-control mt-2 w-full resize-none px-4 py-3 text-sm leading-6 placeholder:text-[#949b94]"/></Field>
 <div><button type="button" role="checkbox" aria-checked={form.consent} onClick={()=>setValue("consent",!form.consent)} className="flex items-start gap-3 text-left text-[11px] leading-5 text-[#667067]"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-md border transition ${form.consent?"border-[#0b6531] bg-[#0b6531] text-white":"border-[#bac4b9] bg-white text-transparent"}`}><Check className="h-3.5 w-3.5"/></span><span>I agree to be contacted by Rani Tour&apos;s regarding this quote request.</span></button>{errors.consent?<p className="mt-1 text-[11px] font-medium text-[#b42318]">{errors.consent}</p>:null}</div>
 {(Object.keys(errors).length||serverError)?<div className="flex items-start gap-3 rounded-xl border border-[#f1c3bd] bg-[#fff4f2] px-4 py-3 text-xs text-[#912018]"><X className="mt-0.5 h-4 w-4 shrink-0"/><span>{serverError||"Please review the highlighted fields before submitting your request."}</span></div>:null}
 <button disabled={sending} type="submit" className="flex items-center justify-center gap-2 rounded-xl bg-[#147435] px-6 py-4 text-sm font-bold text-white shadow-md transition hover:-translate-y-0.5 hover:bg-[#0b6531] hover:shadow-lg disabled:cursor-wait disabled:opacity-60"><Send className="h-4 w-4"/>{sending?"Sending Request...":"Request My Free Quote"}<span>→</span></button><p className="text-center text-[11px] text-[#7c857e]">No booking is confirmed until our team verifies availability and shares the final quotation.</p>
 </form>;
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-xs font-semibold text-[#37443a]">{label}{children}{error?<span className="mt-1 block text-[11px] font-medium text-[#b42318]">{error}</span>:null}</label>}
function CustomSelect({value,placeholder,options,open,onToggle,onSelect}:{value:string;placeholder:string;options:readonly string[];open:boolean;onToggle:()=>void;onSelect:(v:string)=>void}){return <div className="relative mt-2"><button type="button" onClick={onToggle} className="rani-control flex h-12 items-center justify-between px-4 text-left text-sm"><span className={value?"":"text-[#949b94]"}>{value||placeholder}</span><ChevronDown className={`h-4 w-4 text-[#0b6531] transition ${open?"rotate-180":""}`}/></button>{open?<div className="absolute z-50 mt-2 max-h-64 w-full overflow-y-auto rounded-xl border border-[#dce2d8] bg-white p-1.5 shadow-xl">{options.map(option=><button key={option} type="button" onClick={()=>onSelect(option)} className={`flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-xs transition ${value===option?"bg-[#edf5e8] font-bold text-[#0b6531]":"hover:bg-[#f6f8f4]"}`}>{option}{value===option?<Check className="h-4 w-4"/>:null}</button>)}</div>:null}</div>}
function TravellerStepper({value,onChange}:{value:number;onChange:(v:number)=>void}){return <div className="rani-control mt-2 flex h-12 items-center justify-between px-2"><button type="button" onClick={()=>onChange(Math.max(1,value-1))} className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf5e8] text-[#0b6531]"><Minus className="h-4 w-4"/></button><div className="flex items-center gap-2 text-sm font-bold"><UsersRound className="h-4 w-4 text-[#0b6531]"/>{value}</div><button type="button" onClick={()=>onChange(Math.min(99,value+1))} className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf5e8] text-[#0b6531]"><Plus className="h-4 w-4"/></button></div>}
function CustomDatePicker({value,open,month,today,onToggle,onMonthChange,onSelect}:{value:string;open:boolean;month:Date;today:Date;onToggle:()=>void;onMonthChange:(d:Date)=>void;onSelect:(v:string)=>void}){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1),min=formatDate(today.getFullYear(),today.getMonth(),today.getDate());return <div className="relative mt-2"><button type="button" onClick={onToggle} className="rani-control flex h-12 items-center gap-3 px-4 text-left text-sm"><CalendarDays className="h-4 w-4 text-[#0b6531]"/><span className={value?"":"text-[#949b94]"}>{displayDate(value)}</span></button>{open?<div className="absolute left-0 z-50 mt-2 w-[300px] rounded-2xl border border-[#dce2d8] bg-white p-4 shadow-2xl"><div className="flex items-center justify-between"><button type="button" onClick={()=>onMonthChange(new Date(y,m-1,1))} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-[#edf5e8]"><ChevronLeft className="h-4 w-4 text-[#0b6531]"/></button><strong className="text-sm">{new Intl.DateTimeFormat("en-IN",{month:"long",year:"numeric"}).format(month)}</strong><button type="button" onClick={()=>onMonthChange(new Date(y,m+1,1))} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-[#edf5e8]"><ChevronRight className="h-4 w-4 text-[#0b6531]"/></button></div><div className="mt-3 grid grid-cols-7 gap-1 text-center text-[10px] font-bold text-[#8a938b]">{["Su","Mo","Tu","We","Th","Fr","Sa"].map(d=><span key={d}>{d}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-1">{cells.map((day,index)=>{if(!day)return <span key={index}/>;const v=formatDate(y,m,day),disabled=v<min;return <button key={v} type="button" disabled={disabled} onClick={()=>onSelect(v)} className={`grid h-9 w-9 place-items-center rounded-full text-xs ${value===v?"bg-[#0b6531] font-bold text-white":disabled?"text-[#c8cec8]":"hover:bg-[#edf5e8] hover:text-[#0b6531]"}`}>{day}</button>})}</div></div>:null}</div>}
