"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";
import { BadgeIndianRupee, CalendarDays, CarFront, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Clock3, Headphones, MapPin, Minus, Phone, Plus, Route, Send, ShieldCheck, UsersRound, X } from "lucide-react";
import { FaWhatsapp } from "react-icons/fa";
import { siteContact } from "@/lib/site-data";
import { SiteCta } from "@/components/layout/site-cta";

const heroHighlights=[[Clock3,"Quick Response","Get a quote without a complicated booking process"],[BadgeIndianRupee,"Clear Quotations","Trip details and charges are explained before confirmation"],[Headphones,"Expert Support","Our team is available to help plan your journey"]] as const;
const whyQuote=[[Route,"Customized Itineraries","Travel plans tailored to your route, preferences and group size."],[CarFront,"Wide Range of Options","Sedans, SUVs, Force Travellers, buses and vehicles on demand."],[BadgeIndianRupee,"Transparent Quotations","Clear trip details with no hidden surprises."],[Headphones,"Personal Travel Assistance","Talk directly with our team for route and vehicle planning."]] as const;
const trustItems=[[ShieldCheck,"Safe & Reliable","Experienced drivers and dependable travel"],[CarFront,"Well Maintained Fleet","Comfortable vehicles for every group size"],[Clock3,"On-Time Service","Punctual pickup and coordinated journeys"],[UsersRound,"All Group Sizes","From solo travel to large group movement"]] as const;
const journeyOptions=["Local / Sightseeing","One Way","Round Trip","Multi-City","Airport / Railway Transfer","Corporate Travel","Tour Package","Wedding / Event","Other"];
const vehicleOptions=["Let Rani Tour's recommend","Toyota Etios / Sedan","Maruti Suzuki Dzire","Honda Amaze","Toyota Corolla","Innova Crysta","Toyota Fortuner","Force Traveller - 12 Seater","Force Traveller - 14 Seater","Force Traveller - 17 Seater","Force Traveller - 21 Seater","Tourist Bus - 24 Seater","Tourist Bus - 32 Seater","Other / On Demand"];
const fieldClass="rani-control mt-2 h-12 px-4 text-sm placeholder:text-[#949b94]";
type FormState={name:string;phone:string;email:string;journeyType:string;pickup:string;destination:string;date:string;travellers:number;duration:string;vehicle:string;message:string;consent:boolean};
const initialForm:FormState={name:"",phone:"",email:"",journeyType:"",pickup:"",destination:"",date:"",travellers:1,duration:"",vehicle:"Let Rani Tour's recommend",message:"",consent:false};
const pad=(v:number)=>String(v).padStart(2,"0");const formatDate=(y:number,m:number,d:number)=>`${y}-${pad(m+1)}-${pad(d)}`;
function displayDate(value:string){if(!value)return"Select travel date";const[y,m,d]=value.split("-").map(Number);return new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(y,m-1,d));}

export function GetQuotePageContent(){
 const[submitted,setSubmitted]=useState(false);const[sending,setSending]=useState(false);const[serverError,setServerError]=useState("");const[form,setForm]=useState<FormState>(initialForm);const[errors,setErrors]=useState<Record<string,string>>({});const[openControl,setOpenControl]=useState<"journey"|"vehicle"|"date"|null>(null);const today=useMemo(()=>new Date(),[]);const[calendarMonth,setCalendarMonth]=useState(()=>new Date(today.getFullYear(),today.getMonth(),1));
 const setValue=<K extends keyof FormState>(key:K,value:FormState[K])=>{setForm(c=>({...c,[key]:value}));setErrors(c=>{const n={...c};delete n[key];return n});setServerError("")};
 const validate=()=>{const n:Record<string,string>={};if(form.name.trim().length<2)n.name="Please enter your full name.";if(!/^[6-9]\d{9}$/.test(form.phone))n.phone="Enter a valid 10-digit Indian mobile number.";if(form.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email))n.email="Enter a valid email address.";if(!form.journeyType)n.journeyType="Please choose a journey type.";if(form.pickup.trim().length<2)n.pickup="Please enter the pickup location.";if(form.destination.trim().length<2)n.destination="Please enter the destination.";if(!form.date)n.date="Please choose a travel date.";if(!form.consent)n.consent="Please allow us to contact you about this request.";setErrors(n);return Object.keys(n).length===0};
 async function handleSubmit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!validate()||sending)return;setSending(true);setServerError("");try{const response=await fetch("/api/enquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:"get_quote",name:form.name,phone:form.phone,email:form.email,journeyType:form.journeyType,pickup:form.pickup,destination:form.destination,travelDate:form.date,travellers:form.travellers,duration:form.duration,vehicle:form.vehicle,message:form.message})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Unable to submit your quote request.");setSubmitted(true);setOpenControl(null)}catch(error){setServerError(error instanceof Error?error.message:"Unable to submit your quote request. Please try again.")}finally{setSending(false)}}
 return <>
 <section className="relative overflow-hidden bg-[#f9f8f3]"><div className="absolute inset-0"><Image src="https://images.pexels.com/photos/3581368/pexels-photo-3581368.jpeg?auto=compress&cs=tinysrgb&w=1920" alt="Scenic Rajasthan journey landscape" fill priority className="object-cover object-center" sizes="100vw"/><div className="absolute inset-0 bg-gradient-to-r from-white via-white/95 to-white/25"/></div><div className="relative mx-auto min-h-[470px] max-w-[1180px] px-4 py-12 sm:py-16"><div className="flex items-center gap-2 text-xs text-[#59645b]"><Link href="/">Home</Link><span>›</span><span>Get a Quote</span></div><div className="mt-8 max-w-[650px]"><h1 className="font-serif text-5xl font-bold leading-none text-[#17341f] sm:text-6xl">Get a Quote</h1><h2 className="mt-3 font-serif text-3xl font-bold text-[#c67b22] sm:text-4xl">Plan Your Perfect Journey</h2><div className="mt-5 flex items-center gap-3 text-[#d6a63a]"><span className="h-px w-10 bg-current"/><span>✤</span><span className="h-px w-10 bg-current"/></div><p className="mt-6 max-w-[540px] text-sm leading-7 text-[#465148]">Tell us your travel requirements and we will help you choose the right route, vehicle and travel plan with a clear quotation.</p><div className="mt-9 grid gap-5 sm:grid-cols-3">{heroHighlights.map(([Icon,title,text])=><div key={title} className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#edf5e8] text-[#0b6531]"><Icon className="h-5 w-5"/></div><div><h3 className="text-sm font-bold text-[#203524]">{title}</h3><p className="mt-1 text-[11px] leading-5 text-[#667067]">{text}</p></div></div>)}</div></div></div></section>
 <section className="bg-white py-14 sm:py-16"><div className="mx-auto grid max-w-[1180px] gap-8 px-4 lg:grid-cols-[.82fr_1.18fr]"><aside className="self-start overflow-hidden rounded-[26px] bg-[#0b4d29] text-white shadow-xl shadow-[#0b4d29]/10"><div className="p-7 sm:p-9"><span className="text-xs font-bold uppercase tracking-[.18em] text-[#e4b63f]">Why choose us</span><h2 className="mt-3 font-serif text-3xl font-bold leading-tight">Why Get a Quote from <span className="text-[#e4b63f]">Rani Tour&apos;s?</span></h2><div className="mt-8 grid gap-7">{whyQuote.map(([Icon,title,text])=><div key={title} className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-white/10 text-[#e4b63f]"><Icon className="h-5 w-5"/></div><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-xs leading-6 text-white/72">{text}</p></div></div>)}</div><div className="mt-9 border-t border-white/15 pt-7"><p className="text-xs font-semibold text-white/60">Need help before filling the form?</p><div className="mt-4 grid gap-3"><a href={siteContact.phones[0].href} className="flex items-center gap-3 rounded-xl border border-white/15 px-4 py-3 text-sm font-semibold transition hover:bg-white/10"><Phone className="h-4 w-4 text-[#e4b63f]"/>{siteContact.phones[0].display}</a><a href={siteContact.whatsapp} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 rounded-xl border border-white/15 px-4 py-3 text-sm font-semibold transition hover:bg-white/10"><FaWhatsapp className="h-4 w-4"/>WhatsApp Us</a></div></div></div></aside>
 <div className="rounded-[26px] border border-[#e4e3dc] bg-[#fffdfa] p-6 shadow-lg shadow-black/5 sm:p-8"><div className="text-center"><span className="text-xs font-bold uppercase tracking-[.18em] text-[#0b6531]">Travel Requirements</span><h2 className="mt-2 font-serif text-3xl font-bold text-[#17341f]">Tell Us About Your Journey</h2><div className="mx-auto mt-4 h-px w-16 bg-[#d6a63a]"/></div>
 {submitted?<div className="mt-9 rounded-2xl border border-[#9fc099] bg-[#f1f8ee] p-7 text-center"><CheckCircle2 className="mx-auto h-11 w-11 text-[#0b6531]"/><h3 className="mt-4 font-serif text-2xl font-bold text-[#17341f]">Quote Request Sent</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#5c685f]">Thank you. Your enquiry has been received and our team will contact you using the details you provided.</p><button type="button" onClick={()=>{setSubmitted(false);setForm(initialForm);setErrors({});setServerError("")}} className="mt-5 rounded-xl border border-[#0b6531] px-5 py-2.5 text-xs font-bold text-[#0b6531] transition hover:bg-[#0b6531] hover:text-white">Submit Another Request</button></div>:<form onSubmit={handleSubmit} noValidate className="mt-8 grid gap-5">
 <div className="grid gap-5 sm:grid-cols-2"><Field label="Full Name *" error={errors.name}><input value={form.name} onChange={e=>setValue("name",e.target.value)} placeholder="Enter your full name" className={fieldClass}/></Field><Field label="Mobile Number *" error={errors.phone}><input value={form.phone} onChange={e=>setValue("phone",e.target.value.replace(/\D/g,"").slice(0,10))} inputMode="numeric" placeholder="10-digit mobile number" className={fieldClass}/></Field></div>
 <div className="grid gap-5 sm:grid-cols-2"><Field label="Email Address" error={errors.email}><input value={form.email} onChange={e=>setValue("email",e.target.value)} inputMode="email" placeholder="Enter your email" className={fieldClass}/></Field><Field label="Journey Type *" error={errors.journeyType}><CustomSelect value={form.journeyType} placeholder="Select journey type" options={journeyOptions} open={openControl==="journey"} onToggle={()=>setOpenControl(openControl==="journey"?null:"journey")} onSelect={v=>{setValue("journeyType",v);setOpenControl(null)}}/></Field></div>
 <div className="grid gap-5 sm:grid-cols-2"><Field label="Pickup Location *" error={errors.pickup}><span className="relative block"><MapPin className="pointer-events-none absolute left-4 top-[26px] h-4 w-4 text-[#718074]"/><input value={form.pickup} onChange={e=>setValue("pickup",e.target.value)} placeholder="Enter pickup location" className={`${fieldClass} pl-11`}/></span></Field><Field label="Destination *" error={errors.destination}><span className="relative block"><MapPin className="pointer-events-none absolute left-4 top-[26px] h-4 w-4 text-[#718074]"/><input value={form.destination} onChange={e=>setValue("destination",e.target.value)} placeholder="Enter destination" className={`${fieldClass} pl-11`}/></span></Field></div>
 <div className="grid gap-5 sm:grid-cols-3"><Field label="Travel Date *" error={errors.date}><CustomDatePicker value={form.date} open={openControl==="date"} month={calendarMonth} today={today} onToggle={()=>setOpenControl(openControl==="date"?null:"date")} onMonthChange={setCalendarMonth} onSelect={v=>{setValue("date",v);setOpenControl(null)}}/></Field><Field label="Travellers *"><TravellerStepper value={form.travellers} onChange={v=>setValue("travellers",v)}/></Field><Field label="Trip Duration"><input value={form.duration} onChange={e=>setValue("duration",e.target.value)} placeholder="e.g. 3 Days" className={fieldClass}/></Field></div>
 <Field label="Preferred Vehicle"><CustomSelect value={form.vehicle} placeholder="Let Rani Tour's recommend" options={vehicleOptions} open={openControl==="vehicle"} onToggle={()=>setOpenControl(openControl==="vehicle"?null:"vehicle")} onSelect={v=>{setValue("vehicle",v);setOpenControl(null)}}/></Field>
 <Field label="Additional Requirements"><textarea value={form.message} onChange={e=>setValue("message",e.target.value)} rows={5} placeholder="Stops, luggage, hotel pickup, itinerary preferences or anything else..." className="rani-control mt-2 w-full resize-none px-4 py-3 text-sm leading-6 placeholder:text-[#949b94]"/></Field>
 <div><button type="button" role="checkbox" aria-checked={form.consent} onClick={()=>setValue("consent",!form.consent)} className="flex items-start gap-3 text-left text-[11px] leading-5 text-[#667067]"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-md border transition ${form.consent?"border-[#0b6531] bg-[#0b6531] text-white":"border-[#bac4b9] bg-white text-transparent"}`}><Check className="h-3.5 w-3.5"/></span><span>I agree to be contacted by Rani Tour&apos;s regarding this quote request.</span></button>{errors.consent?<p className="mt-1 text-[11px] font-medium text-[#b42318]">{errors.consent}</p>:null}</div>
 {(Object.keys(errors).length||serverError)?<div className="flex items-start gap-3 rounded-xl border border-[#f1c3bd] bg-[#fff4f2] px-4 py-3 text-xs text-[#912018]"><X className="mt-0.5 h-4 w-4 shrink-0"/><span>{serverError||"Please review the highlighted fields before submitting your request."}</span></div>:null}
 <button disabled={sending} type="submit" className="flex items-center justify-center gap-2 rounded-xl bg-[#147435] px-6 py-4 text-sm font-bold text-white shadow-md transition hover:-translate-y-0.5 hover:bg-[#0b6531] hover:shadow-lg disabled:cursor-wait disabled:opacity-60"><Send className="h-4 w-4"/>{sending?"Sending Request...":"Request My Free Quote"}<span>→</span></button><p className="text-center text-[11px] text-[#7c857e]">No booking is confirmed until our team verifies availability and shares the final quotation.</p>
 </form>}</div></div></section>
 <section className="bg-[#fff8ed] py-14"><div className="mx-auto max-w-[1180px] px-4"><div className="text-center"><span className="text-xs font-bold uppercase tracking-[.18em] text-[#0b6531]">Travel With Confidence</span><h2 className="mt-2 font-serif text-3xl font-bold text-[#17341f]">Simple Planning. Reliable Journeys.</h2><div className="mx-auto mt-4 h-px w-16 bg-[#d6a63a]"/></div><div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{trustItems.map(([Icon,title,text])=><div key={title} className="rounded-2xl border border-[#ece5d8] bg-white p-6 text-center shadow-sm"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-[#edf5e8] text-[#0b6531]"><Icon className="h-5 w-5"/></div><h3 className="mt-4 font-serif text-lg font-bold text-[#213825]">{title}</h3><p className="mt-2 text-xs leading-5 text-[#687169]">{text}</p></div>)}</div></div></section><SiteCta/></>
}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-xs font-semibold text-[#37443a]">{label}{children}{error?<span className="mt-1 block text-[11px] font-medium text-[#b42318]">{error}</span>:null}</label>}
function CustomSelect({value,placeholder,options,open,onToggle,onSelect}:{value:string;placeholder:string;options:readonly string[];open:boolean;onToggle:()=>void;onSelect:(v:string)=>void}){return <div className="relative mt-2"><button type="button" onClick={onToggle} className="rani-control flex h-12 items-center justify-between px-4 text-left text-sm"><span className={value?"":"text-[#949b94]"}>{value||placeholder}</span><ChevronDown className={`h-4 w-4 text-[#0b6531] transition ${open?"rotate-180":""}`}/></button>{open?<div className="absolute z-50 mt-2 max-h-64 w-full overflow-y-auto rounded-xl border border-[#dce2d8] bg-white p-1.5 shadow-xl">{options.map(option=><button key={option} type="button" onClick={()=>onSelect(option)} className={`flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-xs transition ${value===option?"bg-[#edf5e8] font-bold text-[#0b6531]":"hover:bg-[#f6f8f4]"}`}>{option}{value===option?<Check className="h-4 w-4"/>:null}</button>)}</div>:null}</div>}
function TravellerStepper({value,onChange}:{value:number;onChange:(v:number)=>void}){return <div className="rani-control mt-2 flex h-12 items-center justify-between px-2"><button type="button" onClick={()=>onChange(Math.max(1,value-1))} className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf5e8] text-[#0b6531]"><Minus className="h-4 w-4"/></button><div className="flex items-center gap-2 text-sm font-bold"><UsersRound className="h-4 w-4 text-[#0b6531]"/>{value}</div><button type="button" onClick={()=>onChange(Math.min(99,value+1))} className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf5e8] text-[#0b6531]"><Plus className="h-4 w-4"/></button></div>}
function CustomDatePicker({value,open,month,today,onToggle,onMonthChange,onSelect}:{value:string;open:boolean;month:Date;today:Date;onToggle:()=>void;onMonthChange:(d:Date)=>void;onSelect:(v:string)=>void}){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1),min=formatDate(today.getFullYear(),today.getMonth(),today.getDate());return <div className="relative mt-2"><button type="button" onClick={onToggle} className="rani-control flex h-12 items-center gap-3 px-4 text-left text-sm"><CalendarDays className="h-4 w-4 text-[#0b6531]"/><span className={value?"":"text-[#949b94]"}>{displayDate(value)}</span></button>{open?<div className="absolute left-0 z-50 mt-2 w-[300px] rounded-2xl border border-[#dce2d8] bg-white p-4 shadow-2xl"><div className="flex items-center justify-between"><button type="button" onClick={()=>onMonthChange(new Date(y,m-1,1))} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-[#edf5e8]"><ChevronLeft className="h-4 w-4 text-[#0b6531]"/></button><strong className="text-sm">{new Intl.DateTimeFormat("en-IN",{month:"long",year:"numeric"}).format(month)}</strong><button type="button" onClick={()=>onMonthChange(new Date(y,m+1,1))} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-[#edf5e8]"><ChevronRight className="h-4 w-4 text-[#0b6531]"/></button></div><div className="mt-3 grid grid-cols-7 gap-1 text-center text-[10px] font-bold text-[#8a938b]">{["Su","Mo","Tu","We","Th","Fr","Sa"].map(d=><span key={d}>{d}</span>)}</div><div className="mt-2 grid grid-cols-7 gap-1">{cells.map((day,index)=>{if(!day)return <span key={index}/>;const v=formatDate(y,m,day),disabled=v<min;return <button key={v} type="button" disabled={disabled} onClick={()=>onSelect(v)} className={`grid h-9 w-9 place-items-center rounded-full text-xs ${value===v?"bg-[#0b6531] font-bold text-white":disabled?"text-[#c8cec8]":"hover:bg-[#edf5e8] hover:text-[#0b6531]"}`}>{day}</button>})}</div></div>:null}</div>}
