"use client";

import { FormEvent, useState } from "react";
import { CheckCircle2, LockKeyhole, Send } from "lucide-react";
import { validateContactInput } from "@/lib/form-validation";

export function ContactForm(){
 const[status,setStatus]=useState<"idle"|"sending"|"success"|"error">("idle");
 const[message,setMessage]=useState("");
 const[errors,setErrors]=useState<Record<string,string>>({});
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(status==="sending")return;const form=e.currentTarget,fd=new FormData(form);const validation=validateContactInput({name:fd.get("name"),phone:fd.get("phone"),email:fd.get("email"),subject:fd.get("subject"),message:fd.get("message")});setErrors(validation.errors);if(!validation.valid){setStatus("error");setMessage("Please correct the highlighted fields before sending.");return}setStatus("sending");setMessage("");try{const response=await fetch("/api/enquiries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:"contact",...validation.data})});const data=await response.json().catch(()=>({}));if(!response.ok){if(data.errors)setErrors(data.errors);throw new Error(data.error||"Unable to send your message.")}form.reset();setErrors({});setStatus("success");setMessage("Thank you. Your message has been sent to Rani Tour's.");}catch(error){setStatus("error");setMessage(error instanceof Error?error.message:"Unable to send your message. Please try again.");}}
 return <form noValidate className="mt-7 grid gap-4 sm:grid-cols-2" onSubmit={submit}><Field label="Your Name *" name="name" placeholder="Enter your name" error={errors.name}/><Field label="Phone Number *" name="phone" placeholder="10-digit Indian mobile number" type="tel" inputMode="numeric" maxLength={10} error={errors.phone}/><Field label="Email Address *" name="email" placeholder="Enter your email" type="email" error={errors.email}/><Field label="Subject *" name="subject" placeholder="Enter a subject" error={errors.subject}/><label className="sm:col-span-2 text-xs font-semibold">Your Message *<textarea name="message" maxLength={4000} rows={7} placeholder="Type your message here..." className={`mt-2 w-full resize-none rounded-lg border bg-white px-4 py-3 text-sm font-normal outline-none ${errors.message?"border-red-400 focus:border-red-500":"border-[#dddcd6] focus:border-[#6f966d]"}`}/>{errors.message?<span className="mt-1 block text-[11px] font-medium text-red-600">{errors.message}</span>:null}</label><button disabled={status==="sending"} type="submit" className="sm:col-span-2 flex items-center justify-center gap-2 rounded-lg bg-[#0b6531] px-5 py-4 text-sm font-bold text-white transition hover:bg-[#084f27] disabled:cursor-wait disabled:opacity-60"><Send className="h-4 w-4"/>{status==="sending"?"Sending...":"Send Message"}</button>{message?<div role="status" className={`sm:col-span-2 flex items-center justify-center gap-2 rounded-xl px-4 py-3 text-center text-xs font-semibold ${status==="success"?"bg-[#edf7e9] text-[#0b6531]":"bg-[#fff1ef] text-[#9b2c21]"}`}>{status==="success"?<CheckCircle2 className="h-4 w-4"/>:null}{message}</div>:null}<p className="sm:col-span-2 flex items-center justify-center gap-2 text-center text-[10px] text-[#788078]"><LockKeyhole className="h-3.5 w-3.5"/>Your information is safe with us.</p></form>;
}
function Field({label,name,placeholder,type="text",inputMode,maxLength,error}:{label:string;name:string;placeholder:string;type?:string;inputMode?:React.HTMLAttributes<HTMLInputElement>["inputMode"];maxLength?:number;error?:string}){return <label className="text-xs font-semibold">{label}<input name={name} type={type} inputMode={inputMode} maxLength={maxLength} placeholder={placeholder} aria-invalid={Boolean(error)} className={`mt-2 w-full rounded-lg border bg-white px-4 py-3 text-sm font-normal outline-none ${error?"border-red-400 focus:border-red-500":"border-[#dddcd6] focus:border-[#6f966d]"}`}/>{error?<span className="mt-1 block text-[11px] font-medium text-red-600">{error}</span>:null}</label>}
