import Link from "next/link";
import { FaFacebookF, FaInstagram, FaWhatsapp, FaYoutube } from "react-icons/fa";
import { BadgeIndianRupee, CalendarDays, Clock3, Headphones, Mail, MapPin, MessageCircle, Phone, ShieldCheck } from "lucide-react";
import { siteContact } from "@/lib/site-data";
import { SiteCta } from "@/components/layout/site-cta";
import { ContactForm } from "@/components/contact/contact-form";

const heroFeatures=[[Headphones,"24/7 Support","We’re here anytime you need us"],[MessageCircle,"Quick Response","Fast help for your travel queries"],[ShieldCheck,"Trusted & Reliable","Dependable service you can count on"],[BadgeIndianRupee,"Best Price Guarantee","Transparent pricing with no hidden charges"]] as const;
const faqs=[[Headphones,"What are your booking hours?","Our booking team is available 24/7 to assist you with your travel plans."],[MapPin,"Do you offer customized tours?","Yes. We create customized routes and travel plans based on your preferences and group requirements."],[BadgeIndianRupee,"Is advance payment required?","Advance payment depends on the booking. Our team will guide you through the applicable terms."],[CalendarDays,"Can I change my booking?","Yes, bookings can be modified subject to availability and the applicable booking terms."]] as const;

export function ContactPageContent(){return <>
<section className="relative overflow-hidden bg-[#f8f8f5]"><div className="absolute inset-0 bg-cover bg-center lg:bg-[center_46%]" style={{backgroundImage:"url('https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=2200&q=88')"}} aria-hidden="true"/><div className="absolute inset-0 bg-gradient-to-r from-white via-white/88 to-white/16"/><div className="relative mx-auto min-h-[520px] max-w-[1180px] px-4 py-12 sm:py-16"><div className="flex items-center gap-2 text-xs text-[#4c5b4f]"><Link href="/">Home</Link><span>›</span><span>Contact</span></div><div className="mt-9 max-w-[610px]"><h1 className="hero-reveal font-serif text-5xl font-bold text-[#17341f] sm:text-6xl">Contact Us</h1><h2 className="mt-3 font-serif text-3xl font-bold text-[#cf7c14]">We&apos;re Here to Help!</h2><p className="mt-6 max-w-[540px] text-[15px] leading-7 text-[#344139]">Have a question, need a quote, or planning your next trip? Get in touch with us. Our team will reply as soon as possible.</p></div><div className="mt-9 grid max-w-[760px] gap-4 sm:grid-cols-2 lg:grid-cols-4">{heroFeatures.map(([Icon,title,text])=><div key={title} className="flex gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#eef5e9] text-[#0b6531]"><Icon className="h-5 w-5"/></div><div><h3 className="text-[13px] font-bold">{title}</h3><p className="mt-1 text-[10px] leading-4 text-[#5f6a61]">{text}</p></div></div>)}</div></div></section>
<section className="bg-white py-16"><div className="mx-auto grid max-w-[1180px] gap-12 px-4 lg:grid-cols-[.82fr_1.18fr]"><div><SectionHeading title="Get in Touch" align="left"/><div className="mt-8 divide-y divide-[#e9e4da]"><ContactItem icon={Phone} title="Call Us"><a href={siteContact.phones[0].href}>{siteContact.phones[0].display}</a><br/><a href={siteContact.phones[1].href}>{siteContact.phones[1].display}</a></ContactItem><ContactItem icon={Mail} title="Email Us"><a href={siteContact.emailHref}>{siteContact.email}</a></ContactItem><ContactItem icon={MapPin} title="Office Address"><a href={siteContact.mapsUrl} target="_blank" rel="noreferrer">Rani Tour&apos;s<br/>{siteContact.address}</a></ContactItem><ContactItem icon={Clock3} title="Office Hours">Mon - Sun: 9:00 AM - 8:00 PM<br/><span className="text-[#8a918a]">Booking support available 24/7</span></ContactItem><div className="flex gap-4 py-6"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#0b6531] text-white"><MessageCircle className="h-5 w-5"/></div><div><h3 className="text-sm font-bold">Follow Us</h3><div className="mt-3 flex gap-2"><Social href="https://www.facebook.com/" label="Facebook"><FaFacebookF/></Social><Social href="https://www.instagram.com/" label="Instagram"><FaInstagram/></Social><Social href="https://www.youtube.com/" label="YouTube"><FaYoutube/></Social><Social href={siteContact.whatsapp} label="WhatsApp"><FaWhatsapp/></Social></div></div></div></div></div><div className="rounded-[24px] border border-[#e3dfd7] bg-[#fffdfa] p-6 shadow-lg sm:p-8"><SectionHeading title="Send Us a Message" align="left"/><ContactForm/></div></div></section>
<section className="defer-render bg-[#fbf6ec] py-14"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading title="Find Us in Jodhpur"/><div className="mt-8 overflow-hidden rounded-[24px] border border-[#dfd8ca] bg-white shadow-sm lg:grid lg:grid-cols-[1.3fr_.7fr]"><div className="min-h-[390px]"><iframe title="Rani Tour's office location" src={`https://www.google.com/maps?q=${encodeURIComponent(`Rani Tour's, ${siteContact.address}`)}&z=17&output=embed`} className="block h-full min-h-[390px] w-full border-0" loading="lazy"/></div><div className="flex flex-col justify-center bg-[#0f522b] p-8 text-white"><MapPin className="h-8 w-8 text-[#efc34d]"/><h3 className="mt-5 font-serif text-3xl font-bold">Rani Tour&apos;s, Jodhpur</h3><p className="mt-4 text-sm leading-7 text-white/78">{siteContact.address}</p><a href={siteContact.mapsUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex w-fit rounded-full border border-white/35 px-5 py-3 text-xs font-bold">View on Google Maps →</a></div></div></div></section>
<section className="defer-render bg-[#fffaf1] py-14"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading title="Frequently Asked Questions"/><div className="mt-9 grid gap-6 md:grid-cols-2 xl:grid-cols-4">{faqs.map(([Icon,q,a])=><article key={q} className="text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full border border-[#b8cab5] bg-white text-[#0b6531]"><Icon className="h-5 w-5"/></div><h3 className="mt-4 font-serif text-lg font-bold">{q}</h3><p className="mx-auto mt-2 max-w-[230px] text-xs leading-6 text-[#687068]">{a}</p></article>)}</div></div></section><SiteCta/>
</>}
function ContactItem({icon:Icon,title,children}:{icon:typeof Phone;title:string;children:React.ReactNode}){return <div className="flex gap-4 py-6"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#0b6531] text-white"><Icon className="h-5 w-5"/></div><div><h3 className="text-sm font-bold">{title}</h3><div className="mt-1 text-xs leading-6 text-[#626b63]">{children}</div></div></div>}
function Social({href,label,children}:{href:string;label:string;children:React.ReactNode}){return <a href={href} target="_blank" rel="noreferrer" aria-label={label} className="grid h-9 w-9 place-items-center rounded-full border border-[#cfd9cc] bg-white text-[#0b6531] transition hover:bg-[#0b6531] hover:text-white">{children}</a>}
function SectionHeading({title,align="center"}:{title:string;align?:"left"|"center"}){return <div className={align==="center"?"text-center":"text-left"}><h2 className="font-serif text-3xl font-bold text-[#17341f] sm:text-4xl">{title}</h2><div className={`mt-4 flex items-center gap-3 text-[#d69a28] ${align==="center"?"justify-center":"justify-start"}`}><span className="h-px w-10 bg-current"/><span>✤</span><span className="h-px w-10 bg-current"/></div></div>}
