import { NextRequest,NextResponse } from "next/server";
import { Types } from "mongoose";
import { connectToDatabase } from "@/lib/db";
import { logAdminActivity,requireAdminApi } from "@/lib/admin-auth";
import { collectCmsPublicIds,destroyCloudinaryImage } from "@/lib/cloudinary";
import { normalizeFleetInput,validateFleetInput } from "@/lib/fleet";
import { FleetVehicle } from "@/models/FleetVehicle";

type Context={params:Promise<{id:string}>};
export async function GET(_:NextRequest,context:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await context.params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid vehicle id."},{status:400});await connectToDatabase();const item=await FleetVehicle.findById(id).lean();if(!item)return NextResponse.json({error:"Fleet vehicle not found."},{status:404});return NextResponse.json({item})}
export async function PUT(request:NextRequest,context:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await context.params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid vehicle id."},{status:400});const input=normalizeFleetInput(await request.json());const errors=validateFleetInput(input);if(errors.length)return NextResponse.json({error:errors[0],errors},{status:400});await connectToDatabase();const existing=await FleetVehicle.findById(id);if(!existing)return NextResponse.json({error:"Fleet vehicle not found."},{status:404});if(await FleetVehicle.exists({slug:input.slug,_id:{$ne:id}}))return NextResponse.json({error:"A fleet vehicle with this slug already exists."},{status:409});const oldIds=collectCmsPublicIds(existing.toObject(),"rani-tours/fleet/");const item=await FleetVehicle.findByIdAndUpdate(id,{...input,publishedAt:input.status==="published"?(existing.publishedAt||new Date()):null,updatedBy:admin.id},{new:true,runValidators:true});const newIds=collectCmsPublicIds(item?.toObject(),"rani-tours/fleet/");await Promise.all([...oldIds].filter(x=>!newIds.has(x)).map(destroyCloudinaryImage));await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Updated fleet vehicle",entity:"FleetVehicle",entityId:id,metadata:{name:input.name,status:input.status}});return NextResponse.json({item})}
export async function DELETE(_:NextRequest,context:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await context.params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid vehicle id."},{status:400});await connectToDatabase();const item=await FleetVehicle.findByIdAndDelete(id);if(!item)return NextResponse.json({error:"Fleet vehicle not found."},{status:404});await Promise.all([...collectCmsPublicIds(item.toObject(),"rani-tours/fleet/")].map(destroyCloudinaryImage));await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Deleted fleet vehicle",entity:"FleetVehicle",entityId:id,metadata:{name:item.name}});return NextResponse.json({success:true})}
