"use client";

import Image from "next/image";
import Link from "next/link";
import { motion } from "motion/react";
import { BadgeIndianRupee, BriefcaseBusiness, Building2, CalendarCheck2, CarFront, CheckCircle2, FileText, Headphones, Laptop2, Leaf, MapPinned, Plane, ShieldCheck, Sparkles, UserRoundCheck, UsersRound } from "lucide-react";
import { SiteCta } from "@/components/layout/site-cta";

const heroImage="https://images.pexels.com/photos/31906969/pexels-photo-31906969.jpeg?auto=compress&cs=tinysrgb&w=2200";
const heroBenefits=[[BriefcaseBusiness,"Business Focused","Travel solutions designed around your company needs."],[CalendarCheck2,"On-time, Every Time","Punctual pickups and dependable coordination."],[ShieldCheck,"Safe & Reliable","Verified drivers and well-maintained vehicles."],[FileText,"Easy Billing","Clear invoicing and streamlined corporate billing."],[Headphones,"24/7 Support","Round-the-clock assistance for every trip."],[Sparkles,"Customized Solutions","Tailored plans for teams, guests and executives."]] as const;
const services=[{icon:Plane,title:"Airport Transfers",text:"Seamless airport pick-up and drop-off for employees, executives and clients.",image:"https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&q=82&w=1000"},{icon:UsersRound,title:"Employee Transport",text:"Reliable daily and scheduled commute solutions for your workforce.",image:"https://images.pexels.com/photos/31906969/pexels-photo-31906969.jpeg?auto=compress&cs=tinysrgb&w=1000"},{icon:BriefcaseBusiness,title:"Corporate Meetings",text:"Professional travel support for meetings, conferences and business events.",image:"https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&q=82&w=1000"},{icon:UserRoundCheck,title:"Executive Travel",text:"Comfortable, discreet and personalized travel for executives and VIP guests.",image:"https://images.pexels.com/photos/9623676/pexels-photo-9623676.jpeg?auto=compress&cs=tinysrgb&w=1000"},{icon:Building2,title:"Outstation Travel",text:"Comfortable intercity transportation for business trips and client visits.",image:"https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&q=82&w=1000"},{icon:FileText,title:"MICE & Event Travel",text:"Coordinated transport support for conferences, seminars and corporate events.",image:"https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=82&w=1000"}] as const;
const corporateReasons=[[UsersRound,"Trusted by Businesses","Flexible solutions for startups, SMEs and established organisations."],[MapPinned,"Pan India Coverage","Business travel support across Rajasthan and major Indian destinations."],[BadgeIndianRupee,"Cost Effective","Transparent quotations and practical plans for recurring travel."],[Laptop2,"Easy Coordination","Clear trip details and responsive coordination from booking to drop-off."],[Leaf,"Responsible Travel","Clean, well-maintained vehicles and sensible route planning."]] as const;
const trustItems=[[ShieldCheck,"Trusted & Reliable","Dependable travel support for every business journey."],[BadgeIndianRupee,"Transparent Pricing","Clear quotations with no hidden surprises."],[CarFront,"Comfort & Safety","Comfortable vehicles and experienced professional drivers."],[Headphones,"24/7 Travel Support","Our team is available whenever your trip needs assistance."]] as const;

export function CorporatePageContent(){return <>
<section className="relative overflow-hidden bg-[#f7f7f4]"><Image src={heroImage} alt="Business professionals beside a white corporate car" fill priority unoptimized sizes="100vw" className="object-cover object-center"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(255,255,255,.98)_0%,rgba(255,255,255,.91)_35%,rgba(255,255,255,.38)_64%,rgba(255,255,255,.08)_100%)]"/><div className="relative mx-auto min-h-[420px] max-w-[1180px] px-4 py-10 sm:py-12"><div className="max-w-[540px]"><div className="flex items-center gap-2 text-xs text-[#4e5b4f]"><Link href="/" className="transition hover:text-[#087239]">Home</Link><span>›</span><span>Corporate Travel</span></div><motion.h1 initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} className="mt-7 font-serif text-5xl font-bold leading-[.98] text-[#17341f] sm:text-6xl">Corporate<span className="mt-2 block text-[#d98200]">Travel Solutions</span></motion.h1><div className="mt-5 flex items-center gap-3 text-[#d69a28]"><span className="h-px w-8 bg-current"/><span>✤</span><span className="h-px w-8 bg-current"/></div><p className="mt-5 max-w-[500px] text-sm leading-7 text-[#303b31]">Smart, efficient and reliable corporate travel solutions tailored to your business needs, helping your teams, guests and executives travel comfortably and on time.</p></div></div></section>
<section className="relative z-10 -mt-5 bg-transparent px-4"><div className="mx-auto grid max-w-[1180px] gap-0 overflow-hidden rounded-2xl border border-[#eee3d4] bg-[#fff9f0] shadow-[0_14px_34px_rgba(60,48,30,.08)] sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{heroBenefits.map(([Icon,title,text])=><div key={title} className="flex gap-3 border-b border-[#eadfce] px-4 py-5 sm:border-r lg:border-b-0 last:border-r-0"><Icon className="mt-0.5 h-7 w-7 shrink-0 text-[#0a6330]"/><div><h2 className="text-[11px] font-bold text-[#203224]">{title}</h2><p className="mt-1 text-[9px] leading-4 text-[#687068]">{text}</p></div></div>)}</div></section>
<section className="bg-white py-12 sm:py-16"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading eyebrow="OUR CORPORATE TRAVEL SERVICES" title="Travel Solutions Built for Business"/><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{services.map((service,index)=>{const Icon=service.icon;return <motion.article key={service.title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.25}} transition={{delay:index*.05}} whileHover={{y:-5}} className="overflow-hidden rounded-2xl border border-[#e8e2da] bg-white shadow-[0_10px_30px_rgba(43,38,29,.06)]"><div className="relative h-36 overflow-hidden bg-[#f3f3f0]"><Image src={service.image} alt={service.title} fill unoptimized sizes="(max-width:768px) 100vw, 240px" className="object-cover"/></div><div className="relative px-4 pb-5 pt-8"><div className="absolute -top-6 left-4 grid h-12 w-12 place-items-center rounded-full border-4 border-white bg-[#0b5f30] text-white shadow-sm"><Icon className="h-5 w-5"/></div><h3 className="font-serif text-[17px] font-bold text-[#19351f]">{service.title}</h3><p className="mt-2 text-[10px] leading-5 text-[#657066]">{service.text}</p></div></motion.article>})}</div></div></section>
<section className="bg-[#fffaf2] py-10 sm:py-12"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading title="Why Choose Rani Tour's for Corporate Travel?"/><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-5">{corporateReasons.map(([Icon,title,text])=><div key={title} className="flex gap-4 lg:border-r lg:border-[#e3d8c8] lg:pr-5 lg:last:border-r-0"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full border border-[#96ad99] bg-white text-[#0b6331]"><Icon className="h-6 w-6"/></div><div><h3 className="text-xs font-bold text-[#213325]">{title}</h3><p className="mt-2 text-[10px] leading-5 text-[#657066]">{text}</p></div></div>)}</div></div></section>
<section className="bg-white py-10 sm:py-12"><div className="mx-auto max-w-[1180px] px-4"><SectionHeading eyebrow="WHY TRAVEL WITH RANI TOUR'S?" title="Dependable Travel for Every Business Journey"/><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{trustItems.map(([Icon,title,text])=><div key={title} className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-full border border-[#9bae9d] text-[#0b6331]"><Icon className="h-6 w-6"/></div><div><h3 className="text-sm font-bold text-[#213325]">{title}</h3><p className="mt-1 text-[10px] leading-5 text-[#687068]">{text}</p></div></div>)}</div></div></section>
<SiteCta/>
</>}
function SectionHeading({title,eyebrow}:{title:string;eyebrow?:string}){return <div className="text-center">{eyebrow?<p className="text-[10px] font-bold tracking-[0.2em] text-[#17713d]">{eyebrow}</p>:null}<h2 className="mt-2 font-serif text-3xl font-bold text-[#17341f] sm:text-[34px]">{title}</h2><div className="mx-auto mt-3 flex w-max items-center gap-3 text-[#d69a28]"><span className="h-px w-9 bg-current"/><CheckCircle2 className="h-4 w-4"/><span className="h-px w-9 bg-current"/></div></div>}
