"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { Activity,ChevronDown,ChevronRight,Clock3,Search,ShieldCheck,UserRound } from "lucide-react";
import { CustomSelect } from "@/components/admin/custom-select";

type Item={_id:string;action:string;adminName?:string;entity:string;entityId?:string|null;metadata?:Record<string,unknown>;ipAddress?:string|null;createdAt:string};
type Response={items:Item[];hasMore:boolean;nextCursor:string|null;entities:string[];admins:string[];total:number};
const input="h-11 w-full rounded-xl border border-[#143124]/10 bg-white px-3 text-sm outline-none transition focus:border-[#0b6b3a] focus:ring-2 focus:ring-[#0b6b3a]/10";

export function ActivityExplorer(){
  const[items,setItems]=useState<Item[]>([]);const[q,setQ]=useState("");const[entity,setEntity]=useState("");const[admin,setAdmin]=useState("");const[loading,setLoading]=useState(true);const[more,setMore]=useState(false);const[cursor,setCursor]=useState<string|null>(null);const[entities,setEntities]=useState<string[]>([]);const[admins,setAdmins]=useState<string[]>([]);const[total,setTotal]=useState(0);const[expanded,setExpanded]=useState<string|null>(null);
  const load=useCallback(async(append=false)=>{setLoading(true);const p=new URLSearchParams();if(q)p.set("q",q);if(entity)p.set("entity",entity);if(admin)p.set("admin",admin);if(append&&cursor)p.set("cursor",cursor);const r=await fetch(`/api/admin/activity?${p.toString()}`);const d=await r.json() as Response;if(r.ok){setItems(current=>append?[...current,...d.items]:d.items);setMore(d.hasMore);setCursor(d.nextCursor);setEntities(d.entities||[]);setAdmins(d.admins||[]);setTotal(d.total||0)}setLoading(false)},[q,entity,admin,cursor]);
  useEffect(()=>{const t=setTimeout(()=>{setCursor(null);void load(false)},250);return()=>clearTimeout(t)},[q,entity,admin]);
  const today=useMemo(()=>items.filter(i=>new Date(i.createdAt).toDateString()===new Date().toDateString()).length,[items]);
  return <div className="space-y-6"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0b6b3a]">Audit & Security</p><h1 className="mt-1 text-3xl font-black md:text-4xl">Activity Log</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#6d806f]">A searchable audit trail of admin authentication, content changes, enquiry updates and billing actions.</p></div><div className="grid grid-cols-2 gap-3"><Stat icon={Activity} label="Total Events" value={total}/><Stat icon={Clock3} label="Loaded Today" value={today}/></div></section><section className="grid gap-3 rounded-2xl border border-[#143124]/10 bg-white p-4 lg:grid-cols-[1fr_220px_220px]"><label className="relative"><Search className="absolute left-3 top-3.5 size-4 text-[#849087]"/><input className={`${input} pl-10`} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search action, admin, area or record ID..."/></label><CustomSelect value={entity} onChange={setEntity} placeholder="All areas" options={[{value:"",label:"All areas"},...entities.map(v=>({value:v,label:v}))]}/><CustomSelect value={admin} onChange={setAdmin} placeholder="All admins" options={[{value:"",label:"All admins"},...admins.map(v=>({value:v,label:v}))]}/></section><section className="overflow-hidden rounded-2xl border border-[#143124]/10 bg-white"><div className="hidden grid-cols-[1.5fr_.8fr_.8fr_.9fr_46px] gap-4 bg-[#f5f8f2] px-5 py-3 text-[11px] font-black uppercase tracking-[.14em] text-[#68756a] md:grid"><span>Action</span><span>Admin</span><span>Area</span><span>Time</span><span/></div><div className="divide-y divide-[#143124]/8">{loading&&!items.length?<div className="p-10 text-center text-sm text-[#7b8d7e]">Loading activity…</div>:items.length?items.map(item=><ActivityRow key={item._id} item={item} expanded={expanded===item._id} onToggle={()=>setExpanded(expanded===item._id?null:item._id)}/>):<div className="p-10 text-center text-sm text-[#7b8d7e]">No activity matches the selected filters.</div>}</div></section>{more&&<div className="flex justify-center"><button disabled={loading} onClick={()=>void load(true)} className="rounded-xl border border-[#0b6b3a]/25 bg-white px-5 py-2.5 text-sm font-bold text-[#0b6b3a] transition hover:bg-[#f3f8ef] disabled:opacity-50">{loading?"Loading…":"Load More"}</button></div>}</div>
}
function Stat({icon:Icon,label,value}:{icon:typeof Activity;label:string;value:number}){return <div className="min-w-[140px] rounded-2xl border border-[#143124]/10 bg-white p-4"><div className="flex items-center gap-2 text-[#0b6b3a]"><Icon className="size-4"/><span className="text-[10px] font-black uppercase tracking-[.14em]">{label}</span></div><p className="mt-2 text-2xl font-black">{value.toLocaleString("en-IN")}</p></div>}
function ActivityRow({item,expanded,onToggle}:{item:Item;expanded:boolean;onToggle:()=>void}){const meta=Object.entries(item.metadata||{}).filter(([,v])=>v!==null&&v!==undefined&&String(v)!=="");return <div><button onClick={onToggle} className="grid w-full gap-2 px-5 py-4 text-left transition hover:bg-[#fafcf8] md:grid-cols-[1.5fr_.8fr_.8fr_.9fr_46px] md:items-center md:gap-4"><div><div className="flex items-start gap-3"><span className="mt-1 grid size-8 shrink-0 place-items-center rounded-xl bg-[#eef5df] text-[#0b6b3a]"><ShieldCheck className="size-4"/></span><div><p className="font-bold text-[#203326]">{item.action}</p>{item.entityId&&<p className="mt-1 font-mono text-[10px] text-[#8a958c]">ID: {item.entityId}</p>}</div></div></div><div className="flex items-center gap-2 text-sm"><UserRound className="size-4 text-[#839086]"/><span>{item.adminName||"System"}</span></div><span className="w-fit rounded-full bg-[#f0f4ed] px-2.5 py-1 text-xs font-bold capitalize text-[#526257]">{item.entity}</span><div className="text-xs text-[#718075]"><p className="font-semibold text-[#445247]">{new Date(item.createdAt).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</p><p>{new Date(item.createdAt).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit"})}</p></div><span className="grid size-8 place-items-center rounded-lg border border-[#143124]/10 text-[#6c796e]">{expanded?<ChevronDown className="size-4"/>:<ChevronRight className="size-4"/>}</span></button>{expanded&&<div className="border-t border-[#143124]/8 bg-[#fafcf8] px-5 py-4 md:pl-16"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{item.ipAddress&&<Meta label="IP Address" value={item.ipAddress}/>} {meta.map(([k,v])=><Meta key={k} label={k.replaceAll("_"," ")} value={typeof v==="object"?JSON.stringify(v):String(v)}/>)}</div>{!item.ipAddress&&!meta.length&&<p className="text-xs text-[#7c887e]">No additional metadata was stored for this event.</p>}</div>}</div>}
function Meta({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-[#143124]/8 bg-white p-3"><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#839087]">{label}</p><p className="mt-1 break-words text-xs font-semibold text-[#344238]">{value}</p></div>}
