"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Edit3,Plus,Search,Star,Trash2 } from "lucide-react";

type Item={_id:string;title:string;slug:string;entityType:"destination"|"category";categoryType:string;state?:string;region?:string;status:"draft"|"published";featured:boolean;heroImage?:{url?:string}};
export function DestinationManager(){const[items,setItems]=useState<Item[]>([]);const[search,setSearch]=useState("");const[status,setStatus]=useState("all");const[type,setType]=useState("all");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams({limit:"50",status,entityType:type});if(search.trim())p.set("search",search.trim());const r=await fetch(`/api/admin/destinations?${p}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load destinations.");setItems(j.items||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load destinations.")}finally{setLoading(false)}},[search,status,type]);
 useEffect(()=>{const t=window.setTimeout(()=>void load(),250);return()=>window.clearTimeout(t)},[load]);
 const counts=useMemo(()=>({total:items.length,published:items.filter(x=>x.status==="published").length,categories:items.filter(x=>x.entityType==="category").length}),[items]);
 async function remove(item:Item){if(!window.confirm(`Delete “${item.title}”?`))return;const r=await fetch(`/api/admin/destinations/${item._id}`,{method:"DELETE"});const j=await r.json();if(!r.ok)return window.alert(j.error||"Unable to delete.");setItems(old=>old.filter(x=>x._id!==item._id))}
 return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">Content Management</p><h1 className="mt-1 text-3xl font-black">Destinations</h1><p className="mt-2 max-w-2xl text-sm text-[#68806f]">Manage cities, regions and travel themes from one reusable destination system.</p></div><Link href="/admin/destinations/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#0b6b3a] px-5 py-3 text-sm font-bold text-white"><Plus className="size-4"/>Add Destination</Link></div>
 <div className="grid gap-3 sm:grid-cols-3">{[["Total entries",counts.total],["Published",counts.published],["Category pages",counts.categories]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-[#143124]/10 bg-white p-5"><p className="text-sm text-[#68806f]">{l}</p><p className="mt-1 text-3xl font-black">{v}</p></div>)}</div>
 <div className="rounded-2xl border border-[#143124]/10 bg-white p-4"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#68806f]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search destinations, states or regions…" className="w-full rounded-xl border border-[#143124]/15 bg-[#f8faf6] py-3 pl-10 pr-4 text-sm"/></label><select value={type} onChange={e=>setType(e.target.value)} className="rounded-xl border border-[#143124]/15 bg-[#f8faf6] px-4 py-3 text-sm"><option value="all">All types</option><option value="destination">Destinations</option><option value="category">Category pages</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-[#143124]/15 bg-[#f8faf6] px-4 py-3 text-sm"><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select></div></div>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 {loading?<div className="rounded-2xl border border-[#143124]/10 bg-white p-10 text-center text-sm text-[#68806f]">Loading destinations…</div>:items.length===0?<div className="rounded-2xl border border-dashed border-[#143124]/20 bg-white p-12 text-center text-sm text-[#68806f]">No destinations found.</div>:<div className="overflow-hidden rounded-2xl border border-[#143124]/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#f6f8f4] text-xs uppercase tracking-wide text-[#68806f]"><tr><th className="px-5 py-4">Entry</th><th className="px-5 py-4">Kind</th><th className="px-5 py-4">Location</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{items.map(item=><tr key={item._id} className="border-t border-[#143124]/8"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="relative size-14 overflow-hidden rounded-xl bg-[#eef3ea]">{item.heroImage?.url&&<Image src={item.heroImage.url} alt="" fill unoptimized className="object-cover"/>}</div><div><div className="flex items-center gap-2"><p className="font-bold">{item.title}</p>{item.featured&&<Star className="size-4 fill-amber-400 text-amber-400"/>}</div><p className="text-xs text-[#68806f]">/{item.slug}</p></div></div></td><td className="px-5 py-4 capitalize">{item.entityType} · {item.categoryType}</td><td className="px-5 py-4">{item.state||item.region||"—"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.status==="published"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{item.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link href={`/admin/destinations/${item._id}`} className="rounded-lg border border-[#143124]/10 p-2"><Edit3 className="size-4"/></Link><button onClick={()=>remove(item)} className="rounded-lg border border-red-200 p-2 text-red-600"><Trash2 className="size-4"/></button></div></td></tr>)}</tbody></table></div></div>}</div>}
