"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { ChangeEvent,useState } from "react";
import { ImagePlus,Plus,Save,Trash2 } from "lucide-react";

type CmsImage={url:string;publicId?:string;alt?:string};
type Card={title:string;description:string;image:CmsImage|null;meta:string};
type Faq={question:string;answer:string};
type DestinationData={_id?:string;title:string;slug:string;entityType:"destination"|"category";categoryType:"city"|"region"|"theme";tagline:string;shortDescription:string;overview:string;heroImage:CmsImage|null;gallery:CmsImage[];country:string;state:string;region:string;bestTimeToVisit:string;idealDuration:string;knownFor:string[];latitude:number|null;longitude:number|null;attractions:Card[];experiences:Card[];travelTips:string[];ctaTitle:string;ctaDescription:string;faq:Faq[];featured:boolean;status:"draft"|"published";sortOrder:number;seo:{metaTitle:string;metaDescription:string;keywords:string[];canonicalUrl:string;ogImage:CmsImage|null}};
const empty:DestinationData={title:"",slug:"",entityType:"destination",categoryType:"city",tagline:"",shortDescription:"",overview:"",heroImage:null,gallery:[],country:"India",state:"",region:"",bestTimeToVisit:"",idealDuration:"",knownFor:[],latitude:null,longitude:null,attractions:[],experiences:[],travelTips:[],ctaTitle:"Plan Your Trip",ctaDescription:"",faq:[],featured:false,status:"draft",sortOrder:0,seo:{metaTitle:"",metaDescription:"",keywords:[],canonicalUrl:"",ogImage:null}};
const field="w-full rounded-xl border border-[#143124]/15 bg-white px-3.5 py-3 text-sm outline-none focus:border-[#0b6b3a] focus:ring-2 focus:ring-[#0b6b3a]/10";
const label="mb-1.5 block text-xs font-bold uppercase tracking-wide text-[#526858]";
const slugify=(v:string)=>v.toLowerCase().trim().replace(/['’]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);
const lines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);
export function DestinationForm({initialData}:{initialData?:DestinationData}){const router=useRouter();const[data,setData]=useState<DestinationData>({...empty,...initialData,seo:{...empty.seo,...initialData?.seo}});const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState("");const[error,setError]=useState("");const set=<K extends keyof DestinationData>(k:K,v:DestinationData[K])=>setData(o=>({...o,[k]:v}));
 async function upload(file:File){const body=new FormData();body.append("file",file);body.append("folder","destinations");const r=await fetch("/api/admin/uploads",{method:"POST",body});const j=await r.json();if(!r.ok)throw new Error(j.error||"Upload failed.");return j.image as CmsImage}
 async function uploadOne(e:ChangeEvent<HTMLInputElement>,target:"hero"|"gallery"|"og"){const f=e.target.files?.[0];if(!f)return;setUploading(target);try{const img=await upload(f);if(target==="hero")set("heroImage",{...img,alt:data.title});else if(target==="gallery")set("gallery",[...data.gallery,{...img,alt:data.title}]);else setData(o=>({...o,seo:{...o.seo,ogImage:{...img,alt:o.title}}}))}catch(err){setError(err instanceof Error?err.message:"Upload failed.")}finally{setUploading("");e.target.value=""}}
 async function uploadCard(e:ChangeEvent<HTMLInputElement>,group:"attractions"|"experiences",index:number){const f=e.target.files?.[0];if(!f)return;setUploading(`${group}-${index}`);try{const img=await upload(f);setData(o=>({...o,[group]:o[group].map((x,i)=>i===index?{...x,image:img}:x)}))}catch(err){setError(err instanceof Error?err.message:"Upload failed.")}finally{setUploading("");e.target.value=""}}
 async function save(status?:"draft"|"published"){setSaving(true);setError("");const payload={...data,status:status??data.status,slug:data.slug||slugify(data.title)};try{const r=await fetch(initialData?`/api/admin/destinations/${initialData._id}`:"/api/admin/destinations",{method:initialData?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to save destination.");router.push("/admin/destinations");router.refresh()}catch(err){setError(err instanceof Error?err.message:"Unable to save destination.")}finally{setSaving(false)}}
 return <div className="space-y-6 pb-24"><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">Destination CMS</p><h1 className="mt-1 text-3xl font-black">{initialData?"Edit":"Create"} Destination</h1><p className="mt-2 text-sm text-[#68806f]">Use the same editor for city, region and travel-theme pages.</p></div><div className="flex gap-2"><button onClick={()=>save("draft")} disabled={saving} className="rounded-xl border border-[#143124]/15 bg-white px-4 py-3 text-sm font-bold">Save Draft</button><button onClick={()=>save("published")} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#0b6b3a] px-5 py-3 text-sm font-bold text-white"><Save className="size-4"/>{saving?"Saving…":"Publish"}</button></div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <Section title="Identity & hero"><div className="grid gap-4 md:grid-cols-2"><F t="Title"><input className={field} value={data.title} onChange={e=>{set("title",e.target.value);if(!initialData&&!data.slug)set("slug",slugify(e.target.value))}}/></F><F t="Slug"><input className={field} value={data.slug} onChange={e=>set("slug",slugify(e.target.value))}/></F><F t="Entry type"><select className={field} value={data.entityType} onChange={e=>set("entityType",e.target.value as DestinationData["entityType"])}><option value="destination">Destination page</option><option value="category">Category page</option></select></F><F t="Category type"><select className={field} value={data.categoryType} onChange={e=>set("categoryType",e.target.value as DestinationData["categoryType"])}><option value="city">City / place</option><option value="region">Region</option><option value="theme">Theme</option></select></F></div><F t="Tagline"><input className={field} value={data.tagline} onChange={e=>set("tagline",e.target.value)}/></F><F t="Short description"><textarea className={`${field} min-h-24`} value={data.shortDescription} onChange={e=>set("shortDescription",e.target.value)}/></F><F t="Overview"><textarea className={`${field} min-h-36`} value={data.overview} onChange={e=>set("overview",e.target.value)}/></F><ImagePicker image={data.heroImage} title="Hero image" uploading={uploading==="hero"} onFile={e=>uploadOne(e,"hero")} onRemove={()=>set("heroImage",null)}/></Section>
 <Section title="Location & travel facts"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><F t="Country"><input className={field} value={data.country} onChange={e=>set("country",e.target.value)}/></F><F t="State"><input className={field} value={data.state} onChange={e=>set("state",e.target.value)}/></F><F t="Region"><input className={field} value={data.region} onChange={e=>set("region",e.target.value)}/></F><F t="Best time to visit"><input className={field} value={data.bestTimeToVisit} onChange={e=>set("bestTimeToVisit",e.target.value)} placeholder="October to March"/></F><F t="Ideal duration"><input className={field} value={data.idealDuration} onChange={e=>set("idealDuration",e.target.value)} placeholder="2–3 Days"/></F><F t="Latitude"><input type="number" step="any" className={field} value={data.latitude??""} onChange={e=>set("latitude",e.target.value===""?null:Number(e.target.value))}/></F><F t="Longitude"><input type="number" step="any" className={field} value={data.longitude??""} onChange={e=>set("longitude",e.target.value===""?null:Number(e.target.value))}/></F><F t="Display order"><input type="number" className={field} value={data.sortOrder} onChange={e=>set("sortOrder",Number(e.target.value))}/></F></div><F t="Known for — one item per line"><textarea className={`${field} min-h-24`} value={data.knownFor.join("\n")} onChange={e=>set("knownFor",lines(e.target.value))}/></F></Section>
 <CardsSection title="Top attractions" items={data.attractions} group="attractions" uploading={uploading} onItems={v=>set("attractions",v)} onUpload={uploadCard}/><CardsSection title="Experiences" items={data.experiences} group="experiences" uploading={uploading} onItems={v=>set("experiences",v)} onUpload={uploadCard}/>
 <Section title="Travel tips & CTA"><F t="Travel tips — one per line"><textarea className={`${field} min-h-32`} value={data.travelTips.join("\n")} onChange={e=>set("travelTips",lines(e.target.value))}/></F><div className="grid gap-4 md:grid-cols-2"><F t="CTA title"><input className={field} value={data.ctaTitle} onChange={e=>set("ctaTitle",e.target.value)}/></F><F t="CTA description"><input className={field} value={data.ctaDescription} onChange={e=>set("ctaDescription",e.target.value)}/></F></div><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={data.featured} onChange={e=>set("featured",e.target.checked)}/> Featured destination</label></Section>
 <Section title="Gallery"><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{data.gallery.map((img,i)=><div key={`${img.url}-${i}`} className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src={img.url} alt={img.alt||"Destination"} fill unoptimized className="object-cover"/><button onClick={()=>set("gallery",data.gallery.filter((_,x)=>x!==i))} className="absolute right-2 top-2 rounded-full bg-black/70 p-1.5 text-white"><Trash2 className="size-3"/></button></div>)}<label className="grid aspect-[4/3] cursor-pointer place-items-center rounded-xl border border-dashed border-[#143124]/25 bg-[#f7faf5] text-xs font-bold"><span><ImagePlus className="mx-auto mb-1 size-5"/>Add image</span><input type="file" accept="image/*" className="hidden" onChange={e=>uploadOne(e,"gallery")}/></label></div></Section>
 <Section title="FAQs"><div className="space-y-3">{data.faq.map((x,i)=><div key={i} className="grid gap-3 rounded-xl border border-[#143124]/10 bg-[#fafcf9] p-4 md:grid-cols-[1fr_1.5fr_auto]"><input className={field} value={x.question} onChange={e=>set("faq",data.faq.map((y,j)=>j===i?{...y,question:e.target.value}:y))}/><textarea className={`${field} min-h-20`} value={x.answer} onChange={e=>set("faq",data.faq.map((y,j)=>j===i?{...y,answer:e.target.value}:y))}/><button onClick={()=>set("faq",data.faq.filter((_,j)=>j!==i))} className="self-start rounded-lg p-3 text-red-600"><Trash2 className="size-4"/></button></div>)}<button onClick={()=>set("faq",[...data.faq,{question:"",answer:""}])} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><Plus className="size-4"/>Add FAQ</button></div></Section>
 <Section title="SEO"><div className="grid gap-4 md:grid-cols-2"><F t="Meta title"><input className={field} value={data.seo.metaTitle} onChange={e=>setData(o=>({...o,seo:{...o.seo,metaTitle:e.target.value}}))}/></F><F t="Canonical URL"><input className={field} value={data.seo.canonicalUrl} onChange={e=>setData(o=>({...o,seo:{...o.seo,canonicalUrl:e.target.value}}))}/></F></div><F t="Meta description"><textarea className={`${field} min-h-24`} value={data.seo.metaDescription} onChange={e=>setData(o=>({...o,seo:{...o.seo,metaDescription:e.target.value}}))}/></F><F t="Keywords — one per line"><textarea className={`${field} min-h-24`} value={data.seo.keywords.join("\n")} onChange={e=>setData(o=>({...o,seo:{...o.seo,keywords:lines(e.target.value)}}))}/></F><ImagePicker image={data.seo.ogImage} title="Open Graph image" uploading={uploading==="og"} onFile={e=>uploadOne(e,"og")} onRemove={()=>setData(o=>({...o,seo:{...o.seo,ogImage:null}}))}/></Section></div>}
function F({t,children}:{t:string;children:React.ReactNode}){return <label className="block"><span className={label}>{t}</span>{children}</label>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-[#143124]/10 bg-white p-5 md:p-6"><h2 className="text-xl font-black">{title}</h2>{children}</section>}
function ImagePicker({image,title,uploading,onFile,onRemove}:{image:CmsImage|null;title:string;uploading:boolean;onFile:(e:ChangeEvent<HTMLInputElement>)=>void;onRemove:()=>void}){return <div><p className={label}>{title}</p><div className="flex items-center gap-3">{image?<div className="relative h-28 w-44 overflow-hidden rounded-xl"><Image src={image.url} alt={image.alt||title} fill unoptimized className="object-cover"/></div>:<div className="grid h-28 w-44 place-items-center rounded-xl border border-dashed text-xs text-[#68806f]">No image</div>}<div className="space-y-2"><label className="block cursor-pointer rounded-xl border px-4 py-2.5 text-sm font-bold">{uploading?"Uploading…":"Choose image"}<input type="file" accept="image/*" className="hidden" onChange={onFile}/></label>{image&&<button onClick={onRemove} className="text-sm font-semibold text-red-600">Remove</button>}</div></div></div>}
function CardsSection({title,items,group,uploading,onItems,onUpload}:{title:string;items:Card[];group:"attractions"|"experiences";uploading:string;onItems:(v:Card[])=>void;onUpload:(e:ChangeEvent<HTMLInputElement>,g:"attractions"|"experiences",i:number)=>void}){return <Section title={title}><div className="space-y-3">{items.map((x,i)=><div key={i} className="grid gap-3 rounded-xl border border-[#143124]/10 bg-[#fafcf9] p-4 md:grid-cols-[1fr_1.4fr_1fr_auto]"><input className={field} value={x.title} onChange={e=>onItems(items.map((y,j)=>j===i?{...y,title:e.target.value}:y))} placeholder="Title"/><textarea className={`${field} min-h-20`} value={x.description} onChange={e=>onItems(items.map((y,j)=>j===i?{...y,description:e.target.value}:y))} placeholder="Description"/><div><input className={field} value={x.meta} onChange={e=>onItems(items.map((y,j)=>j===i?{...y,meta:e.target.value}:y))} placeholder="Meta e.g. 2–3 hrs"/><label className="mt-2 block cursor-pointer text-xs font-bold text-[#0b6b3a]">{uploading===`${group}-${i}`?"Uploading…":"Upload image"}<input type="file" accept="image/*" className="hidden" onChange={e=>onUpload(e,group,i)}/></label></div><button onClick={()=>onItems(items.filter((_,j)=>j!==i))} className="self-start rounded-lg p-3 text-red-600"><Trash2 className="size-4"/></button></div>)}<button onClick={()=>onItems([...items,{title:"",description:"",image:null,meta:""}])} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><Plus className="size-4"/>Add card</button></div></Section>}
