"use client";

import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ArrowRight,Mail,MessageSquareText,Phone,Search,Trash2 } from "lucide-react";
import { AdminSelect } from "@/components/admin/admin-select";
import { AppDialog } from "@/components/ui/app-dialog";

type Item={_id:string;source:"get_quote"|"contact";name:string;phone:string;email:string;subject:string;message:string;journeyType:string;pickup:string;destination:string;status:"new"|"contacted"|"qualified"|"converted"|"closed"|"spam";priority:"low"|"normal"|"high"|"urgent";createdAt:string};
const field="rounded-xl border border-[#143124]/15 bg-[#f8faf6] px-3.5 py-3 text-sm outline-none transition focus:border-[#0b6b3a] focus:ring-4 focus:ring-[#0b6b3a]/8";
const sourceOptions=[{value:"all",label:"All sources"},{value:"get_quote",label:"Get Quote"},{value:"contact",label:"Contact"}];
const statusOptions=[{value:"all",label:"All statuses"},{value:"new",label:"New"},{value:"contacted",label:"Contacted"},{value:"qualified",label:"Qualified"},{value:"converted",label:"Converted"},{value:"closed",label:"Closed"},{value:"spam",label:"Spam"}];
const statusStyle:Record<Item["status"],string>={new:"bg-amber-100 text-amber-800",contacted:"bg-blue-100 text-blue-800",qualified:"bg-violet-100 text-violet-800",converted:"bg-emerald-100 text-emerald-800",closed:"bg-slate-100 text-slate-700",spam:"bg-red-100 text-red-700"};

export function EnquiryManager(){const[items,setItems]=useState<Item[]>([]);const[search,setSearch]=useState("");const[status,setStatus]=useState("all");const[source,setSource]=useState("all");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[pendingDelete,setPendingDelete]=useState<Item|null>(null);const[dialogError,setDialogError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams({search,status,source});const r=await fetch(`/api/admin/enquiries?${p}`);const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load enquiries.");setItems(j.items||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load enquiries.")}finally{setLoading(false)}},[search,status,source]);
 useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[load]);
 const counts=useMemo(()=>({total:items.length,newCount:items.filter(x=>x.status==="new").length,converted:items.filter(x=>x.status==="converted").length}),[items]);
 async function remove(){if(!pendingDelete)return;const target=pendingDelete;setPendingDelete(null);try{const r=await fetch(`/api/admin/enquiries/${target._id}`,{method:"DELETE"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Unable to delete enquiry.");setItems(old=>old.filter(x=>x._id!==target._id));}catch(e){setDialogError(e instanceof Error?e.message:"Unable to delete enquiry.")}}
 return <div className="space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">Unified Inbox</p><h1 className="mt-1 text-3xl font-black">Enquiries</h1><p className="mt-2 text-sm text-[#68806f]">Review Get Quote and Contact enquiries, update their pipeline status and keep follow-up notes.</p></div><div className="grid gap-3 sm:grid-cols-3 xl:min-w-[430px]">{[["Visible",counts.total],["New",counts.newCount],["Converted",counts.converted]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-[#143124]/10 bg-white px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#7a8a7d]">{label}</p><p className="mt-1 text-xl font-black text-[#17341f]">{value}</p></div>)}</div></div>
 <section className="rounded-2xl border border-[#143124]/10 bg-white p-4"><div className="grid gap-3 md:grid-cols-[1fr_210px_210px]"><label className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#7b8d7e]"/><input className={`${field} w-full pl-9`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, phone, email or route…"/></label><AdminSelect value={source} onChange={setSource} options={sourceOptions}/><AdminSelect value={status} onChange={setStatus} options={statusOptions}/></div></section>
 {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <div className="overflow-hidden rounded-2xl border border-[#143124]/10 bg-white">{loading?<div className="p-8 text-sm text-[#68806f]">Loading enquiries…</div>:items.length===0?<div className="p-10 text-center"><MessageSquareText className="mx-auto size-8 text-[#8ca090]"/><p className="mt-3 text-sm font-semibold">No enquiries found</p><p className="mt-1 text-xs text-[#7b8d7e]">Try adjusting your filters.</p></div>:<div className="divide-y divide-[#143124]/8">{items.map(x=><article key={x._id} className="grid gap-4 p-5 transition hover:bg-[#fbfcfa] lg:grid-cols-[1.2fr_1fr_1.2fr_auto] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><Link href={`/admin/enquiries/${x._id}`} className="text-base font-black text-[#17341f] transition hover:text-[#0b6b3a]">{x.name}</Link><span className="rounded-full bg-[#eef5df] px-2.5 py-1 text-[10px] font-bold uppercase text-[#0b6b3a]">{x.source==="get_quote"?"Get Quote":"Contact"}</span><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${statusStyle[x.status]}`}>{x.status}</span></div><p className="mt-1 text-xs text-[#7b8d7e]">{new Date(x.createdAt).toLocaleString("en-IN")}</p></div><div className="space-y-1.5 text-xs text-[#526858]"><a href={`tel:${x.phone}`} className="flex items-center gap-2 hover:text-[#0b6b3a]"><Phone className="size-3.5"/>{x.phone}</a>{x.email&&<a href={`mailto:${x.email}`} className="flex items-center gap-2 hover:text-[#0b6b3a]"><Mail className="size-3.5"/>{x.email}</a>}</div><div><p className="text-sm font-bold text-[#223829]">{x.source==="get_quote"?(x.journeyType||"Travel enquiry"):(x.subject||"Contact enquiry")}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#7b8d7e]">{x.source==="get_quote"?`${x.pickup||"—"} → ${x.destination||"—"}`:x.message}</p></div><div className="flex justify-end gap-2"><Link href={`/admin/enquiries/${x._id}`} className="inline-flex items-center gap-1 rounded-xl border border-[#143124]/12 bg-[#f8faf6] px-3 py-2 text-xs font-bold text-[#174a29] transition hover:border-[#0b6b3a]/30 hover:bg-[#edf5df]">View <ArrowRight className="size-3.5"/></Link><button onClick={()=>setPendingDelete(x)} className="rounded-xl border border-red-200 p-2.5 text-red-600 transition hover:bg-red-50" aria-label="Delete enquiry"><Trash2 className="size-4"/></button></div></article>)}</div>}</div>
 <AppDialog open={Boolean(pendingDelete)} title="Delete enquiry?" message={pendingDelete?`Delete the enquiry from ${pendingDelete.name}? This action cannot be undone.`:""} tone="danger" confirmLabel="Delete Enquiry" onConfirm={remove} onCancel={()=>setPendingDelete(null)}/><AppDialog open={Boolean(dialogError)} title="Action failed" message={dialogError} tone="danger" onConfirm={()=>setDialogError("")}/></div>}
