"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays, CarFront, Clock3, Mail, MapPin, MessageSquareText, Phone, Route, StickyNote, UserRound, UsersRound } from "lucide-react";
import { AdminSelect } from "@/components/admin/admin-select";

type Note={_id?:string;text:string;adminName:string;createdAt:string};
type Data={_id:string;source:"get_quote"|"contact";name:string;phone:string;email:string;subject:string;message:string;journeyType:string;pickup:string;destination:string;travelDate?:string|null;travellers?:number|null;duration:string;vehicle:string;status:string;priority:string;notes:Note[];createdAt:string};
const statusOptions=["new","contacted","qualified","converted","closed","spam"].map(x=>({value:x,label:x[0].toUpperCase()+x.slice(1)}));
const priorityOptions=["low","normal","high","urgent"].map(x=>({value:x,label:x[0].toUpperCase()+x.slice(1)}));
const statusStyle:Record<string,string>={new:"bg-amber-100 text-amber-800",contacted:"bg-blue-100 text-blue-800",qualified:"bg-violet-100 text-violet-800",converted:"bg-emerald-100 text-emerald-800",closed:"bg-slate-100 text-slate-700",spam:"bg-red-100 text-red-700"};
const priorityStyle:Record<string,string>={low:"bg-slate-100 text-slate-700",normal:"bg-[#edf5df] text-[#0b6b3a]",high:"bg-orange-100 text-orange-800",urgent:"bg-red-100 text-red-700"};
export function EnquiryDetail({initialData}:{initialData:Data}){const router=useRouter();const[data,setData]=useState(initialData);const[note,setNote]=useState("");const[saving,setSaving]=useState(false);const[error,setError]=useState("");async function patch(body:Record<string,unknown>){setSaving(true);setError("");try{const r=await fetch(`/api/admin/enquiries/${data._id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to update enquiry.");setData(j.item);if(body.note)setNote("");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Unable to update enquiry.")}finally{setSaving(false)}}return <div className="space-y-6"><header className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">{data.source==="get_quote"?"Get Quote":"Contact"} Enquiry</p><h1 className="mt-1 text-3xl font-black text-[#17341f]">{data.name}</h1><p className="mt-2 text-sm text-[#68806f]">Received {new Date(data.createdAt).toLocaleString("en-IN")}</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1.5 text-[11px] font-black uppercase ${statusStyle[data.status]||"bg-slate-100 text-slate-700"}`}>{data.status}</span><span className={`rounded-full px-3 py-1.5 text-[11px] font-black uppercase ${priorityStyle[data.priority]||"bg-slate-100 text-slate-700"}`}>{data.priority} priority</span></div></header>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
<section className="grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><div className="rounded-2xl border border-[#143124]/10 bg-white p-5"><div className="flex items-center gap-2"><UserRound className="size-5 text-[#0b6b3a]"/><h2 className="text-lg font-black">Contact information</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><ContactCard icon={Phone} label="Phone" value={data.phone} href={`tel:${data.phone}`}/><ContactCard icon={Mail} label="Email" value={data.email||"Not provided"} href={data.email?`mailto:${data.email}`:undefined}/></div></div><div className="rounded-2xl border border-[#143124]/10 bg-white p-5"><h2 className="text-lg font-black">Lead controls</h2><div className="mt-4 space-y-4"><label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-[.08em] text-[#526858]">Status</span><AdminSelect value={data.status} disabled={saving} options={statusOptions} onChange={value=>patch({status:value})}/></label><label className="block"><span className="mb-1.5 block text-xs font-bold uppercase tracking-[.08em] text-[#526858]">Priority</span><AdminSelect value={data.priority} disabled={saving} options={priorityOptions} onChange={value=>patch({priority:value})}/></label>{saving?<p className="text-xs font-medium text-[#68806f]">Saving changes…</p>:null}</div></div></section>
<section className="rounded-2xl border border-[#143124]/10 bg-white p-5"><div className="flex items-center gap-2"><MessageSquareText className="size-5 text-[#0b6b3a]"/><h2 className="text-lg font-black">Enquiry details</h2></div>{data.source==="get_quote"?<div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><DetailCard icon={Route} label="Journey type" value={data.journeyType||"—"}/><DetailCard icon={MapPin} label="Route" value={`${data.pickup||"—"} → ${data.destination||"—"}`}/><DetailCard icon={CalendarDays} label="Travel date" value={data.travelDate?new Date(data.travelDate).toLocaleDateString("en-IN"):"—"}/><DetailCard icon={UsersRound} label="Travellers" value={String(data.travellers??"—")}/><DetailCard icon={Clock3} label="Duration" value={data.duration||"—"}/><DetailCard icon={CarFront} label="Preferred vehicle" value={data.vehicle||"—"}/></div>:<div className="mt-5"><DetailCard icon={MessageSquareText} label="Subject" value={data.subject||"Contact enquiry"}/></div>}{data.message&&<div className="mt-5 rounded-2xl border border-[#143124]/8 bg-[#f8faf6] p-5"><p className="text-xs font-bold uppercase tracking-[.08em] text-[#526858]">Message / requirements</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-[#314438]">{data.message}</p></div>}</section>
<section className="rounded-2xl border border-[#143124]/10 bg-white p-5"><div className="flex items-center gap-2"><StickyNote className="size-5 text-[#0b6b3a]"/><h2 className="text-lg font-black">Internal notes</h2></div><div className="mt-4 grid gap-3 lg:grid-cols-[1fr_auto]"><textarea className="min-h-28 w-full resize-none rounded-2xl border border-[#143124]/15 bg-[#f8faf6] px-4 py-3 text-sm leading-6 outline-none transition focus:border-[#0b6b3a] focus:ring-4 focus:ring-[#0b6b3a]/8" value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a follow-up note, callback summary or internal instruction…"/><button disabled={saving||!note.trim()} onClick={()=>patch({note})} className="self-end rounded-xl bg-[#0b6b3a] px-6 py-3 text-sm font-bold text-white transition hover:bg-[#07572f] disabled:opacity-50">Add Note</button></div><div className="mt-5 space-y-3">{data.notes?.length?data.notes.slice().reverse().map((x,i)=><div key={x._id||i} className="rounded-2xl border border-[#143124]/8 bg-[#fbfcfa] p-4"><p className="text-sm leading-6 text-[#304438]">{x.text}</p><p className="mt-2 text-xs text-[#7b8d7e]">{x.adminName||"Admin"} · {new Date(x.createdAt).toLocaleString("en-IN")}</p></div>):<p className="rounded-xl bg-[#f8faf6] p-4 text-sm text-[#7b8d7e]">No internal notes yet.</p>}</div></section></div>}
function ContactCard({icon:Icon,label,value,href}:{icon:typeof Phone;label:string;value:string;href?:string}){const content=<><div className="grid size-10 place-items-center rounded-xl bg-[#edf5df] text-[#0b6b3a]"><Icon className="size-4"/></div><div className="min-w-0"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#7c8a7e]">{label}</p><p className="mt-1 break-words text-sm font-bold text-[#24382a]">{value}</p></div></>;return href?<a href={href} className="flex items-center gap-3 rounded-2xl border border-[#143124]/8 bg-[#fbfcfa] p-4 transition hover:border-[#0b6b3a]/25 hover:bg-[#f5f9f2]">{content}</a>:<div className="flex items-center gap-3 rounded-2xl border border-[#143124]/8 bg-[#fbfcfa] p-4">{content}</div>}
function DetailCard({icon:Icon,label,value}:{icon:typeof Route;label:string;value:string}){return <div className="rounded-2xl border border-[#143124]/8 bg-[#fbfcfa] p-4"><div className="flex items-center gap-2 text-[#0b6b3a]"><Icon className="size-4"/><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#647667]">{label}</p></div><p className="mt-2 break-words text-sm font-bold leading-6 text-[#24382a]">{value}</p></div>}
