"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { ChangeEvent,useState } from "react";
import { ImagePlus,Save,Trash2 } from "lucide-react";

type CmsImage={url:string;publicId?:string;alt?:string};
type FleetData={_id?:string;name:string;slug:string;modelLabel:string;category:"sedan"|"suv"|"mpv"|"tempo_traveller"|"bus"|"luxury"|"other";seatingLabel:string;seatCount:number;luggageLabel:string;luggageCount:number;ac:boolean;description:string;bestFor:string;badge:string;image:CmsImage|null;gallery:CmsImage[];startingPrice:number;priceUnit:string;localRatePerKm:number;outstationRatePerKm:number;minimumKmPerDay:number;driverAllowancePerDay:number;tollParkingIncluded:boolean;features:string[];suitableFor:string[];featured:boolean;status:"draft"|"published";sortOrder:number;seo:{metaTitle:string;metaDescription:string;keywords:string[];canonicalUrl:string;ogImage:CmsImage|null}};
const empty:FleetData={name:"",slug:"",modelLabel:"",category:"sedan",seatingLabel:"4 Seats",seatCount:4,luggageLabel:"3 Bags",luggageCount:3,ac:true,description:"",bestFor:"",badge:"1 - 4 Seater",image:null,gallery:[],startingPrice:0,priceUnit:"Per Day",localRatePerKm:0,outstationRatePerKm:0,minimumKmPerDay:0,driverAllowancePerDay:0,tollParkingIncluded:false,features:[],suitableFor:[],featured:false,status:"draft",sortOrder:0,seo:{metaTitle:"",metaDescription:"",keywords:[],canonicalUrl:"",ogImage:null}};
const field="w-full rounded-xl border border-[#143124]/15 bg-white px-3.5 py-3 text-sm outline-none focus:border-[#0b6b3a] focus:ring-2 focus:ring-[#0b6b3a]/10";
const label="mb-1.5 block text-xs font-bold uppercase tracking-wide text-[#526858]";
const lines=(v:string)=>v.split("\n").map(x=>x.trim()).filter(Boolean);
const slugify=(v:string)=>v.toLowerCase().trim().replace(/['’]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120);
export function FleetForm({initialData}:{initialData?:FleetData}){const router=useRouter();const[data,setData]=useState<FleetData>({...empty,...initialData,seo:{...empty.seo,...initialData?.seo}});const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState("");const[error,setError]=useState("");const set=<K extends keyof FleetData>(k:K,v:FleetData[K])=>setData(o=>({...o,[k]:v}));
async function upload(file:File){const body=new FormData();body.append("file",file);body.append("folder","fleet");const r=await fetch("/api/admin/uploads",{method:"POST",body});const j=await r.json();if(!r.ok)throw new Error(j.error||"Upload failed.");return j.image as CmsImage}
async function uploadOne(e:ChangeEvent<HTMLInputElement>,target:"image"|"gallery"|"og"){const f=e.target.files?.[0];if(!f)return;setUploading(target);setError("");try{const img=await upload(f);if(target==="image")set("image",{...img,alt:data.name});else if(target==="gallery")set("gallery",[...data.gallery,{...img,alt:data.name}]);else setData(o=>({...o,seo:{...o.seo,ogImage:{...img,alt:o.name}}}))}catch(err){setError(err instanceof Error?err.message:"Upload failed.")}finally{setUploading("");e.target.value=""}}
async function save(status?:"draft"|"published"){setSaving(true);setError("");const payload={...data,status:status??data.status,slug:data.slug||slugify(data.name)};try{const r=await fetch(initialData?`/api/admin/fleet/${initialData._id}`:"/api/admin/fleet",{method:initialData?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to save vehicle.");router.push("/admin/fleet");router.refresh()}catch(err){setError(err instanceof Error?err.message:"Unable to save vehicle.")}finally{setSaving(false)}}
return <div className="space-y-6 pb-24"><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">Fleet CMS</p><h1 className="mt-1 text-3xl font-black">{initialData?"Edit":"Add"} Vehicle</h1><p className="mt-2 text-sm text-[#68806f]">One shared vehicle record can power the Fleet page, taxi service pages and tour-package vehicle choices.</p></div><div className="flex gap-2"><button onClick={()=>save("draft")} disabled={saving} className="rounded-xl border border-[#143124]/15 bg-white px-4 py-3 text-sm font-bold">Save Draft</button><button onClick={()=>save("published")} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#0b6b3a] px-5 py-3 text-sm font-bold text-white"><Save className="size-4"/>{saving?"Saving…":"Publish"}</button></div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
<Section title="Vehicle identity"><div className="grid gap-4 md:grid-cols-2"><F t="Vehicle name"><input className={field} value={data.name} onChange={e=>{set("name",e.target.value);if(!initialData&&!data.slug)set("slug",slugify(e.target.value))}}/></F><F t="Slug"><input className={field} value={data.slug} onChange={e=>set("slug",slugify(e.target.value))}/></F><F t="Model label"><input className={field} value={data.modelLabel} onChange={e=>set("modelLabel",e.target.value)} placeholder="Toyota Etios / Similar"/></F><F t="Category"><select className={field} value={data.category} onChange={e=>set("category",e.target.value as FleetData["category"])}>{["sedan","suv","mpv","tempo_traveller","bus","luxury","other"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></F><F t="Badge"><input className={field} value={data.badge} onChange={e=>set("badge",e.target.value)} placeholder="1 - 4 Seater"/></F><F t="Best for"><input className={field} value={data.bestFor} onChange={e=>set("bestFor",e.target.value)} placeholder="Best for Couples & Small Families"/></F></div><F t="Description"><textarea className={`${field} min-h-28`} value={data.description} onChange={e=>set("description",e.target.value)}/></F><ImagePicker title="Primary vehicle image" image={data.image} uploading={uploading==="image"} onFile={e=>uploadOne(e,"image")} onRemove={()=>set("image",null)}/></Section>
<Section title="Capacity & configuration"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><F t="Seating label"><input className={field} value={data.seatingLabel} onChange={e=>set("seatingLabel",e.target.value)}/></F><F t="Seat count"><input type="number" min="1" className={field} value={data.seatCount} onChange={e=>set("seatCount",Number(e.target.value))}/></F><F t="Luggage label"><input className={field} value={data.luggageLabel} onChange={e=>set("luggageLabel",e.target.value)}/></F><F t="Luggage count"><input type="number" min="0" className={field} value={data.luggageCount} onChange={e=>set("luggageCount",Number(e.target.value))}/></F></div><div className="mt-4 flex flex-wrap gap-5"><Toggle text="Air conditioned" checked={data.ac} onChange={v=>set("ac",v)}/><Toggle text="Featured vehicle" checked={data.featured} onChange={v=>set("featured",v)}/><Toggle text="Toll/parking included" checked={data.tollParkingIncluded} onChange={v=>set("tollParkingIncluded",v)}/></div></Section>
<Section title="Pricing"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><N t="Starting price (₹)" value={data.startingPrice} onChange={v=>set("startingPrice",v)}/><F t="Price unit"><input className={field} value={data.priceUnit} onChange={e=>set("priceUnit",e.target.value)}/></F><N t="Local rate / KM" value={data.localRatePerKm} onChange={v=>set("localRatePerKm",v)}/><N t="Outstation rate / KM" value={data.outstationRatePerKm} onChange={v=>set("outstationRatePerKm",v)}/><N t="Minimum KM / day" value={data.minimumKmPerDay} onChange={v=>set("minimumKmPerDay",v)}/><N t="Driver allowance / day" value={data.driverAllowancePerDay} onChange={v=>set("driverAllowancePerDay",v)}/></div></Section>
<Section title="Features & suitability"><div className="grid gap-4 md:grid-cols-2"><F t="Features — one per line"><textarea className={`${field} min-h-32`} value={data.features.join("\n")} onChange={e=>set("features",lines(e.target.value))}/></F><F t="Suitable for — one per line"><textarea className={`${field} min-h-32`} value={data.suitableFor.join("\n")} onChange={e=>set("suitableFor",lines(e.target.value))}/></F></div><F t="Display order"><input type="number" className={field} value={data.sortOrder} onChange={e=>set("sortOrder",Number(e.target.value))}/></F></Section>
<Section title="Gallery"><div className="grid grid-cols-2 gap-3 md:grid-cols-5">{data.gallery.map((img,i)=><div key={`${img.url}-${i}`} className="relative aspect-[4/3] overflow-hidden rounded-xl"><Image src={img.url} alt={img.alt||data.name} fill unoptimized className="object-contain p-2"/><button onClick={()=>set("gallery",data.gallery.filter((_,x)=>x!==i))} className="absolute right-2 top-2 rounded-full bg-black/70 p-1.5 text-white"><Trash2 className="size-3"/></button></div>)}<label className="grid aspect-[4/3] cursor-pointer place-items-center rounded-xl border border-dashed border-[#143124]/25 bg-[#f7faf5] text-xs font-bold"><span><ImagePlus className="mx-auto mb-1 size-5"/>Add image</span><input type="file" accept="image/*" className="hidden" onChange={e=>uploadOne(e,"gallery")}/></label></div></Section>
<Section title="SEO"><div className="grid gap-4 md:grid-cols-2"><F t="Meta title"><input className={field} value={data.seo.metaTitle} onChange={e=>setData(o=>({...o,seo:{...o.seo,metaTitle:e.target.value}}))}/></F><F t="Canonical URL"><input className={field} value={data.seo.canonicalUrl} onChange={e=>setData(o=>({...o,seo:{...o.seo,canonicalUrl:e.target.value}}))}/></F></div><F t="Meta description"><textarea className={`${field} min-h-24`} value={data.seo.metaDescription} onChange={e=>setData(o=>({...o,seo:{...o.seo,metaDescription:e.target.value}}))}/></F><F t="Keywords — one per line"><textarea className={`${field} min-h-24`} value={data.seo.keywords.join("\n")} onChange={e=>setData(o=>({...o,seo:{...o.seo,keywords:lines(e.target.value)}}))}/></F><ImagePicker title="Open Graph image" image={data.seo.ogImage} uploading={uploading==="og"} onFile={e=>uploadOne(e,"og")} onRemove={()=>setData(o=>({...o,seo:{...o.seo,ogImage:null}}))}/></Section></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-[#143124]/10 bg-white p-5 md:p-6"><h2 className="text-xl font-black">{title}</h2>{children}</section>}
function F({t,children}:{t:string;children:React.ReactNode}){return <label className="block"><span className={label}>{t}</span>{children}</label>}
function N({t,value,onChange}:{t:string;value:number;onChange:(v:number)=>void}){return <F t={t}><input type="number" min="0" step="0.01" className={field} value={value} onChange={e=>onChange(Number(e.target.value))}/></F>}
function Toggle({text,checked,onChange}:{text:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{text}</label>}
function ImagePicker({title,image,uploading,onFile,onRemove}:{title:string;image:CmsImage|null;uploading:boolean;onFile:(e:ChangeEvent<HTMLInputElement>)=>void;onRemove:()=>void}){return <div><p className={label}>{title}</p><div className="flex items-center gap-3">{image?<div className="relative h-28 w-44 overflow-hidden rounded-xl border bg-[#f7f8f5]"><Image src={image.url} alt={image.alt||title} fill unoptimized className="object-contain p-2"/></div>:<div className="grid h-28 w-44 place-items-center rounded-xl border border-dashed text-xs text-[#68806f]">No image</div>}<div className="space-y-2"><label className="block cursor-pointer rounded-xl border px-4 py-2.5 text-sm font-bold">{uploading?"Uploading…":"Choose image"}<input type="file" accept="image/*" className="hidden" onChange={onFile}/></label>{image&&<button onClick={onRemove} className="text-sm font-semibold text-red-600">Remove</button>}</div></div></div>}
