"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { ChangeEvent,useState } from "react";
import { ImagePlus,Save,Trash2 } from "lucide-react";

type CmsImage={url:string;publicId?:string;alt:string};
type GalleryData={_id?:string;title:string;category:"Destinations"|"Vehicles"|"Happy Travelers"|"Travel Moments"|"Events";image:CmsImage|null;caption:string;location:string;destinationId:string|null;fleetId:string|null;featured:boolean;status:"draft"|"published";sortOrder:number};
const empty:GalleryData={title:"",category:"Travel Moments",image:null,caption:"",location:"",destinationId:null,fleetId:null,featured:false,status:"draft",sortOrder:0};
const field="w-full rounded-xl border border-[#143124]/15 bg-white px-3.5 py-3 text-sm outline-none focus:border-[#0b6b3a] focus:ring-2 focus:ring-[#0b6b3a]/10";
const label="mb-1.5 block text-xs font-bold uppercase tracking-wide text-[#526858]";
const categories=["Destinations","Vehicles","Happy Travelers","Travel Moments","Events"] as const;

export function GalleryForm({initialData}:{initialData?:GalleryData}){
 const router=useRouter();const[data,setData]=useState<GalleryData>({...empty,...initialData});const[saving,setSaving]=useState(false);const[uploading,setUploading]=useState(false);const[error,setError]=useState("");
 const set=<K extends keyof GalleryData>(k:K,v:GalleryData[K])=>setData(o=>({...o,[k]:v}));
 async function upload(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setUploading(true);setError("");try{const body=new FormData();body.append("file",f);body.append("folder","gallery");const r=await fetch("/api/admin/uploads",{method:"POST",body});const j=await r.json();if(!r.ok)throw new Error(j.error||"Upload failed.");set("image",{...j.image,alt:data.image?.alt||data.title||"Rani Tours gallery image"})}catch(err){setError(err instanceof Error?err.message:"Upload failed.")}finally{setUploading(false);e.target.value=""}}
 async function save(status:"draft"|"published"){setSaving(true);setError("");try{const r=await fetch(initialData?`/api/admin/gallery/${initialData._id}`:"/api/admin/gallery",{method:initialData?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,status})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to save gallery item.");router.push("/admin/gallery");router.refresh()}catch(err){setError(err instanceof Error?err.message:"Unable to save gallery item.")}finally{setSaving(false)}}
 return <div className="space-y-6 pb-24"><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">Gallery CMS</p><h1 className="mt-1 text-3xl font-black">{initialData?"Edit":"Add"} Gallery Item</h1><p className="mt-2 text-sm text-[#68806f]">Upload and categorize reusable travel media for the gallery and future content relationships.</p></div><div className="flex gap-2"><button onClick={()=>save("draft")} disabled={saving} className="rounded-xl border border-[#143124]/15 bg-white px-4 py-3 text-sm font-bold">Save Draft</button><button onClick={()=>save("published")} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#0b6b3a] px-5 py-3 text-sm font-bold text-white"><Save className="size-4"/>{saving?"Saving…":"Publish"}</button></div></div>{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <section className="space-y-5 rounded-2xl border border-[#143124]/10 bg-white p-5 md:p-6"><h2 className="text-xl font-black">Image & details</h2><div className="grid gap-5 xl:grid-cols-[320px_1fr]"><div><p className={label}>Gallery image</p>{data.image?<div className="space-y-3"><div className="relative aspect-[4/3] overflow-hidden rounded-2xl bg-[#eef3ea]"><Image src={data.image.url} alt={data.image.alt} fill unoptimized className="object-cover"/></div><button onClick={()=>set("image",null)} className="inline-flex items-center gap-2 text-sm font-semibold text-red-600"><Trash2 className="size-4"/>Remove image</button></div>:<label className="grid aspect-[4/3] cursor-pointer place-items-center rounded-2xl border border-dashed border-[#143124]/25 bg-[#f7faf5] text-sm font-bold"><span><ImagePlus className="mx-auto mb-2 size-6"/>{uploading?"Uploading…":"Choose image"}</span><input type="file" accept="image/*" className="hidden" onChange={upload}/></label>}{data.image&&<label className="mt-3 block cursor-pointer rounded-xl border px-4 py-2.5 text-center text-sm font-bold">{uploading?"Uploading…":"Replace image"}<input type="file" accept="image/*" className="hidden" onChange={upload}/></label>}</div><div className="space-y-4"><F t="Title"><input className={field} value={data.title} onChange={e=>set("title",e.target.value)} placeholder="Optional internal/display title"/></F><F t="Alt text"><input className={field} value={data.image?.alt||""} onChange={e=>data.image&&set("image",{...data.image,alt:e.target.value})} placeholder="Describe the image for accessibility and SEO"/></F><div className="grid gap-4 md:grid-cols-2"><F t="Category"><select className={field} value={data.category} onChange={e=>set("category",e.target.value as GalleryData["category"])}>{categories.map(x=><option key={x}>{x}</option>)}</select></F><F t="Location"><input className={field} value={data.location} onChange={e=>set("location",e.target.value)} placeholder="Jodhpur, Rajasthan"/></F></div><F t="Caption"><textarea className={`${field} min-h-28`} value={data.caption} onChange={e=>set("caption",e.target.value)} placeholder="Optional caption shown with this image later"/></F><div className="grid gap-4 md:grid-cols-2"><F t="Display order"><input type="number" className={field} value={data.sortOrder} onChange={e=>set("sortOrder",Number(e.target.value))}/></F><label className="flex items-end gap-2 pb-3 text-sm font-semibold"><input type="checkbox" checked={data.featured} onChange={e=>set("featured",e.target.checked)}/> Featured gallery image</label></div></div></div></section>
 <section className="rounded-2xl border border-[#143124]/10 bg-white p-5 md:p-6"><h2 className="text-xl font-black">Relationships</h2><p className="mt-2 text-sm text-[#68806f]">Destination and Fleet references are supported by the data model. Polished selector controls will be added when we wire cross-module relationships, so raw database IDs are not exposed here.</p></section></div>}
function F({t,children}:{t:string;children:React.ReactNode}){return <label className="block"><span className={label}>{t}</span>{children}</label>}
