"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Edit3, Plus, Search, Star, Trash2 } from "lucide-react";

type Item = { _id:string; title:string; slug:string; serviceType:string; pageTemplate:string; origin?:string; destination?:string; startingPrice:number; priceUnit?:string; status:"draft"|"published"; featured:boolean; heroImage?:{url?:string}; updatedAt:string };

export function TaxiServiceManager(){
  const [items,setItems]=useState<Item[]>([]); const [search,setSearch]=useState(""); const [status,setStatus]=useState("all"); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const p=new URLSearchParams({limit:"50",status});if(search.trim())p.set("search",search.trim());const r=await fetch(`/api/admin/taxi-services?${p}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load taxi services.");setItems(j.items||[])}catch(e){setError(e instanceof Error?e.message:"Unable to load taxi services.")}finally{setLoading(false)}},[search,status]);
  useEffect(()=>{const timer=window.setTimeout(()=>{void load()},250);return()=>window.clearTimeout(timer)},[load]);
  async function remove(item:Item){if(!window.confirm(`Delete “${item.title}”? This cannot be undone.`))return;const r=await fetch(`/api/admin/taxi-services/${item._id}`,{method:"DELETE"});const j=await r.json();if(!r.ok)return window.alert(j.error||"Unable to delete service.");setItems((old)=>old.filter((x)=>x._id!==item._id))}
  const counts=useMemo(()=>({total:items.length,published:items.filter(x=>x.status==="published").length,drafts:items.filter(x=>x.status==="draft").length}),[items]);
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">Content Management</p><h1 className="mt-1 text-3xl font-black">Taxi Services</h1><p className="mt-2 max-w-2xl text-sm text-[#68806f]">Manage local, route, airport, round-trip, corporate and special transport pages from one CMS.</p></div><Link href="/admin/taxi-services/new" className="inline-flex items-center justify-center gap-2 rounded-xl bg-[#0b6b3a] px-5 py-3 text-sm font-bold text-white"><Plus className="size-4"/>Add Taxi Service</Link></div>
    <div className="grid gap-3 sm:grid-cols-3">{[["Total services",counts.total],["Published",counts.published],["Drafts",counts.drafts]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-[#143124]/10 bg-white p-5"><p className="text-sm text-[#68806f]">{l}</p><p className="mt-1 text-3xl font-black">{v}</p></div>)}</div>
    <div className="rounded-2xl border border-[#143124]/10 bg-white p-4"><div className="flex flex-col gap-3 md:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#68806f]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search services, routes or locations…" className="w-full rounded-xl border border-[#143124]/15 bg-[#f8faf6] py-3 pl-10 pr-4 text-sm outline-none focus:border-[#0b6b3a]"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-xl border border-[#143124]/15 bg-[#f8faf6] px-4 py-3 text-sm"><option value="all">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {loading?<div className="rounded-2xl border border-[#143124]/10 bg-white p-10 text-center text-sm text-[#68806f]">Loading taxi services…</div>:items.length===0?<div className="rounded-2xl border border-dashed border-[#143124]/20 bg-white p-12 text-center"><h2 className="font-bold">No taxi services found</h2><p className="mt-2 text-sm text-[#68806f]">Create the first service or adjust the filters.</p></div>:<div className="overflow-hidden rounded-2xl border border-[#143124]/10 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-[#f6f8f4] text-xs uppercase tracking-wide text-[#68806f]"><tr><th className="px-5 py-4">Service</th><th className="px-5 py-4">Template</th><th className="px-5 py-4">Route</th><th className="px-5 py-4">Price</th><th className="px-5 py-4">Status</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{items.map(item=><tr key={item._id} className="border-t border-[#143124]/8"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="relative size-14 overflow-hidden rounded-xl bg-[#eef3ea]">{item.heroImage?.url&&<Image src={item.heroImage.url} alt="" fill unoptimized className="object-cover"/>}</div><div><div className="flex items-center gap-2"><p className="font-bold">{item.title}</p>{item.featured&&<Star className="size-4 fill-amber-400 text-amber-400"/>}</div><p className="mt-1 text-xs text-[#68806f]">{item.serviceType} · /{item.slug}</p></div></div></td><td className="px-5 py-4 capitalize">{item.pageTemplate.replaceAll("_"," ")}</td><td className="px-5 py-4">{item.origin||item.destination?`${item.origin||"—"} → ${item.destination||"—"}`:"—"}</td><td className="px-5 py-4 font-semibold">{item.startingPrice?`₹${Number(item.startingPrice).toLocaleString("en-IN")} ${item.priceUnit||""}`:"On request"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.status==="published"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{item.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Link href={`/admin/taxi-services/${item._id}`} className="rounded-lg border border-[#143124]/10 p-2 hover:bg-[#f3f6f1]" title="Edit"><Edit3 className="size-4"/></Link><button onClick={()=>remove(item)} className="rounded-lg border border-red-200 p-2 text-red-600 hover:bg-red-50" title="Delete"><Trash2 className="size-4"/></button></div></td></tr>)}</tbody></table></div></div>}
  </div>
}
