"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { ChangeEvent, useState } from "react";
import { ImagePlus, Plus, Save, Trash2 } from "lucide-react";

type CmsImage={url:string;publicId?:string;alt?:string};
type Feature={title:string;description:string;icon:string};
type Card={title:string;description:string;image:CmsImage|null};
type PopularRoute={title:string;from:string;to:string;durationLabel:string;startingPrice:number;priceUnit:string;image:CmsImage|null};
type Faq={question:string;answer:string};
type TaxiData={_id?:string;title:string;slug:string;serviceType:string;pageTemplate:"generic"|"route"|"airport"|"round_trip"|"local"|"corporate"|"wedding";tagline:string;shortDescription:string;overview:string;heroImage:CmsImage|null;gallery:CmsImage[];origin:string;destination:string;distanceKm:number;estimatedDuration:string;tripType:string;startingPrice:number;priceUnit:string;priceNote:string;bookingForm:{title:string;showReturnDate:boolean;showTime:boolean;showTransferType:boolean;showFlightNumber:boolean;showVehicleType:boolean;showPassengers:boolean};heroFeatures:Feature[];whyChooseFeatures:Feature[];serviceCards:Card[];popularRoutes:PopularRoute[];useCases:Card[];faq:Faq[];featured:boolean;status:"draft"|"published";sortOrder:number;seo:{metaTitle:string;metaDescription:string;keywords:string[];canonicalUrl:string;ogImage:CmsImage|null}};

const empty:TaxiData={title:"",slug:"",serviceType:"Local Taxi Service",pageTemplate:"generic",tagline:"",shortDescription:"",overview:"",heroImage:null,gallery:[],origin:"Jodhpur",destination:"",distanceKm:0,estimatedDuration:"",tripType:"",startingPrice:0,priceUnit:"",priceNote:"",bookingForm:{title:"Plan Your Ride",showReturnDate:false,showTime:false,showTransferType:false,showFlightNumber:false,showVehicleType:true,showPassengers:true},heroFeatures:[],whyChooseFeatures:[],serviceCards:[],popularRoutes:[],useCases:[],faq:[],featured:false,status:"draft",sortOrder:0,seo:{metaTitle:"",metaDescription:"",keywords:[],canonicalUrl:"",ogImage:null}};
const field="w-full rounded-xl border border-[#143124]/15 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-[#0b6b3a] focus:ring-2 focus:ring-[#0b6b3a]/10";
const label="mb-1.5 block text-xs font-bold uppercase tracking-wide text-[#526858]";
function slugify(v:string){return v.toLowerCase().trim().replace(/['’]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120)}
function lines(v:string){return v.split("\n").map(x=>x.trim()).filter(Boolean)}
function featureText(items:Feature[]){return items.map(x=>`${x.title} | ${x.description} | ${x.icon}`).join("\n")}
function parseFeatures(v:string):Feature[]{return lines(v).map(row=>{const [title,description="",icon=""]=row.split("|").map(x=>x.trim());return{title,description,icon}}).filter(x=>x.title)}

export function TaxiServiceForm({initialData}:{initialData?:TaxiData}){
 const router=useRouter(); const [data,setData]=useState<TaxiData>({...empty,...initialData,bookingForm:{...empty.bookingForm,...initialData?.bookingForm},seo:{...empty.seo,...initialData?.seo}}); const [saving,setSaving]=useState(false);const[uploading,setUploading]=useState("");const[error,setError]=useState("");
 const set=<K extends keyof TaxiData>(k:K,v:TaxiData[K])=>setData(o=>({...o,[k]:v}));
 async function upload(file:File){const body=new FormData();body.append("file",file);body.append("folder","taxi-services");const r=await fetch("/api/admin/uploads",{method:"POST",body});const j=await r.json();if(!r.ok)throw new Error(j.error||"Upload failed.");return j.image as CmsImage}
 async function uploadOne(e:ChangeEvent<HTMLInputElement>,target:"hero"|"gallery"|"og"){const f=e.target.files?.[0];if(!f)return;setUploading(target);try{const img=await upload(f);if(target==="hero")set("heroImage",{...img,alt:data.title});else if(target==="gallery")set("gallery",[...data.gallery,{...img,alt:data.title}]);else setData(o=>({...o,seo:{...o.seo,ogImage:{...img,alt:o.title}}}))}catch(err){setError(err instanceof Error?err.message:"Upload failed.")}finally{setUploading("");e.target.value=""}}
 async function uploadCard(e:ChangeEvent<HTMLInputElement>,group:"serviceCards"|"useCases"|"popularRoutes",index:number){const f=e.target.files?.[0];if(!f)return;setUploading(`${group}-${index}`);try{const img=await upload(f);setData(o=>({...o,[group]:(o[group] as Array<Card|PopularRoute>).map((x,i)=>i===index?{...x,image:img}:x)} as TaxiData))}catch(err){setError(err instanceof Error?err.message:"Upload failed.")}finally{setUploading("");e.target.value=""}}
 async function save(status?:"draft"|"published"){setSaving(true);setError("");const payload={...data,status:status??data.status,slug:data.slug||slugify(data.title)};try{const r=await fetch(initialData?`/api/admin/taxi-services/${initialData._id}`:"/api/admin/taxi-services",{method:initialData?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to save taxi service.");router.push("/admin/taxi-services");router.refresh()}catch(err){setError(err instanceof Error?err.message:"Unable to save taxi service.")}finally{setSaving(false)}}
 return <div className="space-y-6 pb-24">
  <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">Taxi Services CMS</p><h1 className="mt-1 text-3xl font-black">{initialData?"Edit":"Create"} Taxi Service</h1><p className="mt-2 max-w-2xl text-sm text-[#68806f]">Supports the different service templates shown in the approved mockups, including Airport Transfers and Round Trip Taxi.</p></div><div className="flex gap-2"><button onClick={()=>save("draft")} disabled={saving} className="rounded-xl border border-[#143124]/15 bg-white px-4 py-3 text-sm font-bold disabled:opacity-60">Save Draft</button><button onClick={()=>save("published")} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#0b6b3a] px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Save className="size-4"/>{saving?"Saving…":"Publish"}</button></div></div>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <Section title="Service identity & hero" note="Feeds breadcrumbs, hero copy, listing cards and the main service image."><div className="grid gap-4 md:grid-cols-2"><F title="Service title"><input className={field} value={data.title} onChange={e=>{set("title",e.target.value);if(!initialData&&!data.slug)set("slug",slugify(e.target.value))}}/></F><F title="URL slug"><input className={field} value={data.slug} onChange={e=>set("slug",slugify(e.target.value))}/></F><F title="Service type"><input className={field} value={data.serviceType} onChange={e=>set("serviceType",e.target.value)} placeholder="Airport Transfers"/></F><F title="Page template"><select className={field} value={data.pageTemplate} onChange={e=>set("pageTemplate",e.target.value as TaxiData["pageTemplate"])}><option value="generic">Generic service</option><option value="route">Point-to-point route</option><option value="airport">Airport transfer</option><option value="round_trip">Round trip</option><option value="local">Local taxi</option><option value="corporate">Corporate travel</option><option value="wedding">Wedding transport</option></select></F></div><F title="Hero tagline"><input className={field} value={data.tagline} onChange={e=>set("tagline",e.target.value)} placeholder="On-Time. Every Time."/></F><F title="Short hero description"><textarea className={`${field} min-h-24`} value={data.shortDescription} onChange={e=>set("shortDescription",e.target.value)}/></F><F title="Full overview"><textarea className={`${field} min-h-36`} value={data.overview} onChange={e=>set("overview",e.target.value)}/></F><ImagePicker title="Hero image" image={data.heroImage} uploading={uploading==="hero"} onFile={e=>uploadOne(e,"hero")} onRemove={()=>set("heroImage",null)}/></Section>
  <Section title="Route & pricing" note="Leave fields blank when they do not apply to a generic service."><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><F title="Origin"><input className={field} value={data.origin} onChange={e=>set("origin",e.target.value)}/></F><F title="Destination"><input className={field} value={data.destination} onChange={e=>set("destination",e.target.value)}/></F><F title="Distance (KM)"><input type="number" className={field} value={data.distanceKm} onChange={e=>set("distanceKm",Number(e.target.value))}/></F><F title="Estimated duration"><input className={field} value={data.estimatedDuration} onChange={e=>set("estimatedDuration",e.target.value)} placeholder="5–6 Hours"/></F><F title="Trip type"><input className={field} value={data.tripType} onChange={e=>set("tripType",e.target.value)} placeholder="One Way / Round Trip"/></F><F title="Starting price (₹)"><input type="number" className={field} value={data.startingPrice} onChange={e=>set("startingPrice",Number(e.target.value))}/></F><F title="Price unit"><input className={field} value={data.priceUnit} onChange={e=>set("priceUnit",e.target.value)} placeholder="/km or /car"/></F><F title="Display order"><input type="number" className={field} value={data.sortOrder} onChange={e=>set("sortOrder",Number(e.target.value))}/></F></div><F title="Price note"><input className={field} value={data.priceNote} onChange={e=>set("priceNote",e.target.value)}/></F><Toggle checked={data.featured} onChange={v=>set("featured",v)} text="Featured taxi service"/></Section>
  <Section title="Enquiry panel" note="Controls which fields appear in the right-side booking panel for each mockup template."><F title="Panel heading"><input className={field} value={data.bookingForm.title} onChange={e=>setData(o=>({...o,bookingForm:{...o.bookingForm,title:e.target.value}}))}/></F><div className="flex flex-wrap gap-4"><BookingToggle text="Return date" k="showReturnDate" data={data} setData={setData}/><BookingToggle text="Journey time" k="showTime" data={data} setData={setData}/><BookingToggle text="Transfer type" k="showTransferType" data={data} setData={setData}/><BookingToggle text="Flight number" k="showFlightNumber" data={data} setData={setData}/><BookingToggle text="Vehicle type" k="showVehicleType" data={data} setData={setData}/><BookingToggle text="Passengers" k="showPassengers" data={data} setData={setData}/></div></Section>
  <Section title="Hero benefits" note="Use TITLE | DESCRIPTION | ICON KEY, one item per line. These are the small hero benefit items below the main copy."><textarea className={`${field} min-h-36 font-mono`} value={featureText(data.heroFeatures)} onChange={e=>set("heroFeatures",parseFeatures(e.target.value))} placeholder={"Punctual Pickup & Drop | Reliable on-time pickup | clock\nFlight Tracking Support | Real-time updates | plane"}/></Section>
  <Section title="Why choose Rani Tours" note="The six benefit cards shown under the hero in the service mockups."><textarea className={`${field} min-h-44 font-mono`} value={featureText(data.whyChooseFeatures)} onChange={e=>set("whyChooseFeatures",parseFeatures(e.target.value))} placeholder={"On-Time Pickup | We value your time and ensure punctual service. | clock\nSafe & Secure | Verified drivers and secure rides. | shield"}/></Section>
  <CardEditor title="Service cards" note="Examples: Airport Pickup, Airport Drop, VIP Airport Transfers." items={data.serviceCards} onChange={v=>set("serviceCards",v)} uploadCard={(e,i)=>uploadCard(e,"serviceCards",i)} uploading={uploading}/>
  <RouteEditor items={data.popularRoutes} onChange={v=>set("popularRoutes",v)} uploadCard={(e,i)=>uploadCard(e,"popularRoutes",i)} uploading={uploading}/>
  <CardEditor title="Occasions / use cases" note="Examples: Family Vacations, Business Trips, Pilgrimage Tours, Weekend Getaways and Weddings." items={data.useCases} onChange={v=>set("useCases",v)} uploadCard={(e,i)=>uploadCard(e,"useCases",i)} uploading={uploading}/>
  <Section title="Gallery" note="Optional supporting imagery for the dynamic service page."><div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6">{data.gallery.map((img,i)=><div key={`${img.url}-${i}`} className="relative aspect-[4/3] overflow-hidden rounded-xl border"><Image src={img.url} alt={img.alt||"Taxi service gallery"} fill sizes="(min-width: 1280px) 17vw, (min-width: 768px) 25vw, 50vw" unoptimized className="object-cover"/><button type="button" aria-label={`Remove gallery image ${i+1}`} onClick={()=>set("gallery",data.gallery.filter((_,x)=>x!==i))} className="absolute right-2 top-2 rounded-full bg-black/70 p-1.5 text-white"><Trash2 aria-hidden="true" className="size-3"/></button></div>)}<label className="grid aspect-[4/3] cursor-pointer place-items-center rounded-xl border border-dashed border-[#143124]/25 bg-[#f7faf5] text-center text-xs font-bold text-[#607366]"><span><ImagePlus className="mx-auto mb-1 size-5"/>Add image</span><input type="file" accept="image/*" className="hidden" onChange={e=>uploadOne(e,"gallery")}/></label></div></Section>
  <Section title="FAQs" note="Optional service-specific questions and answers."><div className="space-y-3">{data.faq.map((x,i)=><div key={i} className="grid gap-3 rounded-xl border bg-[#fafcf9] p-4 md:grid-cols-[1fr_1.6fr_auto]"><input className={field} value={x.question} onChange={e=>set("faq",data.faq.map((q,n)=>n===i?{...q,question:e.target.value}:q))}/><textarea className={`${field} min-h-20`} value={x.answer} onChange={e=>set("faq",data.faq.map((q,n)=>n===i?{...q,answer:e.target.value}:q))}/><button type="button" aria-label={`Remove FAQ ${i+1}`} onClick={()=>set("faq",data.faq.filter((_,n)=>n!==i))} className="self-start rounded-lg p-3 text-red-600"><Trash2 aria-hidden="true" className="size-4"/></button></div>)}<button onClick={()=>set("faq",[...data.faq,{question:"",answer:""}])} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><Plus className="size-4"/>Add FAQ</button></div></Section>
  <Section title="SEO & social sharing" note="Service-specific metadata for Google and social previews."><div className="grid gap-4 md:grid-cols-2"><F title="Meta title"><input className={field} value={data.seo.metaTitle} onChange={e=>setData(o=>({...o,seo:{...o.seo,metaTitle:e.target.value}}))}/></F><F title="Canonical URL"><input className={field} value={data.seo.canonicalUrl} onChange={e=>setData(o=>({...o,seo:{...o.seo,canonicalUrl:e.target.value}}))}/></F></div><F title="Meta description"><textarea className={`${field} min-h-24`} value={data.seo.metaDescription} onChange={e=>setData(o=>({...o,seo:{...o.seo,metaDescription:e.target.value}}))}/></F><F title="Keywords — one per line"><textarea className={`${field} min-h-24`} value={data.seo.keywords.join("\n")} onChange={e=>setData(o=>({...o,seo:{...o.seo,keywords:lines(e.target.value)}}))}/></F><ImagePicker title="Open Graph image" image={data.seo.ogImage} uploading={uploading==="og"} onFile={e=>uploadOne(e,"og")} onRemove={()=>setData(o=>({...o,seo:{...o.seo,ogImage:null}}))}/></Section>
 </div>
}

function Section({title,note,children}:{title:string;note?:string;children:React.ReactNode}){return <section className="space-y-4 rounded-2xl border border-[#143124]/10 bg-white p-5 shadow-sm md:p-6"><div><h2 className="text-xl font-black">{title}</h2>{note&&<p className="mt-1 text-sm text-[#718174]">{note}</p>}</div>{children}</section>}
function F({title,children}:{title:string;children:React.ReactNode}){return <label className="block"><span className={label}>{title}</span>{children}</label>}
function Toggle({checked,onChange,text}:{checked:boolean;onChange:(v:boolean)=>void;text:string}){return <label className="inline-flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)} className="size-4 accent-[#0b6b3a]"/>{text}</label>}
function BookingToggle({text,k,data,setData}:{text:string;k:keyof TaxiData["bookingForm"];data:TaxiData;setData:React.Dispatch<React.SetStateAction<TaxiData>>}){return <Toggle checked={Boolean(data.bookingForm[k])} onChange={v=>setData(o=>({...o,bookingForm:{...o.bookingForm,[k]:v}}))} text={text}/>}
function ImagePicker({title,image,uploading,onFile,onRemove}:{title:string;image:CmsImage|null;uploading:boolean;onFile:(e:ChangeEvent<HTMLInputElement>)=>void;onRemove:()=>void}){return <div><span className={label}>{title}</span><div className="flex flex-col gap-3 sm:flex-row sm:items-center">{image?<div className="relative h-32 w-52 overflow-hidden rounded-xl border"><Image src={image.url} alt={image.alt||title} fill sizes="208px" unoptimized className="object-cover"/></div>:<div className="grid h-32 w-52 place-items-center rounded-xl border border-dashed text-sm text-[#718174]">No image</div>}<div className="flex gap-2"><label className="cursor-pointer rounded-xl border px-4 py-2.5 text-sm font-bold">{uploading?"Uploading…":"Upload image"}<input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={onFile}/></label>{image&&<button onClick={onRemove} className="rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-600">Remove</button>}</div></div></div>}
function CardEditor({title,note,items,onChange,uploadCard,uploading}:{title:string;note:string;items:Card[];onChange:(v:Card[])=>void;uploadCard:(e:ChangeEvent<HTMLInputElement>,i:number)=>void;uploading:string}){return <Section title={title} note={note}><div className="space-y-3">{items.map((x,i)=><div key={i} className="grid gap-3 rounded-xl border bg-[#fafcf9] p-4 lg:grid-cols-[180px_1fr_auto]"><ImageSlot image={x.image} uploading={uploading.endsWith(`-${i}`)} onFile={e=>uploadCard(e,i)} onRemove={()=>onChange(items.map((v,n)=>n===i?{...v,image:null}:v))}/><div className="space-y-3"><input className={field} value={x.title} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,title:e.target.value}:v))} placeholder="Card title"/><textarea className={`${field} min-h-20`} value={x.description} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,description:e.target.value}:v))} placeholder="Description"/></div><button type="button" aria-label={`Remove ${title} item ${i+1}`} onClick={()=>onChange(items.filter((_,n)=>n!==i))} className="self-start rounded-lg p-3 text-red-600"><Trash2 aria-hidden="true" className="size-4"/></button></div>)}<button onClick={()=>onChange([...items,{title:"",description:"",image:null}])} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><Plus className="size-4"/>Add card</button></div></Section>}
function RouteEditor({items,onChange,uploadCard,uploading}:{items:PopularRoute[];onChange:(v:PopularRoute[])=>void;uploadCard:(e:ChangeEvent<HTMLInputElement>,i:number)=>void;uploading:string}){return <Section title="Popular route cards" note="Used by templates such as Round Trip Taxi for Jodhpur ⇄ Jaipur/Udaipur/Jaisalmer route cards."><div className="space-y-3">{items.map((x,i)=><div key={i} className="grid gap-3 rounded-xl border bg-[#fafcf9] p-4 xl:grid-cols-[160px_1fr_auto]"><ImageSlot image={x.image} uploading={uploading===`popularRoutes-${i}`} onFile={e=>uploadCard(e,i)} onRemove={()=>onChange(items.map((v,n)=>n===i?{...v,image:null}:v))}/><div className="grid gap-3 md:grid-cols-2"><input className={field} value={x.title} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,title:e.target.value}:v))} placeholder="Jodhpur ⇄ Jaipur"/><input className={field} value={x.durationLabel} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,durationLabel:e.target.value}:v))} placeholder="2 Days (Round Trip)"/><input className={field} value={x.from} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,from:e.target.value}:v))} placeholder="From"/><input className={field} value={x.to} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,to:e.target.value}:v))} placeholder="To"/><input type="number" className={field} value={x.startingPrice} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,startingPrice:Number(e.target.value)}:v))} placeholder="Starting price"/><input className={field} value={x.priceUnit} onChange={e=>onChange(items.map((v,n)=>n===i?{...v,priceUnit:e.target.value}:v))} placeholder="Price unit"/></div><button type="button" aria-label={`Remove route ${i+1}`} onClick={()=>onChange(items.filter((_,n)=>n!==i))} className="self-start rounded-lg p-3 text-red-600"><Trash2 aria-hidden="true" className="size-4"/></button></div>)}<button onClick={()=>onChange([...items,{title:"",from:"",to:"",durationLabel:"",startingPrice:0,priceUnit:"",image:null}])} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><Plus className="size-4"/>Add route</button></div></Section>}
function ImageSlot({image,uploading,onFile,onRemove}:{image:CmsImage|null;uploading:boolean;onFile:(e:ChangeEvent<HTMLInputElement>)=>void;onRemove:()=>void}){return <div>{image?<div className="relative h-28 overflow-hidden rounded-xl"><Image src={image.url} alt="" fill sizes="180px" unoptimized className="object-cover"/><button type="button" aria-label="Remove image" onClick={onRemove} className="absolute right-2 top-2 rounded-full bg-black/70 p-1 text-white"><Trash2 aria-hidden="true" className="size-3"/></button></div>:<label className="grid h-28 cursor-pointer place-items-center rounded-xl border border-dashed text-xs font-bold text-[#607366]">{uploading?"Uploading…":"Upload image"}<input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={onFile}/></label>}</div>}
