"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { ChangeEvent, useState } from "react";
import { ImagePlus, Plus, Save, Trash2, UploadCloud } from "lucide-react";

type CmsImage = { url: string; publicId?: string; alt?: string };
type Day = { day: number; title: string; description: string; image: CmsImage | null; stops: { time: string; title: string }[] };
type Faq = { question: string; answer: string };
type PackageData = {
  _id?: string; title: string; slug: string; category: string; location: string; shortDescription: string; overview: string;
  heroImage: CmsImage | null; gallery: CmsImage[]; durationDays: number; durationNights: number; approximateDistanceKm: number; popularAttractions: number;
  tourType: string; flexibleItinerary: boolean; customizable: boolean; startingPrice: number; priceUnit: string; priceNote: string;
  highlights: string[]; itinerary: Day[]; itineraryNote: string; inclusions: string[]; exclusions: string[]; faq: Faq[];
  featured: boolean; status: "draft" | "published"; sortOrder: number;
  seo: { metaTitle: string; metaDescription: string; keywords: string[]; canonicalUrl: string; ogImage: CmsImage | null };
};

const empty: PackageData = { title:"",slug:"",category:"Rajasthan Tour Packages",location:"Rajasthan",shortDescription:"",overview:"",heroImage:null,gallery:[],durationDays:2,durationNights:1,approximateDistanceKm:0,popularAttractions:0,tourType:"Private Tour",flexibleItinerary:true,customizable:true,startingPrice:0,priceUnit:"Per Car",priceNote:"Price may vary based on vehicle type, season and availability.",highlights:[],itinerary:[],itineraryNote:"This is a suggested itinerary. You can customize it according to your preferences.",inclusions:[],exclusions:[],faq:[],featured:false,status:"draft",sortOrder:0,seo:{metaTitle:"",metaDescription:"",keywords:[],canonicalUrl:"",ogImage:null} };

function lines(value: string) { return value.split("\n").map((x)=>x.trim()).filter(Boolean); }
function slugify(value:string){return value.toLowerCase().trim().replace(/['’]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120)}
const field = "w-full rounded-xl border border-[#143124]/15 bg-white px-3.5 py-3 text-sm outline-none transition focus:border-[#0b6b3a] focus:ring-2 focus:ring-[#0b6b3a]/10";
const label = "mb-1.5 block text-xs font-bold uppercase tracking-wide text-[#526858]";

export function TourPackageForm({ initialData }: { initialData?: PackageData }) {
  const router = useRouter();
  const [data,setData]=useState<PackageData>({...empty,...initialData,seo:{...empty.seo,...initialData?.seo}});
  const [saving,setSaving]=useState(false); const [uploading,setUploading]=useState(""); const [error,setError]=useState("");
  const set = <K extends keyof PackageData>(key:K,value:PackageData[K])=>setData((old)=>({...old,[key]:value}));

  async function upload(file:File):Promise<CmsImage>{ const body=new FormData(); body.append("file",file); const res=await fetch("/api/admin/uploads",{method:"POST",body}); const json=await res.json(); if(!res.ok) throw new Error(json.error||"Upload failed."); return json.image; }
  async function imageChange(event:ChangeEvent<HTMLInputElement>, target:"hero"|"gallery"|"og", dayIndex?:number){ const file=event.target.files?.[0]; if(!file)return; setUploading(`${target}-${dayIndex??""}`); setError(""); try{const img=await upload(file); if(target==="hero") set("heroImage",{...img,alt:data.title}); else if(target==="gallery") set("gallery",[...data.gallery,{...img,alt:data.title}]); else if(target==="og") setData((old)=>({...old,seo:{...old.seo,ogImage:{...img,alt:old.title}}})); else if(typeof dayIndex==="number"){} }catch(e){setError(e instanceof Error?e.message:"Upload failed.")}finally{setUploading("");event.target.value=""} }
  async function dayImageChange(event:ChangeEvent<HTMLInputElement>,index:number){const file=event.target.files?.[0];if(!file)return;setUploading(`day-${index}`);try{const img=await upload(file);setData((old)=>({...old,itinerary:old.itinerary.map((d,i)=>i===index?{...d,image:{...img,alt:d.title}}:d)}))}catch(e){setError(e instanceof Error?e.message:"Upload failed.")}finally{setUploading("");event.target.value=""}}

  function addDay(){set("itinerary",[...data.itinerary,{day:data.itinerary.length+1,title:"",description:"",image:null,stops:[]}])}
  function updateDay(index:number, patch:Partial<Day>){set("itinerary",data.itinerary.map((d,i)=>i===index?{...d,...patch}:d))}
  function removeDay(index:number){set("itinerary",data.itinerary.filter((_,i)=>i!==index).map((d,i)=>({...d,day:i+1})))}
  function addFaq(){set("faq",[...data.faq,{question:"",answer:""}])}

  async function save(status?:"draft"|"published"){
    setSaving(true);setError(""); const payload={...data,status:status??data.status,slug:data.slug||slugify(data.title)};
    try{const res=await fetch(initialData?`/api/admin/tour-packages/${initialData._id}`:"/api/admin/tour-packages",{method:initialData?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const json=await res.json(); if(!res.ok) throw new Error(json.error||"Unable to save package."); router.push("/admin/tour-packages"); router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to save package.")}finally{setSaving(false)}
  }

  return <div className="space-y-6 pb-24">
    <div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#68806f]">Tour Package CMS</p><h1 className="mt-1 text-3xl font-black">{initialData?"Edit":"Create"} Tour Package</h1><p className="mt-2 text-sm text-[#68806f]">Fields mirror the approved package-detail mockup and feed the future dynamic page.</p></div><div className="flex gap-2"><button onClick={()=>save("draft")} disabled={saving} className="rounded-xl border border-[#143124]/15 bg-white px-4 py-3 text-sm font-bold disabled:opacity-60">Save Draft</button><button onClick={()=>save("published")} disabled={saving} className="inline-flex items-center gap-2 rounded-xl bg-[#0b6b3a] px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Save className="size-4"/>{saving?"Saving…":"Publish"}</button></div></div>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}

    <Section title="Package identity & hero" note="Used in breadcrumbs, hero section and listing cards."><div className="grid gap-4 md:grid-cols-2"><F label="Package title"><input className={field} value={data.title} onChange={(e)=>{set("title",e.target.value);if(!initialData&&!data.slug)set("slug",slugify(e.target.value))}}/></F><F label="URL slug"><input className={field} value={data.slug} onChange={(e)=>set("slug",slugify(e.target.value))}/></F><F label="Category"><input className={field} value={data.category} onChange={(e)=>set("category",e.target.value)} placeholder="Rajasthan Tour Packages"/></F><F label="Primary location"><input className={field} value={data.location} onChange={(e)=>set("location",e.target.value)}/></F></div><F label="Short hero description"><textarea className={`${field} min-h-24`} value={data.shortDescription} onChange={(e)=>set("shortDescription",e.target.value)}/></F><F label="Full overview"><textarea className={`${field} min-h-36`} value={data.overview} onChange={(e)=>set("overview",e.target.value)}/></F><ImagePicker labelText="Hero image" image={data.heroImage} uploading={uploading==="hero-"} onFile={(e)=>imageChange(e,"hero")} onRemove={()=>set("heroImage",null)}/></Section>

    <Section title="Package overview metrics" note="These populate the quick overview bar visible below the hero."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><NumberField title="Days" value={data.durationDays} onChange={(v)=>set("durationDays",v)}/><NumberField title="Nights" value={data.durationNights} onChange={(v)=>set("durationNights",v)}/><NumberField title="Approx. distance (KM)" value={data.approximateDistanceKm} onChange={(v)=>set("approximateDistanceKm",v)}/><NumberField title="Popular attractions" value={data.popularAttractions} onChange={(v)=>set("popularAttractions",v)}/></div><div className="mt-4 grid gap-4 md:grid-cols-2"><F label="Tour type"><input className={field} value={data.tourType} onChange={(e)=>set("tourType",e.target.value)}/></F><F label="Display order"><input type="number" className={field} value={data.sortOrder} onChange={(e)=>set("sortOrder",Number(e.target.value))}/></F></div><div className="mt-4 flex flex-wrap gap-4"><Toggle checked={data.flexibleItinerary} onChange={(v)=>set("flexibleItinerary",v)} text="Flexible itinerary"/><Toggle checked={data.customizable} onChange={(v)=>set("customizable",v)} text="Customizable"/><Toggle checked={data.featured} onChange={(v)=>set("featured",v)} text="Featured package"/></div></Section>

    <Section title="Pricing" note="Matches the package price CTA block in the mockup."><div className="grid gap-4 md:grid-cols-3"><NumberField title="Starting price (₹)" value={data.startingPrice} onChange={(v)=>set("startingPrice",v)}/><F label="Price unit"><input className={field} value={data.priceUnit} onChange={(e)=>set("priceUnit",e.target.value)} placeholder="Per Car"/></F><F label="Price note"><input className={field} value={data.priceNote} onChange={(e)=>set("priceNote",e.target.value)}/></F></div></Section>

    <Section title="Highlights, inclusions & exclusions" note="Enter one item per line."><div className="grid gap-4 xl:grid-cols-3"><LinesField title="Package highlights" value={data.highlights} onChange={(v)=>set("highlights",v)}/><LinesField title="Package inclusions" value={data.inclusions} onChange={(v)=>set("inclusions",v)}/><LinesField title="Package exclusions" value={data.exclusions} onChange={(v)=>set("exclusions",v)}/></div></Section>

    <Section title="Journey itinerary" note="Each day supports its own image and timestamped stops, matching the vertical itinerary timeline in the mockup."><div className="space-y-4">{data.itinerary.map((day,index)=><div key={index} className="rounded-2xl border border-[#143124]/10 bg-[#f9fbf7] p-4"><div className="mb-4 flex items-center justify-between"><div className="font-black">Day {day.day}</div><button onClick={()=>removeDay(index)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 className="size-4"/></button></div><div className="grid gap-4 md:grid-cols-2"><F label="Day title"><input className={field} value={day.title} onChange={(e)=>updateDay(index,{title:e.target.value})} placeholder="Jodhpur Sightseeing"/></F><F label="Day number"><input type="number" min="1" className={field} value={day.day} onChange={(e)=>updateDay(index,{day:Number(e.target.value)})}/></F></div><F label="Day description"><textarea className={`${field} min-h-20`} value={day.description} onChange={(e)=>updateDay(index,{description:e.target.value})}/></F><F label="Stops — one per line as TIME | ACTIVITY"><textarea className={`${field} min-h-36 font-mono`} value={day.stops.map((s)=>`${s.time} | ${s.title}`).join("\n")} onChange={(e)=>updateDay(index,{stops:lines(e.target.value).map((row)=>{const [time,...rest]=row.split("|");return{time:(time||"").trim(),title:rest.join("|").trim()||time.trim()}})})} placeholder={"09:00 AM | Pickup from your location\n09:30 AM | Visit Mehrangarh Fort"}/></F><ImagePicker labelText="Day image" image={day.image} uploading={uploading===`day-${index}`} onFile={(e)=>dayImageChange(e,index)} onRemove={()=>updateDay(index,{image:null})}/></div>)}<button onClick={addDay} className="inline-flex items-center gap-2 rounded-xl border border-dashed border-[#0b6b3a]/40 bg-[#f7fbf5] px-4 py-3 text-sm font-bold text-[#0b6b3a]"><Plus className="size-4"/> Add itinerary day</button></div><F label="Itinerary note"><input className={field} value={data.itineraryNote} onChange={(e)=>set("itineraryNote",e.target.value)}/></F></Section>

    <Section title="Gallery" note="Additional package imagery for the detail page."><div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-6">{data.gallery.map((img,index)=><div key={`${img.url}-${index}`} className="relative aspect-[4/3] overflow-hidden rounded-xl border border-[#143124]/10"><Image src={img.url} alt={img.alt||"Package gallery"} fill unoptimized className="object-cover"/><button onClick={()=>set("gallery",data.gallery.filter((_,i)=>i!==index))} className="absolute right-2 top-2 rounded-full bg-black/70 p-1.5 text-white"><Trash2 className="size-3"/></button></div>)}<label className="grid aspect-[4/3] cursor-pointer place-items-center rounded-xl border border-dashed border-[#143124]/25 bg-[#f7faf5] text-center text-xs font-bold text-[#607366]"><span><ImagePlus className="mx-auto mb-1 size-5"/>Add image</span><input type="file" accept="image/*" className="hidden" onChange={(e)=>imageChange(e,"gallery")}/></label></div></Section>

    <Section title="Frequently asked questions" note="Optional FAQs can later render below the package details."><div className="space-y-3">{data.faq.map((item,index)=><div key={index} className="grid gap-3 rounded-xl border border-[#143124]/10 bg-[#fafcf9] p-4 md:grid-cols-[1fr_1.6fr_auto]"><input className={field} value={item.question} onChange={(e)=>set("faq",data.faq.map((x,i)=>i===index?{...x,question:e.target.value}:x))} placeholder="Question"/><textarea className={`${field} min-h-20`} value={item.answer} onChange={(e)=>set("faq",data.faq.map((x,i)=>i===index?{...x,answer:e.target.value}:x))} placeholder="Answer"/><button onClick={()=>set("faq",data.faq.filter((_,i)=>i!==index))} className="self-start rounded-lg p-3 text-red-600 hover:bg-red-50"><Trash2 className="size-4"/></button></div>)}<button onClick={addFaq} className="inline-flex items-center gap-2 rounded-xl border border-[#143124]/15 px-4 py-2.5 text-sm font-bold"><Plus className="size-4"/> Add FAQ</button></div></Section>

    <Section title="SEO & social sharing" note="Controls package-specific metadata for search and social previews."><div className="grid gap-4 md:grid-cols-2"><F label="Meta title"><input className={field} value={data.seo.metaTitle} onChange={(e)=>setData((old)=>({...old,seo:{...old.seo,metaTitle:e.target.value}}))}/></F><F label="Canonical URL"><input className={field} value={data.seo.canonicalUrl} onChange={(e)=>setData((old)=>({...old,seo:{...old.seo,canonicalUrl:e.target.value}}))}/></F></div><F label="Meta description"><textarea className={`${field} min-h-24`} value={data.seo.metaDescription} onChange={(e)=>setData((old)=>({...old,seo:{...old.seo,metaDescription:e.target.value}}))}/></F><F label="Keywords — one per line"><textarea className={`${field} min-h-24`} value={data.seo.keywords.join("\n")} onChange={(e)=>setData((old)=>({...old,seo:{...old.seo,keywords:lines(e.target.value)}}))}/></F><ImagePicker labelText="Open Graph image" image={data.seo.ogImage} uploading={uploading==="og-"} onFile={(e)=>imageChange(e,"og")} onRemove={()=>setData((old)=>({...old,seo:{...old.seo,ogImage:null}}))}/></Section>
  </div>;
}

function Section({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <section className="rounded-2xl border border-[#143124]/10 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 border-b border-[#143124]/8 pb-4"><h2 className="text-lg font-black">{title}</h2><p className="mt-1 text-sm text-[#68806f]">{note}</p></div><div className="space-y-4">{children}</div></section>}
function F({label:labelText,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className={label}>{labelText}</span>{children}</label>}
function NumberField({title,value,onChange}:{title:string;value:number;onChange:(value:number)=>void}){return <F label={title}><input type="number" min="0" className={field} value={value} onChange={(e)=>onChange(Number(e.target.value))}/></F>}
function LinesField({title,value,onChange}:{title:string;value:string[];onChange:(value:string[])=>void}){return <F label={title}><textarea className={`${field} min-h-44`} value={value.join("\n")} onChange={(e)=>onChange(lines(e.target.value))}/></F>}
function Toggle({checked,onChange,text}:{checked:boolean;onChange:(v:boolean)=>void;text:string}){return <label className="flex cursor-pointer items-center gap-2 rounded-xl border border-[#143124]/10 bg-[#f8faf6] px-4 py-3 text-sm font-semibold"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)} className="size-4 accent-[#0b6b3a]"/>{text}</label>}
function ImagePicker({labelText,image,uploading,onFile,onRemove}:{labelText:string;image:CmsImage|null;uploading:boolean;onFile:(e:ChangeEvent<HTMLInputElement>)=>void;onRemove:()=>void}){return <div><span className={label}>{labelText}</span>{image?<div className="flex flex-col gap-3 rounded-xl border border-[#143124]/10 bg-[#f8faf6] p-3 sm:flex-row sm:items-center"><div className="relative h-28 w-full overflow-hidden rounded-lg sm:w-48"><Image src={image.url} alt={image.alt||labelText} fill unoptimized className="object-cover"/></div><div className="flex gap-2"><label className="cursor-pointer rounded-lg border border-[#143124]/15 bg-white px-3 py-2 text-xs font-bold">Replace<input type="file" accept="image/*" className="hidden" onChange={onFile}/></label><button onClick={onRemove} className="rounded-lg border border-red-200 bg-white px-3 py-2 text-xs font-bold text-red-600">Remove</button></div></div>:<label className="flex min-h-28 cursor-pointer items-center justify-center gap-3 rounded-xl border border-dashed border-[#143124]/25 bg-[#f8faf6] p-5 text-sm font-bold text-[#557060]"><UploadCloud className="size-5"/>{uploading?"Uploading…":"Upload image (max 8MB)"}<input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={onFile}/></label>}</div>}
