import fs from "node:fs";import path from "node:path";
const root=process.cwd(),fail=[];const exists=p=>fs.existsSync(path.join(root,p)),read=p=>exists(p)?fs.readFileSync(path.join(root,p),"utf8"):"";
for(const p of["app/robots.ts","app/sitemap.ts","lib/seo.ts","app/admin/layout.tsx","public/llms.txt"])if(!exists(p))fail.push(`missing ${p}`);
const layout=read("app/layout.tsx"),robots=read("app/robots.ts"),sitemap=read("app/sitemap.ts"),admin=read("app/admin/layout.tsx"),llms=read("public/llms.txt");for(const token of["metadataBase","openGraph","twitter","robots","application/ld+json"])if(!layout.includes(token))fail.push(`root metadata missing ${token}`);if(!robots.includes("/admin/")||!robots.includes("/api/")||!robots.includes("sitemap"))fail.push("robots policy incomplete");if(!admin.includes("index:false")||!admin.includes("follow:false"))fail.push("admin noindex policy missing");
for(const token of["TaxiService","TourPackage","Destination"])if(!sitemap.includes(token))fail.push(`sitemap missing dynamic ${token} URLs`);
for(const token of["# Rani Tours","https://www.ranitour.in/","/taxi-services","/tour-packages","/destinations","/fleet","/contact","/sitemap.xml","/robots.txt"])if(!llms.includes(token))fail.push(`llms.txt missing ${token}`);if(/\/admin|\/api\//.test(llms))fail.push("llms.txt must not advertise admin/API routes");if(/₹|\bprice\b|\bfare\b/i.test(llms)&&!/does not provide online booking or public fixed taxi pricing/i.test(llms))fail.push("llms.txt pricing language needs explicit no-public-pricing context");
const publicPages=["app/page.tsx","app/about/page.tsx","app/taxi-services/page.tsx","app/tour-packages/page.tsx","app/destinations/page.tsx","app/fleet/page.tsx","app/gallery/page.tsx","app/corporate/page.tsx","app/contact/page.tsx","app/get-quote/page.tsx","app/faq/page.tsx","app/privacy-policy/page.tsx","app/terms-and-conditions/page.tsx","app/cancellation-policy/page.tsx"];for(const p of publicPages){const s=read(p);if(!s.includes("publicMetadata"))fail.push(`${p}: must use publicMetadata for canonical/social metadata`)}
for(const p of["app/taxi-services/[slug]/page.tsx","app/tour-packages/[slug]/page.tsx","app/destinations/[slug]/page.tsx"]){const s=read(p);for(const token of["generateMetadata","publicMetadata","BreadcrumbList","application/ld+json"])if(!s.includes(token))fail.push(`${p}: missing ${token}`)}
for(const p of["app/about/page.tsx","app/taxi-services/page.tsx","app/tour-packages/page.tsx","app/destinations/page.tsx","app/fleet/page.tsx","app/gallery/page.tsx","app/corporate/page.tsx","app/contact/page.tsx","app/get-quote/page.tsx","app/faq/page.tsx"]){if(!read(p).includes("BreadcrumbList"))fail.push(`${p}: missing BreadcrumbList`)}
if(!read("app/faq/page.tsx").includes('"FAQPage"'))fail.push("FAQ page missing FAQPage schema");if(fail.length){console.error("Technical SEO audit failed:\n\n"+fail.map(x=>`- ${x}`).join("\n"));process.exit(1)}console.log(`Technical SEO audit passed (${publicPages.length} public pages, dynamic CMS routes, crawler discovery files and structured data checked).`);
