import mongoose from "mongoose";

const uri=process.env.MONGODB_URI;if(!uri)throw new Error("MONGODB_URI is required");await mongoose.connect(uri);
const Mixed=new mongoose.Schema({}, {strict:false,timestamps:true});const Fleet=mongoose.models.FleetVehicle||mongoose.model("FleetVehicle",Mixed,"fleetvehicles");
const img=(url,alt)=>({url,publicId:"",alt});
const vehicles=[
{name:"Sedan",slug:"sedan",modelLabel:"Toyota Dzire / Etios / Similar",category:"sedan",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"2 Bags",luggageCount:2,ac:true,description:"Comfortable and economical sedan for couples, small families, local sightseeing, airport transfers and outstation journeys.",bestFor:"Best for Small Families",badge:"1 - 4 Seater",image:img("https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&w=1400","White sedan for Rani Tours"),features:["Air conditioned","Comfortable seating","Well maintained","Professional driver"],suitableFor:["Couples","Small families","Local sightseeing","Airport transfers"],featured:true,status:"published",sortOrder:10},
{name:"Innova Crysta",slug:"innova-crysta",modelLabel:"Toyota Innova Crysta / Similar",category:"mpv",seatingLabel:"1 - 6 Seater",seatCount:6,luggageLabel:"4 Bags",luggageCount:4,ac:true,description:"Spacious premium MPV with comfortable seating and luggage space, ideal for Rajasthan tours and long-distance family journeys.",bestFor:"Best for Families",badge:"1 - 6 Seater",image:img("https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1400","Premium white family MPV"),features:["Air conditioned","Spacious cabin","Good luggage capacity","Long-distance comfort"],suitableFor:["Families","Rajasthan tours","Outstation travel","Airport transfers"],featured:true,status:"published",sortOrder:20},
{name:"Toyota Fortuner",slug:"toyota-fortuner",modelLabel:"Toyota Fortuner / Similar",category:"suv",seatingLabel:"1 - 7 Seater",seatCount:7,luggageLabel:"4 Bags",luggageCount:4,ac:true,description:"Premium SUV option for travellers who prefer extra space, road presence and comfort on longer journeys.",bestFor:"Best for Premium Travel",badge:"1 - 7 Seater",image:img("https://images.pexels.com/photos/1335077/pexels-photo-1335077.jpeg?auto=compress&cs=tinysrgb&w=1400","Premium white SUV"),features:["Air conditioned","Premium SUV","Comfortable cabin","Long-distance travel"],suitableFor:["Premium family travel","Corporate guests","Outstation tours"],featured:false,status:"published",sortOrder:30},
{name:"Tempo Traveller 12 Seater",slug:"tempo-traveller-12-seater",modelLabel:"Force Traveller / Similar",category:"tempo_traveller",seatingLabel:"7 - 12 Seater",seatCount:12,luggageLabel:"6 Bags",luggageCount:6,ac:true,description:"Spacious group vehicle for family tours, friends, wedding groups and comfortable outstation travel.",bestFor:"Best for Groups",badge:"12 Seater",image:img("https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=1400","White passenger traveller van"),features:["Air conditioned","Reclining seating","Group luggage space","Experienced driver"],suitableFor:["Family groups","Friends","Wedding travel","Outstation tours"],featured:true,status:"published",sortOrder:40},
{name:"Tempo Traveller 17 Seater",slug:"tempo-traveller-17-seater",modelLabel:"Force Traveller / Similar",category:"tempo_traveller",seatingLabel:"13 - 17 Seater",seatCount:17,luggageLabel:"8 Bags",luggageCount:8,ac:true,description:"Large Force Traveller configuration for bigger families and organised groups travelling across Rajasthan and India.",bestFor:"Best for Large Groups",badge:"17 Seater",image:img("https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=1400#17-seater","White tempo traveller for group travel"),features:["Air conditioned","Group seating","Luggage space","Outstation ready"],suitableFor:["Large families","Tour groups","Corporate groups","Events"],featured:false,status:"published",sortOrder:50},
{name:"Tempo Traveller 21 Seater",slug:"tempo-traveller-21-seater",modelLabel:"Force Traveller / Similar",category:"tempo_traveller",seatingLabel:"18 - 21 Seater",seatCount:21,luggageLabel:"10 Bags",luggageCount:10,ac:true,description:"High-capacity Traveller option for larger groups that want the flexibility of a van with comfortable group seating.",bestFor:"Best for Large Groups",badge:"21 Seater",image:img("https://images.pexels.com/photos/13861/IMG_3496bfree.jpg?auto=compress&cs=tinysrgb&w=1400#21-seater","Large white tempo traveller"),features:["Air conditioned","High capacity","Group luggage space","Long route capable"],suitableFor:["Tour groups","Corporate teams","Wedding groups"],featured:false,status:"published",sortOrder:60},
{name:"Tourist Bus 24 Seater",slug:"tourist-bus-24-seater",modelLabel:"Tata / Eicher / Similar",category:"bus",seatingLabel:"18 - 24 Seater",seatCount:24,luggageLabel:"15 Bags",luggageCount:15,ac:true,description:"Comfortable tourist bus suited to corporate travel, school groups, weddings and organised tours.",bestFor:"Best for Tour Groups",badge:"24 Seater",image:img("https://images.pexels.com/photos/3608967/pexels-photo-3608967.jpeg?auto=compress&cs=tinysrgb&w=1400","Tourist coach bus"),features:["Air conditioned","Group seating","Large luggage capacity","Tour-ready"],suitableFor:["Corporate tours","Weddings","School groups","Group tours"],featured:false,status:"published",sortOrder:70},
{name:"Tourist Bus 32 Seater",slug:"tourist-bus-32-seater",modelLabel:"Tata / Volvo / Similar",category:"bus",seatingLabel:"25 - 32 Seater",seatCount:32,luggageLabel:"20 Bags",luggageCount:20,ac:true,description:"Full-size tourist coach for large groups, events and long-distance tours with maximum group convenience.",bestFor:"Best for Large Groups",badge:"32 Seater",image:img("https://images.pexels.com/photos/3608967/pexels-photo-3608967.jpeg?auto=compress&cs=tinysrgb&w=1400#32-seater","Large tourist coach"),features:["Air conditioned","Large group capacity","Luggage storage","Long-distance comfort"],suitableFor:["Large tour groups","Corporate events","Weddings","Educational tours"],featured:true,status:"published",sortOrder:80},
];
for(const vehicle of vehicles){const payload={...vehicle,startingPrice:0,priceUnit:"",localRatePerKm:0,outstationRatePerKm:0,minimumKmPerDay:0,driverAllowancePerDay:0,tollParkingIncluded:false,gallery:[],publishedAt:new Date(),seo:{metaTitle:`${vehicle.name} Rental in Jodhpur | Rani Tours`,metaDescription:`Travel comfortably with ${vehicle.name} from Rani Tours for local, Rajasthan and outstation journeys.`,keywords:[vehicle.name,"Jodhpur taxi","Rani Tours fleet"],canonicalUrl:`/fleet#${vehicle.slug}`,ogImage:vehicle.image}};await Fleet.findOneAndUpdate({slug:vehicle.slug},{$set:payload},{upsert:true,returnDocument:"after"});console.log(`Seeded ${vehicle.slug}`)}
console.log(`Done. ${vehicles.length} fleet vehicles seeded.`);await mongoose.disconnect();
