import mongoose from "mongoose";

const uri=process.env.MONGODB_URI;if(!uri)throw new Error("MONGODB_URI is required");await mongoose.connect(uri);
const Mixed=new mongoose.Schema({}, {strict:false,timestamps:true});const Fleet=mongoose.models.FleetVehicle||mongoose.model("FleetVehicle",Mixed,"fleetvehicles");
const img=(url,alt)=>({url,publicId:"",alt});

// Remove only obsolete records created by earlier fleet seed versions. This does
// not touch custom vehicles added manually through Admin.
const legacySeedSlugs=[
  "sedan","innova-crysta","tempo-traveller-12-seater","tempo-traveller-17-seater",
  "tempo-traveller-21-seater","tourist-bus-24-seater","tourist-bus-32-seater"
];
await Fleet.deleteMany({slug:{$in:legacySeedSlugs}});

// Every public fleet option has its own image. No URL is shared between cards.
// Car photos match the named model and are white; Traveller/bus photos match the
// corresponding vehicle class/capacity as closely as available.
const vehicleImages={
  etios:"https://maataxiservice.com/images/tour/tour_img1.jpg",
  dzire:"https://menworld.pl/wp-content/uploads/2024/11/2024-Suzuki-Dzire-sedan-fot-3.webp",
  amaze:"https://www.motorbeam.com/wp-content/uploads/2025-Honda-Amaze-White.jpg",
  corolla:"https://assets.cdntoyota.co.za/toyotacms23/attachments/cml83mvsk0mzhphakxkhzvvci-corrolla-hero.desktop.png",
  crysta:"https://images10.gaadi.com/usedcar_image/5193460/original/processed_8e3fe172-32b3-46f8-b929-487c9332a75c.jpg?imwidth=1280",
  fortuner:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2025%20Toyota%20Fortuner%202.8%20Q%204x2%20in%20Platinum%20White%20Pearl%20Mica%2C%20front%20right.jpg",
  traveller12:"https://www.smtravelhub.com/assets/img/tempo-traveller/8.jpeg",
  traveller14:"https://www.southtourism.in/assets/resource/images/transport/slider/tempo-14-seater.jpg",
  traveller17:"https://godavarigrand.com/package_images/Tempo_Traveller_17_Seater/Tempo_Traveller_17_Seater_4b54.jpeg",
  traveller21:"https://ncdtempotravellerhire.com/wp-content/uploads/2025/04/tempo-traveller.jpg.webp",
  bus24:"https://busesandvans.tatamotors.com/assets/buses/files/styles/flexslider_full/s3/trucks/2023-11/sgallery2_15.jpg?VersionId=3cMnzt3prMVMizjX2vk67gDEVOnSo8tk&itok=1EcwU74Z",
  bus32:"https://aaitoursandtravels.com/storage/photos/1/Starbus%20Staff%20AC_0.jpg",
  onDemand:"https://images.pexels.com/photos/3764984/pexels-photo-3764984.jpeg?auto=compress&cs=tinysrgb&w=1400"
};

const vehicles=[
{name:"Toyota Etios",slug:"toyota-etios",modelLabel:"Toyota Platinum Etios",category:"sedan",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"3 Bags",luggageCount:3,ac:true,description:"Reliable and spacious sedan suited to local sightseeing, airport transfers and long-distance taxi journeys.",bestFor:"Best for Couples & Small Families",badge:"1 - 4 Seater",image:img(vehicleImages.etios,"White Toyota Etios sedan"),features:["Air conditioned","Comfortable rear seating","Large boot space","Professional driver"],suitableFor:["Couples","Small families","Local sightseeing","Outstation travel"],featured:true,status:"published",sortOrder:10},
{name:"Maruti Suzuki Dzire",slug:"maruti-suzuki-dzire",modelLabel:"Latest-generation Maruti Suzuki Dzire",category:"sedan",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"2 Bags",luggageCount:2,ac:true,description:"Modern compact sedan offering comfortable city travel and efficient long-distance journeys.",bestFor:"Best for Everyday Travel",badge:"1 - 4 Seater",image:img(vehicleImages.dzire,"Latest-generation white Maruti Suzuki Dzire"),features:["Air conditioned","Comfortable seating","Compact and efficient","Well maintained"],suitableFor:["City travel","Airport transfers","Couples","Small families"],featured:true,status:"published",sortOrder:20},
{name:"Honda Amaze",slug:"honda-amaze",modelLabel:"Latest-generation Honda Amaze",category:"sedan",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"3 Bags",luggageCount:3,ac:true,description:"Comfortable compact sedan with a refined cabin, ideal for business, family and outstation journeys.",bestFor:"Best for Comfortable Sedan Travel",badge:"1 - 4 Seater",image:img(vehicleImages.amaze,"Latest-generation white Honda Amaze"),features:["Air conditioned","Refined cabin","Good luggage space","Comfortable ride"],suitableFor:["Families","Corporate guests","Airport transfers","Outstation travel"],featured:false,status:"published",sortOrder:30},
{name:"Toyota Corolla",slug:"toyota-corolla",modelLabel:"Toyota Corolla / Corolla Altis",category:"luxury",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"3 Bags",luggageCount:3,ac:true,description:"Executive sedan option for travellers who prefer premium comfort for corporate, airport and long-distance journeys.",bestFor:"Best for Executive Travel",badge:"Premium Sedan",image:img(vehicleImages.corolla,"White Toyota Corolla sedan"),features:["Air conditioned","Premium sedan","Comfortable cabin","Executive travel"],suitableFor:["Corporate travel","VIP guests","Airport transfers","Premium journeys"],featured:false,status:"published",sortOrder:40},
{name:"Toyota Innova Crysta",slug:"toyota-innova-crysta",modelLabel:"Toyota Innova Crysta",category:"mpv",seatingLabel:"1 - 7 Seater",seatCount:7,luggageLabel:"5 Bags",luggageCount:5,ac:true,description:"Spacious premium MPV with excellent comfort and luggage capacity for Rajasthan tours and long-distance family travel.",bestFor:"Best for Families",badge:"1 - 7 Seater",image:img(vehicleImages.crysta,"White Toyota Innova Crysta"),features:["Air conditioned","Spacious cabin","Large luggage capacity","Long-distance comfort"],suitableFor:["Families","Rajasthan tours","Outstation travel","Airport transfers"],featured:true,status:"published",sortOrder:50},
{name:"Toyota Fortuner",slug:"toyota-fortuner",modelLabel:"Toyota Fortuner",category:"suv",seatingLabel:"1 - 7 Seater",seatCount:7,luggageLabel:"5 Bags",luggageCount:5,ac:true,description:"Premium SUV for travellers who prefer extra road presence, comfort and space on long journeys.",bestFor:"Best for Premium Family Travel",badge:"1 - 7 Seater",image:img(vehicleImages.fortuner,"Latest white Toyota Fortuner"),features:["Air conditioned","Premium SUV","Comfortable cabin","Long-distance travel"],suitableFor:["Premium family travel","Corporate guests","Outstation tours"],featured:true,status:"published",sortOrder:60},
{name:"Force Tempo Traveller 12 Seater",slug:"force-tempo-traveller-12-seater",modelLabel:"Force Traveller 12 Seater",category:"tempo_traveller",seatingLabel:"12 Seater",seatCount:12,luggageLabel:"6 Bags",luggageCount:6,ac:true,description:"Spacious Force Traveller for family tours, friends, wedding groups and comfortable outstation travel.",bestFor:"Best for Medium Groups",badge:"12 Seater",image:img(vehicleImages.traveller12,"White Force Tempo Traveller 12 seater"),features:["Air conditioned","Reclining seating","Group luggage space","Experienced driver"],suitableFor:["Family groups","Friends","Wedding travel","Outstation tours"],featured:true,status:"published",sortOrder:70},
{name:"Force Tempo Traveller 14 Seater",slug:"force-tempo-traveller-14-seater",modelLabel:"Force Traveller 14 Seater",category:"tempo_traveller",seatingLabel:"14 Seater",seatCount:14,luggageLabel:"7 Bags",luggageCount:7,ac:true,description:"Comfortable 14-seater Force Traveller configuration for medium-sized groups and longer tours.",bestFor:"Best for Family & Tour Groups",badge:"14 Seater",image:img(vehicleImages.traveller14,"White Force Tempo Traveller 14 seater"),features:["Air conditioned","Group seating","Luggage capacity","Long-route comfort"],suitableFor:["Family groups","Tour groups","Corporate teams","Events"],featured:false,status:"published",sortOrder:80},
{name:"Force Tempo Traveller 17 Seater",slug:"force-tempo-traveller-17-seater",modelLabel:"Force Traveller 17 Seater",category:"tempo_traveller",seatingLabel:"17 Seater",seatCount:17,luggageLabel:"8 Bags",luggageCount:8,ac:true,description:"Large Force Traveller configuration for bigger families and organised groups travelling across Rajasthan and India.",bestFor:"Best for Large Groups",badge:"17 Seater",image:img(vehicleImages.traveller17,"White Force Tempo Traveller 17 seater"),features:["Air conditioned","Group seating","Luggage space","Outstation ready"],suitableFor:["Large families","Tour groups","Corporate groups","Events"],featured:false,status:"published",sortOrder:90},
{name:"Force Tempo Traveller 21 Seater",slug:"force-tempo-traveller-21-seater",modelLabel:"Force Traveller 21 Seater",category:"tempo_traveller",seatingLabel:"21 Seater",seatCount:21,luggageLabel:"10 Bags",luggageCount:10,ac:true,description:"High-capacity Force Traveller for larger groups wanting comfortable group seating without moving to a full-size bus.",bestFor:"Best for Large Groups",badge:"21 Seater",image:img(vehicleImages.traveller21,"White Force Tempo Traveller 21 seater"),features:["Air conditioned","High capacity","Group luggage space","Long-route capable"],suitableFor:["Tour groups","Corporate teams","Wedding groups"],featured:true,status:"published",sortOrder:100},
{name:"Tata Tourist Bus 24 Seater",slug:"tata-tourist-bus-24-seater",modelLabel:"Tata Starbus / Tourist Bus 24 Seater",category:"bus",seatingLabel:"24 Seater",seatCount:24,luggageLabel:"15 Bags",luggageCount:15,ac:true,description:"Comfortable Tata tourist bus suited to corporate travel, weddings and organised group tours.",bestFor:"Best for Tour Groups",badge:"24 Seater",image:img(vehicleImages.bus24,"White Tata Starbus 24 seater"),features:["Air conditioned","Group seating","Large luggage capacity","Tour-ready"],suitableFor:["Corporate tours","Weddings","Group tours","Events"],featured:false,status:"published",sortOrder:110},
{name:"Tata Tourist Bus 32 Seater",slug:"tata-tourist-bus-32-seater",modelLabel:"Tata Starbus / Tourist Bus 32 Seater",category:"bus",seatingLabel:"32 Seater",seatCount:32,luggageLabel:"20 Bags",luggageCount:20,ac:true,description:"Full-size Tata tourist bus for large groups, events and long-distance tours with maximum group convenience.",bestFor:"Best for Large Tour Groups",badge:"32 Seater",image:img(vehicleImages.bus32,"White Tata Starbus 32 seater"),features:["Air conditioned","Large group capacity","Luggage storage","Long-distance comfort"],suitableFor:["Large tour groups","Corporate events","Weddings","Educational tours"],featured:true,status:"published",sortOrder:120},
{name:"On Demand Vehicle",slug:"on-demand-vehicle",modelLabel:"Any car, SUV, premium vehicle, Traveller or coach",category:"other",seatingLabel:"As Required",seatCount:1,luggageLabel:"As Required",luggageCount:0,ac:true,description:"Need a specific vehicle that is not listed? Rani Tours can arrange other cars, SUVs, premium vehicles, Travellers or coaches subject to availability.",bestFor:"Best for Special Requirements",badge:"On Demand",image:img(vehicleImages.onDemand,"Vehicle available on demand"),features:["Vehicle arranged on request","Multiple categories available","Flexible seating options","Subject to availability"],suitableFor:["Special requirements","VIP travel","Events","Custom group sizes"],featured:true,status:"published",sortOrder:130},
];

for(const vehicle of vehicles){const payload={...vehicle,startingPrice:0,priceUnit:"",localRatePerKm:0,outstationRatePerKm:0,minimumKmPerDay:0,driverAllowancePerDay:0,tollParkingIncluded:false,gallery:[],publishedAt:new Date(),seo:{metaTitle:`${vehicle.name} Rental in Jodhpur | Rani Tours`,metaDescription:`Travel comfortably with ${vehicle.name} from Rani Tours for local, Rajasthan and outstation journeys.`,keywords:[vehicle.name,"Jodhpur taxi","Rani Tours fleet"],canonicalUrl:`/fleet#${vehicle.slug}`,ogImage:vehicle.image}};await Fleet.findOneAndUpdate({slug:vehicle.slug},{$set:payload},{upsert:true,returnDocument:"after"});console.log(`Seeded ${vehicle.slug}`)}
console.log(`Done. ${vehicles.length} fleet vehicles seeded; obsolete seed records removed.`);await mongoose.disconnect();
