import mongoose from "mongoose";

const uri=process.env.MONGODB_URI;if(!uri)throw new Error("MONGODB_URI is required");await mongoose.connect(uri);
const Mixed=new mongoose.Schema({}, {strict:false,timestamps:true});const Fleet=mongoose.models.FleetVehicle||mongoose.model("FleetVehicle",Mixed,"fleetvehicles");
const img=(url,alt)=>({url,publicId:"",alt});
const whiteVehicles={
  etios:"https://images.unsplash.com/photo-1776505752240-1dd20e928657?auto=format&fit=crop&q=80&w=1760",
  dzire:"https://www.suzukigraaffreinet.co.za/hubfs/Dzire%20-%20Arctic%20White%20Pearl.png",
  amaze:"https://cdn.honda.co.za/main-03/banners/_1200x630_fit_center-center_82_none/HondaAMAZE_Feb2026_banner-SEO.jpg?mtime=1770713363",
  corolla:"https://assets.cdntoyota.co.za/toyotacms23/attachments/cml83mvsk0mzhphakxkhzvvci-corrolla-hero.desktop.png",
  crysta:"https://awsimages.detik.net.id/community/media/visual/2026/06/05/model-terbaru-kembaran-toyota-kijang-innova-reborn-meluncur-di-india-1780622231420_169.jpeg?w=1200",
  fortuner:"https://commons.wikimedia.org/wiki/Special:Redirect/file/2025%20Toyota%20Fortuner%202.8%20Q%204x2%20in%20Platinum%20White%20Pearl%20Mica%2C%20front%20right.jpg",
  traveller12:"https://www.smtravelhub.com/assets/img/tempo-traveller/8.jpeg",
  traveller14:"https://www.jcrcab.com/wp-content/uploads/2020/07/Force-Tempo-Traveller-non-ac-1250x917.jpg",
  traveller17:"https://www.jcrcab.com/wp-content/uploads/2020/07/Force-Tempo-Traveller-non-ac-1250x917.jpg#17-seater",
  traveller21:"https://ncdtempotravellerhire.com/wp-content/uploads/2025/04/tempo-traveller.jpg.webp",
  bus24:"https://images.pexels.com/photos/3608967/pexels-photo-3608967.jpeg?auto=compress&cs=tinysrgb&w=1400",
  bus32:"https://images.pexels.com/photos/3608967/pexels-photo-3608967.jpeg?auto=compress&cs=tinysrgb&w=1400#32-seater",
  onDemand:"https://images.pexels.com/photos/3764984/pexels-photo-3764984.jpeg?auto=compress&cs=tinysrgb&w=1400"
};
const vehicles=[
{name:"Toyota Etios",slug:"toyota-etios",modelLabel:"Toyota Platinum Etios / Similar",category:"sedan",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"3 Bags",luggageCount:3,ac:true,description:"Reliable and spacious sedan suited to local sightseeing, airport transfers and long-distance taxi journeys.",bestFor:"Best for Couples & Small Families",badge:"1 - 4 Seater",image:img(whiteVehicles.etios,"White Toyota Etios"),features:["Air conditioned","Comfortable rear seating","Large boot space","Professional driver"],suitableFor:["Couples","Small families","Local sightseeing","Outstation travel"],featured:true,status:"published",sortOrder:10},
{name:"Maruti Suzuki Dzire",slug:"maruti-suzuki-dzire",modelLabel:"Maruti Suzuki Dzire / Similar",category:"sedan",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"2 Bags",luggageCount:2,ac:true,description:"Modern compact sedan offering comfortable city travel and efficient long-distance journeys.",bestFor:"Best for Everyday Travel",badge:"1 - 4 Seater",image:img(whiteVehicles.dzire,"Latest white Maruti Suzuki Dzire"),features:["Air conditioned","Comfortable seating","Compact and efficient","Well maintained"],suitableFor:["City travel","Airport transfers","Couples","Small families"],featured:true,status:"published",sortOrder:20},
{name:"Honda Amaze",slug:"honda-amaze",modelLabel:"Honda Amaze / Similar",category:"sedan",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"3 Bags",luggageCount:3,ac:true,description:"Comfortable premium compact sedan with a refined cabin, ideal for business, family and outstation journeys.",bestFor:"Best for Comfortable Sedan Travel",badge:"1 - 4 Seater",image:img(whiteVehicles.amaze,"Latest white Honda Amaze"),features:["Air conditioned","Refined cabin","Good luggage space","Comfortable ride"],suitableFor:["Families","Corporate guests","Airport transfers","Outstation travel"],featured:false,status:"published",sortOrder:30},
{name:"Toyota Corolla",slug:"toyota-corolla",modelLabel:"Toyota Corolla / Similar",category:"luxury",seatingLabel:"1 - 4 Seater",seatCount:4,luggageLabel:"3 Bags",luggageCount:3,ac:true,description:"Executive sedan option for travellers who prefer premium comfort for corporate, airport and long-distance journeys.",bestFor:"Best for Executive Travel",badge:"Premium Sedan",image:img(whiteVehicles.corolla,"Latest white Toyota Corolla"),features:["Air conditioned","Premium sedan","Comfortable cabin","Executive travel"],suitableFor:["Corporate travel","VIP guests","Airport transfers","Premium journeys"],featured:false,status:"published",sortOrder:40},
{name:"Toyota Innova Crysta",slug:"toyota-innova-crysta",modelLabel:"Toyota Innova Crysta / Similar",category:"mpv",seatingLabel:"1 - 7 Seater",seatCount:7,luggageLabel:"5 Bags",luggageCount:5,ac:true,description:"Spacious premium MPV with excellent comfort and luggage capacity for Rajasthan tours and long-distance family travel.",bestFor:"Best for Families",badge:"1 - 7 Seater",image:img(whiteVehicles.crysta,"Latest white Toyota Innova Crysta"),features:["Air conditioned","Spacious cabin","Large luggage capacity","Long-distance comfort"],suitableFor:["Families","Rajasthan tours","Outstation travel","Airport transfers"],featured:true,status:"published",sortOrder:50},
{name:"Toyota Fortuner",slug:"toyota-fortuner",modelLabel:"Toyota Fortuner / Similar",category:"suv",seatingLabel:"1 - 7 Seater",seatCount:7,luggageLabel:"5 Bags",luggageCount:5,ac:true,description:"Premium SUV for travellers who prefer extra road presence, comfort and space on long journeys.",bestFor:"Best for Premium Family Travel",badge:"1 - 7 Seater",image:img(whiteVehicles.fortuner,"Latest white Toyota Fortuner"),features:["Air conditioned","Premium SUV","Comfortable cabin","Long-distance travel"],suitableFor:["Premium family travel","Corporate guests","Outstation tours"],featured:true,status:"published",sortOrder:60},
{name:"Force Tempo Traveller 12 Seater",slug:"force-tempo-traveller-12-seater",modelLabel:"Force Traveller 12 Seater",category:"tempo_traveller",seatingLabel:"12 Seater",seatCount:12,luggageLabel:"6 Bags",luggageCount:6,ac:true,description:"Spacious Force Traveller for family tours, friends, wedding groups and comfortable outstation travel.",bestFor:"Best for Medium Groups",badge:"12 Seater",image:img(whiteVehicles.traveller12,"White Force Tempo Traveller 12 seater"),features:["Air conditioned","Reclining seating","Group luggage space","Experienced driver"],suitableFor:["Family groups","Friends","Wedding travel","Outstation tours"],featured:true,status:"published",sortOrder:70},
{name:"Force Tempo Traveller 14 Seater",slug:"force-tempo-traveller-14-seater",modelLabel:"Force Traveller 14 Seater",category:"tempo_traveller",seatingLabel:"14 Seater",seatCount:14,luggageLabel:"7 Bags",luggageCount:7,ac:true,description:"Comfortable 14-seater Force Traveller configuration for medium-sized groups and longer tours.",bestFor:"Best for Family & Tour Groups",badge:"14 Seater",image:img(whiteVehicles.traveller14,"White Force Tempo Traveller 14 seater"),features:["Air conditioned","Group seating","Luggage capacity","Long-route comfort"],suitableFor:["Family groups","Tour groups","Corporate teams","Events"],featured:false,status:"published",sortOrder:80},
{name:"Force Tempo Traveller 17 Seater",slug:"force-tempo-traveller-17-seater",modelLabel:"Force Traveller 17 Seater",category:"tempo_traveller",seatingLabel:"17 Seater",seatCount:17,luggageLabel:"8 Bags",luggageCount:8,ac:true,description:"Large Force Traveller configuration for bigger families and organised groups travelling across Rajasthan and India.",bestFor:"Best for Large Groups",badge:"17 Seater",image:img(whiteVehicles.traveller17,"White Force Tempo Traveller 17 seater"),features:["Air conditioned","Group seating","Luggage space","Outstation ready"],suitableFor:["Large families","Tour groups","Corporate groups","Events"],featured:false,status:"published",sortOrder:90},
{name:"Force Tempo Traveller 21 Seater",slug:"force-tempo-traveller-21-seater",modelLabel:"Force Traveller 21 Seater",category:"tempo_traveller",seatingLabel:"21 Seater",seatCount:21,luggageLabel:"10 Bags",luggageCount:10,ac:true,description:"High-capacity Force Traveller for larger groups wanting comfortable group seating without moving to a full-size bus.",bestFor:"Best for Large Groups",badge:"21 Seater",image:img(whiteVehicles.traveller21,"White Force Tempo Traveller 21 seater"),features:["Air conditioned","High capacity","Group luggage space","Long-route capable"],suitableFor:["Tour groups","Corporate teams","Wedding groups"],featured:true,status:"published",sortOrder:100},
{name:"Tata Tourist Bus 24 Seater",slug:"tata-tourist-bus-24-seater",modelLabel:"Tata Tourist Bus 24 Seater",category:"bus",seatingLabel:"24 Seater",seatCount:24,luggageLabel:"15 Bags",luggageCount:15,ac:true,description:"Comfortable Tata tourist bus suited to corporate travel, school groups, weddings and organised tours.",bestFor:"Best for Tour Groups",badge:"24 Seater",image:img(whiteVehicles.bus24,"White Tata tourist bus 24 seater"),features:["Air conditioned","Group seating","Large luggage capacity","Tour-ready"],suitableFor:["Corporate tours","Weddings","School groups","Group tours"],featured:false,status:"published",sortOrder:110},
{name:"Tata Tourist Bus 32 Seater",slug:"tata-tourist-bus-32-seater",modelLabel:"Tata Tourist Bus 32 Seater",category:"bus",seatingLabel:"32 Seater",seatCount:32,luggageLabel:"20 Bags",luggageCount:20,ac:true,description:"Full-size Tata tourist bus for large groups, events and long-distance tours with maximum group convenience.",bestFor:"Best for Large Tour Groups",badge:"32 Seater",image:img(whiteVehicles.bus32,"White Tata tourist bus 32 seater"),features:["Air conditioned","Large group capacity","Luggage storage","Long-distance comfort"],suitableFor:["Large tour groups","Corporate events","Weddings","Educational tours"],featured:true,status:"published",sortOrder:120},
{name:"On Demand Vehicle",slug:"on-demand-vehicle",modelLabel:"Any Car / SUV / Premium Vehicle / Coach on request",category:"other",seatingLabel:"As Required",seatCount:1,luggageLabel:"As Required",luggageCount:0,ac:true,description:"Need a specific vehicle that is not listed? Rani Tours can arrange cars, SUVs, premium vehicles, travellers or coaches on demand subject to availability.",bestFor:"Best for Special Requirements",badge:"On Demand",image:img(whiteVehicles.onDemand,"On-demand vehicle arrangement"),features:["Vehicle arranged on request","Multiple categories available","Flexible seating options","Subject to availability"],suitableFor:["Special requirements","VIP travel","Events","Custom group sizes"],featured:true,status:"published",sortOrder:130},
];
for(const vehicle of vehicles){const payload={...vehicle,startingPrice:0,priceUnit:"",localRatePerKm:0,outstationRatePerKm:0,minimumKmPerDay:0,driverAllowancePerDay:0,tollParkingIncluded:false,gallery:[],publishedAt:new Date(),seo:{metaTitle:`${vehicle.name} Rental in Jodhpur | Rani Tours`,metaDescription:`Travel comfortably with ${vehicle.name} from Rani Tours for local, Rajasthan and outstation journeys.`,keywords:[vehicle.name,"Jodhpur taxi","Rani Tours fleet"],canonicalUrl:`/fleet#${vehicle.slug}`,ogImage:vehicle.image}};await Fleet.findOneAndUpdate({slug:vehicle.slug},{$set:payload},{upsert:true,returnDocument:"after"});console.log(`Seeded ${vehicle.slug}`)}
console.log(`Done. ${vehicles.length} fleet vehicles seeded.`);await mongoose.disconnect();
