import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarDays, CheckCircle2, Headphones, MapPin, Route, ShieldCheck, Sparkles } from "lucide-react";
import { SiteCta } from "@/components/layout/site-cta";
import { publicImageUrl } from "@/lib/public-image";
type Img={url:string;alt?:string};type Card={title:string;description?:string;image?:Img|null;meta?:string};type D={title:string;slug:string;tagline?:string;shortDescription:string;overview?:string;heroImage:Img;gallery?:Img[];state?:string;region?:string;bestTimeToVisit?:string;idealDuration?:string;knownFor?:string[];attractions?:Card[];experiences?:Card[];travelTips?:string[];ctaTitle?:string;ctaDescription?:string};
export function DestinationDetail({destination:d}:{destination:D}){const seen=new Set([d.heroImage.url]);const unique=(img?:Img|null)=>{if(!img?.url||seen.has(img.url))return null;seen.add(img.url);return img};const attractions=(d.attractions||[]).map(x=>({...x,image:unique(x.image)}));const experiences=(d.experiences||[]).map(x=>({...x,image:unique(x.image)}));const gallery=(d.gallery||[]).map(unique).filter(Boolean) as Img[];return <div className="bg-white text-[#17341f]">
<section className="relative isolate min-h-[520px] overflow-hidden bg-[#073d25] text-white"><Image src={publicImageUrl(d.heroImage.url,1600)} alt={d.heroImage.alt||d.title} fill priority sizes="100vw" className="object-cover opacity-55"/><div className="absolute inset-0 bg-gradient-to-r from-[#042b1a]/95 via-[#073d25]/70 to-transparent"/><div className="relative mx-auto max-w-[1180px] px-4 py-14 lg:py-20"><div className="text-[11px] text-white/70"><Link href="/">Home</Link><span className="mx-2">›</span><Link href="/destinations">Destinations</Link><span className="mx-2">›</span>{d.title}</div><p className="mt-8 text-xs font-black uppercase tracking-[.2em] text-[#e1bd58]">{d.state||d.region||"India"}</p><h1 className="mt-2 max-w-3xl font-serif text-5xl font-black leading-none sm:text-6xl">{d.title}</h1>{d.tagline?<h2 className="mt-3 font-serif text-2xl font-black text-[#e1bd58]">{d.tagline}</h2>:null}<p className="mt-5 max-w-2xl text-[15px] leading-7 text-white/82">{d.shortDescription}</p><div className="mt-8 flex flex-wrap gap-6 text-xs font-bold"><span className="inline-flex items-center gap-2"><CalendarDays className="size-5 text-[#e1bd58]"/>{d.bestTimeToVisit||"Plan year-round"}</span><span className="inline-flex items-center gap-2"><Route className="size-5 text-[#e1bd58]"/>{d.idealDuration||"Flexible duration"}</span><span className="inline-flex items-center gap-2"><MapPin className="size-5 text-[#e1bd58]"/>{d.state||d.region||"India"}</span></div></div></section>
<section className="relative z-10 mx-auto -mt-7 max-w-[1120px] px-4"><div className="grid gap-3 rounded-2xl border border-[#17341f]/10 bg-white p-4 shadow-lg sm:grid-cols-2 lg:grid-cols-4">{(d.knownFor||[]).slice(0,4).map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-[#f8faf6] px-4 py-3"><span className="grid size-9 place-items-center rounded-full bg-[#edf5e8] text-[#08713b]">{i===0?<MapPin className="size-4"/>:<Sparkles className="size-4"/>}</span><p className="text-xs font-black">{x}</p></div>)}</div></section>
<section className="mx-auto max-w-[1180px] px-4 py-14"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#08713b]">About {d.title}</p><h2 className="mt-2 font-serif text-3xl font-black">Discover the Destination</h2><div className="mt-3 h-px w-20 bg-[#e1bd58]"/></div><div><p className="text-[15px] leading-8 text-[#59665d]">{d.overview||d.shortDescription}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Info label="Best Time to Visit" value={d.bestTimeToVisit||"Flexible"}/><Info label="Ideal Duration" value={d.idealDuration||"Flexible"}/></div></div></div></section>
{attractions.length?<section className="bg-[#f7f8f2] py-14"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow="Top Attractions" title={`Best Places to Visit in ${d.title}`}/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{attractions.map((x,i)=><article key={`${x.title}-${i}`} className="overflow-hidden rounded-2xl bg-white shadow-sm">{x.image?<div className="relative h-44"><Image src={publicImageUrl(x.image.url,640)} alt={x.image.alt||x.title} fill sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" className="object-cover"/></div>:null}<div className="p-4"><h3 className="font-serif text-lg font-black">{x.title}</h3><p className="mt-2 text-xs leading-5 text-[#5c685f]">{x.description}</p>{x.meta?<p className="mt-3 text-[10px] font-black text-[#735613]">{x.meta}</p>:null}</div></article>)}</div></div></section>:null}
{experiences.length?<section className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow="Things to Do" title={`Experiences in ${d.title}`}/><div className="mt-9 grid gap-5 md:grid-cols-3">{experiences.map((x,i)=><article key={`${x.title}-${i}`} className="overflow-hidden rounded-2xl border border-[#17341f]/10 bg-white">{x.image?<div className="relative h-48"><Image src={publicImageUrl(x.image.url,760)} alt={x.image.alt||x.title} fill sizes="(min-width: 768px) 33vw, 100vw" className="object-cover"/></div>:null}<div className="p-5"><h3 className="font-serif text-xl font-black">{x.title}</h3><p className="mt-2 text-sm leading-6 text-[#59665d]">{x.description}</p></div></article>)}</div></section>:null}
{gallery.length?<section className="bg-[#f7f8f2] py-14"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow="Travel Gallery" title={`See More of ${d.title}`}/><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{gallery.map((g,i)=><div key={`${g.url}-${i}`} className={`relative overflow-hidden rounded-2xl ${i===0?"h-64 sm:col-span-2":"h-52"}`}><Image src={publicImageUrl(g.url,i===0?1000:560)} alt={g.alt||d.title} fill sizes={i===0?"(min-width: 1024px) 40vw, (min-width: 640px) 100vw, 100vw":"(min-width: 1024px) 20vw, (min-width: 640px) 50vw, 100vw"} className="object-cover"/></div>)}</div></div></section>:null}
<section className="mx-auto max-w-[1180px] px-4 py-14"><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div><Heading eyebrow="Travel Tips" title={`Plan ${d.title} Better`}/><div className="mt-7 grid gap-3 sm:grid-cols-2">{(d.travelTips||[]).map((t,i)=><div key={`${t}-${i}`} className="flex gap-3 rounded-xl bg-[#f7f9f5] p-4 text-xs leading-5 text-[#59665d]"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-[#08713b]"/>{t}</div>)}</div></div><aside className="rounded-[24px] bg-[#0b4d29] p-6 text-white"><Headphones className="size-7 text-[#e1bd58]"/><h3 className="mt-4 font-serif text-2xl font-black">{d.ctaTitle||`Plan Your ${d.title} Trip`}</h3><p className="mt-3 text-sm leading-6 text-white/78">{d.ctaDescription||"Tell us your dates and preferences and our team will help plan the journey."}</p><Link href="/get-quote" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#e4b63f] px-4 py-3 text-xs font-black text-[#17341f] transition hover:bg-[#f0c653]">Get a Quote <ArrowRight className="size-4"/></Link></aside></div></section>
<section className="border-t border-[#17341f]/8 py-12"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow="Why Travel With Rani Tours?" title="Comfortable, Flexible & Reliable"/><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,"Trusted & Reliable"],[Route,"Flexible Itineraries"],[MapPin,"Local Route Knowledge"],[Headphones,"24/7 Support"]].map(([Icon,t])=>{const I=Icon as typeof ShieldCheck;return <div key={String(t)} className="text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-[#edf5e8] text-[#08713b]"><I className="size-5"/></span><h3 className="mt-3 font-black">{String(t)}</h3></div>})}</div></div></section><SiteCta/></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-[#f7f9f5] p-4"><p className="text-[9px] font-black uppercase tracking-[.14em] text-[#59665d]">{label}</p><p className="mt-2 text-sm font-black">{value}</p></div>}
function Heading({eyebrow,title}:{eyebrow:string;title:string}){return <div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#08713b]">{eyebrow}</p><h2 className="mt-2 font-serif text-3xl font-black sm:text-4xl">{title}</h2><div className="mx-auto mt-3 h-px w-20 bg-[#e1bd58]"/></div>}
