import { NextRequest,NextResponse } from "next/server";
import { Types } from "mongoose";
import { logAdminActivity,requireAdminApi } from "@/lib/admin-auth";
import { connectToDatabase } from "@/lib/db";
import { Enquiry } from "@/models/Enquiry";

type Context={params:Promise<{id:string}>};
const statuses=new Set(["new","contacted","qualified","converted","closed","spam"]);
const priorities=new Set(["low","normal","high","urgent"]);
export async function GET(_:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid enquiry id."},{status:400});await connectToDatabase();const item=await Enquiry.findById(id).lean();if(!item)return NextResponse.json({error:"Enquiry not found."},{status:404});return NextResponse.json({item});}
export async function PATCH(request:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid enquiry id."},{status:400});const body=await request.json() as Record<string,unknown>;await connectToDatabase();const item=await Enquiry.findById(id);if(!item)return NextResponse.json({error:"Enquiry not found."},{status:404});if(typeof body.status==="string"&&statuses.has(body.status)){item.status=body.status;if(body.status==="contacted")item.lastContactedAt=new Date();if(body.status==="converted")item.convertedAt=new Date();}if(typeof body.priority==="string"&&priorities.has(body.priority))item.priority=body.priority;if(typeof body.note==="string"&&body.note.trim())item.notes.push({text:body.note.trim().slice(0,2000),adminId:admin.id,adminName:admin.name,createdAt:new Date()});await item.save();await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Updated enquiry",entity:"Enquiry",entityId:id,metadata:{status:item.status,priority:item.priority,source:item.source}});return NextResponse.json({item});}
export async function DELETE(_:NextRequest,{params}:Context){const admin=await requireAdminApi();if(!admin)return NextResponse.json({error:"Unauthorized"},{status:401});const{id}=await params;if(!Types.ObjectId.isValid(id))return NextResponse.json({error:"Invalid enquiry id."},{status:400});await connectToDatabase();const item=await Enquiry.findByIdAndDelete(id);if(!item)return NextResponse.json({error:"Enquiry not found."},{status:404});await logAdminActivity({adminId:admin.id,adminName:admin.name,action:"Deleted enquiry",entity:"Enquiry",entityId:id,metadata:{name:item.name,source:item.source}});return NextResponse.json({success:true});}
