import { createHash } from "node:crypto";
import { NextRequest } from "next/server";
import { connectToDatabase } from "@/lib/db";
import { cleanText,validateContactInput,validateQuoteInput } from "@/lib/form-validation";
import { rateLimit } from "@/lib/rate-limit";
import { enforceBodySize,getClientIp,hasJsonContentType,jsonNoStore } from "@/lib/security";
import { Enquiry } from "@/models/Enquiry";

const duplicateWindowMs=30_000;
export async function POST(request:NextRequest){
 const sizeError=enforceBodySize(request,32*1024);if(sizeError)return sizeError;if(!hasJsonContentType(request))return jsonNoStore({error:"Unsupported request format."},{status:415});
 const ip=cleanText(await getClientIp(),80);const limit=rateLimit(`public-enquiry:${ip}`,8,10*60*1000);if(!limit.allowed)return jsonNoStore({error:"Too many enquiry attempts. Please wait a few minutes and try again."},{status:429,headers:{"Retry-After":String(limit.retryAfterSeconds)}});
 const ua=cleanText(request.headers.get("user-agent"),500);if(!ua||/sqlmap|nikto|masscan|nmap|acunetix|nessus|zgrab/i.test(ua))return jsonNoStore({error:"Request rejected."},{status:403});
 const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body||Array.isArray(body))return jsonNoStore({error:"Invalid request."},{status:400});
 const source=body.source==="contact"?"contact":body.source==="get_quote"?"get_quote":null;if(!source)return jsonNoStore({error:"Invalid enquiry source."},{status:400});const requestId=cleanText(body.requestId,120);if(requestId&&!/^[A-Za-z0-9._:-]{8,120}$/.test(requestId))return jsonNoStore({error:"Invalid request identifier."},{status:400});
 let data:Record<string,unknown>;let coreFingerprintParts:string[];
 if(source==="contact"){const result=validateContactInput({name:body.name,phone:body.phone,email:body.email,subject:body.subject,message:body.message});if(!result.valid)return jsonNoStore({error:Object.values(result.errors)[0],errors:result.errors},{status:400});data={requestId:requestId||undefined,source,...result.data};coreFingerprintParts=[source,result.data.name.toLowerCase(),result.data.phone,result.data.email,result.data.subject.toLowerCase(),result.data.message.toLowerCase()];}
 else{const result=validateQuoteInput({name:body.name,phone:body.phone,email:body.email,journeyType:body.journeyType,pickup:body.pickup,destination:body.destination,travelDate:body.travelDate,travellers:body.travellers,duration:body.duration,vehicle:body.vehicle,message:body.message});if(!result.valid)return jsonNoStore({error:Object.values(result.errors)[0],errors:result.errors},{status:400});const date=new Date(`${result.data.travelDate}T00:00:00.000Z`);data={requestId:requestId||undefined,source,...result.data,travelDate:date};coreFingerprintParts=[source,result.data.name.toLowerCase(),result.data.phone,result.data.email,result.data.journeyType.toLowerCase(),result.data.pickup.toLowerCase(),result.data.destination.toLowerCase(),result.data.travelDate];}
 Object.assign(data,{ipAddress:ip,userAgent:ua});const fingerprint=createHash("sha256").update(coreFingerprintParts.join("|")).digest("hex"),now=Date.now(),currentBucket=Math.floor(now/duplicateWindowMs),previousBucket=currentBucket-1,currentKey=createHash("sha256").update(`${fingerprint}|${currentBucket}`).digest("hex"),previousKey=createHash("sha256").update(`${fingerprint}|${previousBucket}`).digest("hex");data.dedupeKey=currentKey;
 await connectToDatabase();if(requestId){const existing=await Enquiry.findOne({requestId}).select("_id").lean();if(existing)return jsonNoStore({success:true,id:String(existing._id),duplicate:true},{status:200});}const duplicate=await Enquiry.findOne({dedupeKey:{$in:[currentKey,previousKey]},createdAt:{$gte:new Date(now-duplicateWindowMs)}}).select("_id").lean();if(duplicate)return jsonNoStore({success:true,id:String(duplicate._id),duplicate:true},{status:200});
 try{const item=await Enquiry.create(data);return jsonNoStore({success:true,id:item._id.toString()},{status:201});}catch(error:unknown){if(typeof error==="object"&&error!==null&&"code" in error&&(error as{code?:number}).code===11000){const existing=requestId?await Enquiry.findOne({$or:[{requestId},{dedupeKey:{$in:[currentKey,previousKey]}}]}).select("_id").lean():await Enquiry.findOne({dedupeKey:{$in:[currentKey,previousKey]}}).select("_id").lean();if(existing)return jsonNoStore({success:true,id:String(existing._id),duplicate:true},{status:200});}throw error;}
}
