import { Schema, model, models } from "mongoose";

const MediaSchema=new Schema({url:{type:String,default:""},publicId:{type:String,default:""}},{_id:false});
const InvoiceSchema=new Schema({
  invoiceNumber:{type:String,required:true,unique:true,index:true},
  billDate:{type:Date,required:true,default:Date.now,index:true},
  customerName:{type:String,required:true,trim:true,index:true},
  customerPhone:{type:String,default:"",trim:true,index:true},
  travelDate:{type:Date,default:null,index:true},
  travelType:{type:String,enum:["itinerary","distance"],default:"distance"},
  itinerary:{type:String,default:""},
  vehicleName:{type:String,required:true,trim:true},
  vehicleNumber:{type:String,required:true,trim:true,index:true},
  totalKm:{type:Number,required:true,min:0,default:0},
  pricePerKm:{type:Number,required:true,min:0,default:0},
  distanceAmount:{type:Number,default:0,min:0},
  tollIncluded:{type:Boolean,default:false},
  tollAmount:{type:Number,default:0,min:0},
  parkingIncluded:{type:Boolean,default:false},
  parkingAmount:{type:Number,default:0,min:0},
  otherCharges:{type:Number,default:0,min:0},
  otherChargesLabel:{type:String,default:"Other Charges"},
  taxableAmount:{type:Number,default:0,min:0},
  taxRate:{type:Number,required:true,min:0.01,default:5},
  taxAmount:{type:Number,default:0,min:0},
  total:{type:Number,default:0,min:0},
  amountPaid:{type:Number,default:0,min:0},
  balanceDue:{type:Number,default:0,min:0},
  paymentStatus:{type:String,enum:["unpaid","partial","paid"],default:"unpaid",index:true},
  paymentMethod:{type:String,enum:["cash","upi","bank_transfer","card","other",""],default:""},
  status:{type:String,enum:["draft","issued","cancelled"],default:"issued",index:true},
  notes:{type:String,default:""},
  signatoryName:{type:String,default:"Authorized Signatory"},
  signatureImage:{type:MediaSchema,default:()=>({url:"",publicId:""})},
  stampImage:{type:MediaSchema,default:()=>({url:"",publicId:""})},
  createdBy:{type:Schema.Types.ObjectId,ref:"AdminUser",default:null},
  updatedBy:{type:Schema.Types.ObjectId,ref:"AdminUser",default:null},
},{timestamps:true});
InvoiceSchema.index({invoiceNumber:"text",customerName:"text",customerPhone:"text",vehicleNumber:"text",itinerary:"text"});
export const Invoice=models.Invoice||model("Invoice",InvoiceSchema);
