import Image from "next/image";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, CheckCircle2, Clock3, Headphones, Luggage, MapPin, Phone, Route, ShieldCheck, Sparkles, UsersRound, X } from "lucide-react";
import { siteContact } from "@/lib/site-data";

type Img={url:string;alt?:string};
type Stop={time:string;title:string};
type Day={day:number;title:string;description?:string;image?:Img|null;stops?:Stop[]};
type Faq={question:string;answer:string};
type Package={title:string;slug:string;category:string;location:string;shortDescription:string;overview?:string;heroImage:Img;gallery?:Img[];durationDays:number;durationNights:number;approximateDistanceKm?:number;popularAttractions?:number;tourType?:string;flexibleItinerary?:boolean;customizable?:boolean;highlights?:string[];itinerary?:Day[];itineraryNote?:string;inclusions?:string[];exclusions?:string[];faq?:Faq[]};
type Fleet={_id:string;name:string;modelLabel?:string;image?:Img;seatCount?:number;seatingLabel?:string;luggageCount?:number;luggageLabel?:string;ac?:boolean};
type Related={_id:string;title:string;slug:string;category:string;location:string;shortDescription:string;durationDays:number;durationNights:number;heroImage:Img};

export function TourPackageDetail({pkg,fleet,related}:{pkg:Package;fleet:Fleet[];related:Related[]}){
  const seen=new Set<string>([pkg.heroImage.url]);
  const uniqueImage=(img?:Img|null)=>{if(!img?.url||seen.has(img.url))return null;seen.add(img.url);return img};
  const itinerary=(pkg.itinerary||[]).map((item)=>({...item,image:uniqueImage(item.image)}));
  const gallery=(pkg.gallery||[]).map((img)=>uniqueImage(img)).filter(Boolean) as Img[];
  const perfectFor=(pkg.highlights||[]).slice(0,4);
  return <div className="bg-white text-[#17341f]">
    <section className="relative isolate overflow-hidden bg-[#073d25] text-white">
      <Image src={pkg.heroImage.url} alt={pkg.heroImage.alt||pkg.title} fill priority className="object-cover opacity-50"/><div className="absolute inset-0 bg-gradient-to-r from-[#042b1a]/96 via-[#073d25]/82 to-[#073d25]/45"/>
      <div className="relative mx-auto max-w-[1180px] px-4 py-12 lg:py-16">
        <div className="flex flex-wrap items-center gap-2 text-[10px] font-bold text-white/70"><Link href="/">Home</Link><span>›</span><Link href="/tour-packages">Tour Packages</Link><span>›</span><span>{pkg.title}</span></div>
        <p className="mt-8 text-[10px] font-black uppercase tracking-[.2em] text-[#e1bd58]">{pkg.category}</p><h1 className="mt-2 max-w-3xl font-serif text-4xl font-black leading-[1.04] sm:text-5xl lg:text-[58px]">{pkg.title}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-white/83">{pkg.shortDescription}</p>
        <div className="mt-8 grid max-w-4xl grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
          <Fact icon={CalendarDays} label="Duration" value={`${pkg.durationDays} Days / ${pkg.durationNights} Nights`}/><Fact icon={Route} label="Distance" value={pkg.approximateDistanceKm?`Approx. ${pkg.approximateDistanceKm} km`:"Flexible route"}/><Fact icon={MapPin} label="Attractions" value={pkg.popularAttractions?`${pkg.popularAttractions}+ places`:"Multiple sights"}/><Fact icon={UsersRound} label="Tour Type" value={pkg.tourType||"Private Tour"}/><Fact icon={Sparkles} label="Itinerary" value={pkg.flexibleItinerary?"Flexible":"Planned"}/><Fact icon={CheckCircle2} label="Package" value={pkg.customizable?"Customizable":"Curated"}/>
        </div>
      </div>
    </section>

    <section className="mx-auto max-w-[1180px] px-4 py-14"><div className="grid gap-9 lg:grid-cols-[.82fr_1.18fr]"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#08713b]">Tour Overview</p><h2 className="mt-2 font-serif text-3xl font-black">A Journey Designed Around You</h2><div className="mt-3 h-px w-20 bg-[#e1bd58]"/></div><div><p className="text-[15px] leading-8 text-[#637066]">{pkg.overview||pkg.shortDescription}</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-[#eef5df] px-3 py-2 text-xs font-bold text-[#08713b]">{pkg.location}</span>{(pkg.highlights||[]).slice(0,4).map((x)=><span key={x} className="rounded-full bg-[#f7f8f2] px-3 py-2 text-xs font-bold text-[#667369]">{x}</span>)}</div></div></div></section>

    <section className="bg-[#f7f8f2] py-14"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow="Day by Day Journey" title="Tour Itinerary"/><div className="mt-10 grid gap-8 lg:grid-cols-[1.5fr_.72fr]">
      <div className="space-y-5">{itinerary.map((item)=><article key={item.day} className="overflow-hidden rounded-2xl border border-[#17341f]/8 bg-white shadow-sm"><div className="grid md:grid-cols-[220px_1fr]">{item.image?<div className="relative min-h-48"><Image src={item.image.url} alt={item.image.alt||item.title} fill className="object-cover"/></div>:null}<div className="p-5"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#08713b] text-xs font-black text-white">{item.day}</span><div><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#a17d25]">Day {item.day}</p><h3 className="mt-1 font-serif text-xl font-black">{item.title}</h3></div></div>{item.description?<p className="mt-3 text-sm leading-6 text-[#69756c]">{item.description}</p>:null}{item.stops?.length?<div className="mt-4 space-y-2 border-l border-[#d9dfd5] pl-4">{item.stops.map((s,index)=><div key={`${s.time}-${s.title}-${index}`} className="flex gap-3 text-xs"><span className="w-20 shrink-0 font-black text-[#08713b]">{s.time}</span><span className="text-[#667369]">{s.title}</span></div>)}</div>:null}</div></div></article>)}{pkg.itineraryNote?<div className="rounded-xl border border-[#e1bd58]/35 bg-[#fffaf0] px-4 py-3 text-xs leading-5 text-[#6f6750]"><b>Note:</b> {pkg.itineraryNote}</div>:null}</div>
      <aside className="space-y-4 lg:sticky lg:top-28 lg:self-start"><ListCard title="Package Inclusions" items={pkg.inclusions||[]} positive/><ListCard title="Package Exclusions" items={pkg.exclusions||[]}/>{perfectFor.length?<div className="rounded-2xl border border-[#17341f]/8 bg-[#eef5df] p-5"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#08713b]">Perfect For</p><div className="mt-4 grid grid-cols-2 gap-3">{perfectFor.map((x)=><div key={x} className="rounded-xl bg-white/75 p-3 text-center text-xs font-bold">{x}</div>)}</div></div>:null}<div className="rounded-2xl bg-[#073d25] p-5 text-white"><Headphones className="size-6 text-[#e1bd58]"/><h3 className="mt-3 font-serif text-xl font-black">Need help planning?</h3><p className="mt-2 text-xs leading-5 text-white/72">Our travel team can customize the route, duration and sightseeing around your preferences.</p><Link href="/get-quote" className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#b3df24] px-4 py-2.5 text-xs font-black text-[#073b25]">Get Free Quote <ArrowRight className="size-3.5"/></Link></div></aside>
    </div></div></section>

    {gallery.length?<section className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow="Tour Gallery" title="A Glimpse of the Journey"/><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{gallery.map((img,index)=><div key={`${img.url}-${index}`} className={`relative overflow-hidden rounded-2xl ${index===0?"sm:col-span-2 lg:col-span-2 h-64":"h-52"}`}><Image src={img.url} alt={img.alt||`${pkg.title} gallery`} fill className="object-cover transition duration-500 hover:scale-105"/></div>)}</div></section>:null}

    {fleet.length?<section className="bg-[#f7f8f2] py-14"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow="Our Vehicles for Your Comfort" title="Choose the Right Vehicle for Your Trip"/><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{fleet.slice(0,8).map((v)=><article key={v._id} className="overflow-hidden rounded-2xl border border-[#17341f]/8 bg-white"><div className="relative h-40 bg-[#fafbf8]">{v.image?.url?<Image src={v.image.url} alt={v.image.alt||v.name} fill className="object-contain p-4"/>:null}</div><div className="p-4"><h3 className="font-serif text-lg font-black">{v.name}</h3>{v.modelLabel?<p className="mt-1 text-xs text-[#7b877d]">{v.modelLabel}</p>:null}<div className="mt-3 flex gap-4 text-[11px] text-[#657168]"><span className="inline-flex items-center gap-1"><UsersRound className="size-3.5 text-[#08713b]"/>{v.seatingLabel||`${v.seatCount||"—"} seats`}</span><span className="inline-flex items-center gap-1"><Luggage className="size-3.5 text-[#08713b]"/>{v.luggageLabel||`${v.luggageCount||"—"} bags`}</span></div></div></article>)}</div></div></section>:null}

    <section className="mx-auto max-w-[1180px] px-4 py-14"><Heading eyebrow="Why Choose Rani Tours?" title="Travel with Confidence"/><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck,"Trusted & Reliable","Experienced local travel support for your journey."],[Sparkles,"Flexible Planning","Itineraries can be adjusted around your preferences."],[CheckCircle2,"Comfort & Safety","Comfortable vehicles and thoughtful trip coordination."],[Headphones,"24/7 Support","Help before and throughout your journey when required."]].map(([Icon,title,text])=>{const I=Icon as typeof ShieldCheck;return <div key={String(title)} className="rounded-2xl border border-[#17341f]/8 bg-white p-5 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-[#eef5df] text-[#08713b]"><I className="size-5"/></span><h3 className="mt-4 font-serif text-lg font-black">{String(title)}</h3><p className="mt-2 text-xs leading-5 text-[#6b786e]">{String(text)}</p></div>})}</div></section>

    {related.length?<section className="bg-[#f7f8f2] py-14"><div className="mx-auto max-w-[1180px] px-4"><Heading eyebrow="You May Also Like" title="More Tour Packages"/><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{related.slice(0,4).map((item)=><Link key={item._id} href={`/tour-packages/${item.slug}`} className="group overflow-hidden rounded-2xl border border-[#17341f]/8 bg-white"><div className="relative h-44"><Image src={item.heroImage.url} alt={item.heroImage.alt||item.title} fill className="object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-4"><p className="text-[9px] font-black uppercase tracking-[.15em] text-[#a17d25]">{item.category}</p><h3 className="mt-1 font-serif text-lg font-black">{item.title}</h3><p className="mt-2 text-[11px] text-[#69756c]">{item.durationDays} Days / {item.durationNights} Nights</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-[#08713b]">View Details <ArrowRight className="size-3.5"/></span></div></Link>)}</div></div></section>:null}

    {pkg.faq?.length?<section className="mx-auto max-w-[900px] px-4 py-14"><Heading eyebrow="Frequently Asked Questions" title="Good to Know"/><div className="mt-8 space-y-3">{pkg.faq.map((faq,index)=><details key={`${faq.question}-${index}`} className="rounded-2xl border border-[#17341f]/8 bg-white p-5"><summary className="cursor-pointer list-none font-serif text-base font-black">{faq.question}</summary><p className="mt-3 text-sm leading-6 text-[#69756c]">{faq.answer}</p></details>)}</div></section>:null}

    <section className="mx-auto max-w-[1180px] px-4 pb-14"><div className="rounded-[26px] bg-[#073d25] px-6 py-8 text-white md:flex md:items-center md:justify-between md:gap-8 md:px-10"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#e1bd58]">Plan Your Trip Today</p><h2 className="mt-2 font-serif text-2xl font-black sm:text-3xl">Ready to explore with {pkg.title}?</h2><p className="mt-2 text-xs text-white/70">Send your dates and preferences and we’ll help tailor the journey.</p></div><div className="mt-5 flex flex-wrap gap-3 md:mt-0"><a href={siteContact.phones[0].href} className="inline-flex items-center gap-2 rounded-lg border border-white/20 bg-white/10 px-5 py-3 text-xs font-black"><Phone className="size-4"/>{siteContact.phones[0].display}</a><a href={siteContact.whatsapp} className="rounded-lg bg-[#b3df24] px-5 py-3 text-xs font-black text-[#073b25]">WhatsApp Us</a></div></div></section>
  </div>;
}

function Fact({icon:Icon,label,value}:{icon:typeof CalendarDays;label:string;value:string}){return <div className="rounded-xl border border-white/12 bg-white/8 p-3 backdrop-blur"><Icon className="size-4 text-[#e1bd58]"/><p className="mt-2 text-[8px] font-black uppercase tracking-[.12em] text-white/55">{label}</p><p className="mt-1 text-[11px] font-bold leading-4">{value}</p></div>}
function Heading({eyebrow,title}:{eyebrow:string;title:string}){return <div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.19em] text-[#08713b]">{eyebrow}</p><h2 className="mt-2 font-serif text-3xl font-black sm:text-4xl">{title}</h2><div className="mx-auto mt-3 h-px w-20 bg-[#e1bd58]"/></div>}
function ListCard({title,items,positive=false}:{title:string;items:string[];positive?:boolean}){return <div className="rounded-2xl border border-[#17341f]/8 bg-white p-5"><h3 className={`font-serif text-xl font-black ${positive?"text-[#08713b]":"text-[#9b3b31]"}`}>{title}</h3><div className="mt-4 space-y-3">{items.map((item)=><div key={item} className="flex gap-2 text-xs leading-5 text-[#657168]">{positive?<Check className="mt-0.5 size-4 shrink-0 text-[#08713b]"/>:<X className="mt-0.5 size-4 shrink-0 text-[#b34a3d]"/>}<span>{item}</span></div>)}</div></div>}
